import {createWeeklyNarrativeService} from "../../../domain/services/WeeklyNarrativeService";
import WeeklyBriefingScreen from "../../../screens/WeeklyBriefingScreen";
import PersistedLegacyWeeklyScreen from "../../../screens/DailyBriefingScreen";
import {adaptWeeklyArtifactForPresentation} from "../../../domain/services/WeeklyBriefingPresentationService";
import {createBriefingReconciliationPresentation} from "../../../domain/services/BriefingReconciliationPresentationService";
import {getProductionBriefingNavigationReadService,loadProductionBoundedFounderReadContext} from "../../../application/composition/productionApplicationComposition";
import {projectConfidenceExplanationForSurface} from "../../../domain/presentation/confidenceExplanationPresentation";
export const dynamic="force-dynamic";
export default async function WeeklyPage(){const {repositories}=await loadProductionBoundedFounderReadContext({collections:["user","dailyBriefings","briefingReconciliationWorkItems"]});const user=await repositories.users.getCurrentUser();const [artifact,workItems]=await Promise.all([createWeeklyNarrativeService({repositories}).getLatest({userId:user.id}),repositories.briefingReconciliationWorkItems.listWorkItems(user.id)]);if(!artifact)return <main className="app-surface min-h-screen"><div className="mx-auto max-w-[393px] px-4 py-10"><p className="text-sm font-extrabold uppercase tracking-[0.12em] text-[var(--primary)]">Weekly Briefing</p><h1 className="mt-3 text-3xl font-extrabold text-[var(--text-primary)]">No persisted Weekly Briefing is available yet.</h1></div></main>;if(!artifact.briefing?.weeklyNarrative)return <PersistedLegacyWeeklyScreen backHref="/briefings/review" backLabel="Briefing History" briefing={artifact.briefing} eyebrow="Weekly Briefing"/>;const presented=await adaptWeeklyArtifactForPresentation({artifact,timeZone:user.timeZone});const narrative=presented.briefing.weeklyNarrative;const assessment=await getProductionBriefingNavigationReadService().getConfidenceAssessment({assessmentId:narrative.goalConfidence?.assessmentId});const enriched={...narrative,goalConfidence:projectConfidenceExplanationForSurface(narrative.goalConfidence,{assessment,surface:"weekly"})};const reconciliation=createBriefingReconciliationPresentation({publicationRootId:artifact.id,workItems});return <WeeklyBriefingScreen narrative={enriched} reconciliation={reconciliation}/>;}
