import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "scripts/deployPhysiqueOS.test.js",
      "scripts/providerBuildSafety.test.js",
      "src/app/api/health/route.test.js",
      "src/app/api/private-evidence/[...path]/route.test.js",
      "src/application/media/AuthorizedMediaService.test.js",
      "src/application/read-models/Phase3ReadModelService.test.js",
      "src/application/read-models/WebParityComposition.test.js",
      "src/application/training/TrainingReadService.test.js",
      "src/platform/auth/foundationIdentity.test.js",
      "src/platform/database/foundationDatabase.test.js",
      "src/platform/object-storage/SpacesPrivateObjectProvider.test.js",
      "src/app/log/training/TrainingLoggerMutationBoundary.test.js",
      "src/app/log/training/TrainingLoggerProductionState.test.js",
      "src/domain/models/trainingExerciseIdentity.test.js",
      "src/domain/models/trainingExecutionVariant.test.js",
      "src/domain/services/August10FalseTrainingRetractionService.test.js",
      "src/domain/services/CanonicalTrainingExecutionVariant.test.js",
      "src/domain/services/TrainingLoggerAppleHealthService.test.js",
      "src/domain/services/TrainingLoggerCanonicalPipeline.test.js",
      "src/domain/services/TrainingLoggerDraftRecoveryService.test.js",
      "src/domain/services/TrainingLoggerProgressionService.test.js",
      "src/domain/services/TrainingLoggerSuggestionService.test.js",
      "src/domain/services/TrainingSupersetPerformanceContext.test.js",
      "src/navigation/trainingTimelineNavigation.test.js",
      "src/screens/TrainingDayScreen.test.js",
      "src/screens/TrainingKnowledgeScreen.test.js",
      "src/domain/interpreters/PhotoObservationModelV2.test.js",
      "src/domain/services/CanonicalPhotoSessionReadService.test.js",
      "src/domain/services/PendingPhotoReviewEditing.test.js",
      "src/domain/services/PhotoEventContextService.test.js",
      "src/domain/services/PhotoEventNarrativeService.test.js",
      "src/application/composition/productionPhotoEventNarrativeComposition.test.js",
      "src/domain/services/PhotoPIObservationCompatibility.test.js",
      "src/screens/PhotoEventBriefingScreen.test.js",
      "src/screens/PhotosEvidenceContextProduction.test.js",
      "src/domain/services/EvidenceReviewService.test.js",
      "src/domain/services/EvidenceReviewCommitRecovery.test.js",
      "src/domain/services/EvidenceCanonicalCommitRecoveryService.test.js",
      "src/domain/services/PILowerLevelCanonicalEvidenceBoundedCommit.test.js",
      "src/domain/services/PostConfirmationOrchestrator.test.js",
      "src/domain/services/EvidenceReviewPresentationService.test.js",
      "src/domain/services/GoalEvaluationJsonSafety.test.js",
      "src/application/read-models/EvidenceConfirmationReadService.test.js",
      "src/app/evidence/review/[reviewId]/actions.test.js",
      "src/domain/services/MorningCheckInPersistenceService.test.js",
      "src/domain/services/ExecutionPriorityProjectionService.test.js",
      "src/domain/services/ProtocolProvenanceResolverService.test.js",
      "src/domain/services/HomeHeroContract.test.js",
      "src/domain/services/HomeGoalTrajectoryService.test.js",
      "src/domain/services/HomeExecutionPriorityIntegration.test.js",
      "src/domain/confidence/ConfidenceV2ScenarioAcceptance.test.js",
      "src/application/briefings/BriefingReadService.test.js",
      "src/domain/services/GoalNavigationRouteResolver.test.js",
    ],
    fileParallelism: false,
    maxWorkers: 1,
    minWorkers: 1,
  },
});
