const requested=new URLSearchParams(location.search).get('theme');
document.documentElement.dataset.theme=requested==='light'?'light':'dark';
const el=document.getElementById('screens');

const status=`<div class="status"><span>9:41</span><span class="status-icons">● ▰</span></div>`;
const nav=(back,title='',action='')=>`<div class="nav"><span class="nav-back">${back}</span><span class="nav-title">${title}</span><span class="nav-action">${action}</span></div>`;
const phone=(content,{back='‹ Evidence Hub',title='',action='',tall=0,extra=''}={})=>`<div class="phone ${tall?'tall':''} ${extra}" ${tall?`style="--phone-h:${tall}px"`:''}>${status}${nav(back,title,action)}<div class="scroll">${content}</div></div>`;
const article=(id,family,title,desc,content,opts={})=>`<article class="screen-card" data-screen="${id}" data-family="${family}"><div class="screen-meta"><span class="screen-id">${id}</span><div><h2>${title}</h2><p>${desc}</p></div></div><div class="stage">${phone(content,opts)}</div></article>`;
const silhouette=(cls='thumb')=>`<div class="${cls}"><div class="silhouette"></div></div>`;
const scope=(all)=>`<div class="scope"><div class="scope-label">Viewing Goal</div><div class="pills"><span class="pill selected">Build Lean Mass</span><span class="pill">Visible Abs</span><span class="pill">${all}</span></div></div>`;
const photoHeader=`<div class="header"><div class="icon">P</div><div><div class="eyebrow">Evidence Report</div><div class="title">Progress Photos</div><div class="subtitle">What PhysiqueOS currently understands.</div></div></div>`;
const dexaHeader=`<div class="header"><div class="icon">D</div><div><div class="eyebrow">Evidence Report</div><div class="title">DEXA</div><div class="subtitle">BodySpec body-composition scan history.</div></div></div>`;
const latestPhoto=`<section class="section card"><div class="hero-row">${silhouette('thumb hero-thumb')}<div><div class="section-head"><span class="eyebrow">Latest Photo Set</span><span class="tag">4 views</span></div><div class="section-title" style="font-size:20px">Aug 30, 2026</div><div class="row-copy" style="margin-top:7px">Compared against: 3/4 poses have prior comparisons</div><div class="action" style="margin-top:13px">Open gallery →</div></div></div></section>`;
const historyRow=(date,views,context='Comparison available')=>`<div class="history-row">${silhouette('thumb')}<div><div class="row-label">${date}</div><div class="row-copy">${views} views</div><div class="row-copy">${context}</div></div><span class="row-label">View</span></div>`;
const photoHistory=(expanded=false)=>`<section class="section card"><div class="disclosure-row"><div><div class="section-title">Uploaded Photos</div><div class="row-copy">Tap any record to inspect the original image and comparison context.</div></div><span class="action">${expanded?'Close':'Show All'}</span></div><div style="margin-top:12px">${historyRow('Aug 30, 2026','4','3/4 poses have prior comparisons')}${historyRow('Aug 16, 2026','3','3/3 poses have prior comparisons')}${historyRow('Jul 18, 2026','3','3/3 poses have prior comparisons')}${expanded?historyRow('Jun 14, 2026','3','3/3 poses have prior comparisons')+historyRow('May 24, 2026','3','First photo set'):''}</div></section>`;
const rootPhotos=`${photoHeader}${scope('All Photos')}${latestPhoto}<div class="primary-action">Read Photo Briefing</div>${photoHistory(false)}`;

const comparison=`<section class="section card"><div class="photo-grid"><div><div class="photo-tile"><div class="silhouette"></div></div><div class="date">Aug 16, 2026</div><div class="role">PREVIOUS</div></div><div><div class="photo-tile"><div class="silhouette"></div></div><div class="date">Aug 30, 2026</div><div class="role">CURRENT</div></div></div></section>`;
const interpretation=`<section class="section card interpretation"><div class="eyebrow">Interpretation</div><p style="margin-top:7px">Visual comparison available for front relaxed.</p><ul class="bullets"><li>Same pose matched against Aug 16, 2026.</li></ul></section>`;
const conditions=`<section class="section card interpretation"><div class="eyebrow" style="color:var(--muted)">Capture Conditions</div><p style="margin-top:7px">Evening, post-workout, pump present.</p></section>`;
const source=(expanded=false)=>`<section class="section card"><div class="disclosure-row"><span class="eyebrow" style="color:var(--muted)">Source History</span><span class="chev">${expanded?'⌃':'⌄'}</span></div>${expanded?'<div class="source-copy">This comparison uses your Front Relaxed photos from Aug 16, 2026 and Aug 30, 2026.</div>':''}</section>`;
const pager=`<div class="pager"><span class="disabled">Previous</span><span>Next</span></div>`;
const detail=(sourceExpanded=false)=>`<div class="eyebrow">Progress Photo Evidence</div><div class="title" style="font-size:25px;margin:5px 0 2px">Front Relaxed</div><div class="subtitle" style="margin-bottom:16px">Aug 30, 2026 · 1 of 4 poses</div>${comparison}${interpretation}${conditions}${source(sourceExpanded)}${pager}`;

const screens=[];
screens.push(article('P1','photos','Photos root — production hierarchy','Visual latest set, full-width Briefing action and thumbnail history retain their production prominence.',rootPhotos));
screens.push(article('P2','photos','Uploaded Photos — Show All','Expanded history remains thumbnail-based with date, view count, comparison context and View action.',`${photoHeader}${scope('All Photos')}${photoHistory(true)}`,{tall:1040}));
screens.push(article('P3','photos','Gallery detail — paired pose','Previous and Current remain simultaneous, followed by Interpretation, Capture Conditions, Source History and pose navigation.',detail(false),{back:'',title:'Photo Set',action:'Close',tall:1180}));
screens.push(article('P4','photos','Source History — expanded','The independent Source History disclosure expands in place without moving the paired media or pager.',detail(true),{back:'',title:'Photo Set',action:'Close',tall:1240}));
screens.push(article('P5','photos','Image inspection','Tapping either paired image opens the current full-screen inspector at the tapped item.',`<div class="viewer-photo"><div class="silhouette"></div><div class="viewer-caption"><b>Front Relaxed · Previous</b><br>Aug 16, 2026 · 1 of 2<br><span style="color:#aeb8bd">Pinch to zoom · double-tap · swipe for Current</span></div></div>`,{back:'✕',title:'',action:'',extra:'viewer'}));
screens.push(article('P6','photos','Media loading, retry and unavailable','Tile and inspection states retain recoverable retry, permanent unavailable and low-resolution fallback behavior.',`<div class="eyebrow">Progress Photo Media</div><div class="state-stack" style="margin-top:12px"><div class="media-state"><div><div class="spinner"></div><div class="state-copy">Loading photo…</div></div></div><div class="media-state"><div><div class="state-title">The photo couldn't be loaded.</div><span class="retry">Try again</span></div></div><div class="media-state"><div><div class="state-title">Photo unavailable</div><div class="state-copy">This item cannot be retrieved.</div></div></div><div class="media-state"><div><div class="state-title">Full resolution unavailable</div><span class="retry">Try again</span></div></div></div>`,{back:'‹ Photo Set',title:'Front Relaxed'}));

const chart=(title,value,unit='lb',tone='')=>`<div class="chart-block"><div class="chart-title">${title}</div><div class="chart-copy">Structured values extracted from BodySpec reports.</div><div class="chart"><svg viewBox="0 0 300 76"><path class="line ${tone}" d="M5 18 L78 34 L150 62 L224 50 L295 46"/><circle class="dot" cx="295" cy="46" r="3.5"/></svg></div><div class="row-copy">Aug 30, 2026 / ${title}: ${value}${unit}</div><div class="axis"><span>May 24</span><span>${value}${unit}</span><span>Aug 30</span></div></div>`;
const summary=`<div class="summary-grid section"><div class="metric"><div class="metric-label">Body Fat</div><div class="metric-value">9.4%</div></div><div class="metric"><div class="metric-label">Fat Mass</div><div class="metric-value">16.9 lb</div></div><div class="metric"><div class="metric-label">Lean Mass</div><div class="metric-value">159.5 lb</div></div><div class="metric"><div class="metric-label">Weight</div><div class="metric-value">179.4 lb</div></div><div class="metric"><div class="metric-label">RMR</div><div class="metric-value">2,240 kcal/day</div></div></div>`;
const delta=`<section class="section card"><div class="section-title" style="margin-bottom:10px">Since Prior Scan</div><div class="delta"><div class="metric"><div class="metric-label">Body Fat</div><div class="metric-value">+0.4 pts</div></div><div class="metric"><div class="metric-label">Fat Mass</div><div class="metric-value">+1.0 lb</div></div><div class="metric"><div class="metric-label">Lean Mass</div><div class="metric-value">+1.5 lb</div></div></div></section>`;
const latestDexa=`<section class="section card"><div class="section-head"><span class="section-title">Latest Scan</span><span class="action">View BodySpec PDF</span></div><div class="row"><div><div class="row-label">Aug 30, 2026</div><div class="row-copy">BodySpec</div></div><span class="tag">Latest</span></div></section><section class="section card"><div class="health"><span class="health-mark">✓</span><div><div class="row-label">DEXA → Apple Health</div><div class="row-copy">Current</div></div></div></section>`;
const collapsed=(title,sub,rows,action='Show All')=>`<section class="section card"><div class="disclosure-row"><div><div class="section-title">${title}</div>${sub?`<div class="row-copy">${sub}</div>`:''}</div><span class="action">${action}</span></div><div class="disclosure-list" style="margin-top:10px">${rows.map(([a,b])=>`<div class="metric-row"><span>${a}</span><b>${b}</b></div>`).join('')}</div></section>`;
const rootOrder=`${dexaHeader}${scope('All DEXA')}${latestDexa}${summary}${delta}<section class="section card"><div class="section-title">Core Trends</div><div class="row-copy">Body Fat %, Fat Mass, Lean Mass, Total Mass, RMR</div>${chart('Body Fat %','9.4','%','green')}</section>${collapsed('Supplemental Metrics','Secondary calibration metrics from BodySpec.',[['VAT Mass','1.1 lb'],['VAT Volume','19.8 in³'],['Android Fat %','11.6%']])}${collapsed('Regional Tissue Lean Mass','Regional lean tissue in pounds.',[['Arms','18.6lb'],['Legs','55.1lb'],['Trunk','73.7lb']])}${collapsed('Regional Tissue Fat Mass','Regional fat tissue in pounds.',[['Arms','1.9lb'],['Legs','5.4lb'],['Trunk','8.1lb']])}${collapsed('Scan History','',[['Aug 30, 2026','9.4%'],['Aug 16, 2026','9.0%'],['Jul 18, 2026','8.2%']])}`;
screens.push(article('D1','dexa','DEXA root — exact section order','All ten production sections appear in source order with each disclosure independently collapsed.',rootOrder,{tall:2370}));

const core=`<div class="eyebrow">DEXA</div><div class="title" style="font-size:25px;margin:5px 0 16px">Core Trends</div>${chart('Body Fat %','9.4','%','green')}${chart('Fat Mass','16.9','lb','amber')}${chart('Lean Mass','159.5','lb','green')}${chart('Total Mass','179.4','lb','green')}${chart('RMR','2240.0','kcal/day','green')}`;
screens.push(article('D2','dexa','Core Trends — all five graphs','Every production graph survives in exact order with its title, selected value and unit.',core,{back:'‹ DEXA',title:'Core Trends',tall:1290}));

const supplementalRows=[['VAT Mass','1.1 lb'],['VAT Volume','19.8 in³'],['Android Fat %','11.6%'],['Gynoid Fat %','8.1%'],['A/G Ratio','1.43'],['Bone Mineral Content','7.0 lb'],['Total BMD','1.209 g/cm²'],['T-Score','0.1'],['Z-Score','0.6']];
screens.push(article('D3','dexa','Supplemental Metrics — collapsed','Collapsed production preview contains exactly the first three metric rows.',collapsed('Supplemental Metrics','Secondary calibration metrics from BodySpec.',supplementalRows.slice(0,3)),{back:'‹ DEXA',title:'DEXA'}));
const supplementalExpanded=`${collapsed('Supplemental Metrics','Secondary calibration metrics from BodySpec.',supplementalRows,'Close')}${chart('VAT Mass','1.1','lb','amber')}${chart('A/G Ratio','1.43','','amber')}`;
screens.push(article('D4','dexa','Supplemental Metrics — expanded','All nine metrics and both production graphs remain visible with exact units.',supplementalExpanded,{back:'‹ DEXA',title:'DEXA',tall:1530}));

const leanRows=[['Arms','18.6lb'],['Legs','55.1lb'],['Trunk','73.7lb'],['Android','10.6lb'],['Gynoid','18.3lb']];
const fatRows=[['Arms','1.9lb'],['Legs','5.4lb'],['Trunk','8.1lb'],['Android','1.1lb'],['Gynoid','2.0lb']];
screens.push(article('D5','dexa','Regional Lean — collapsed','The three-row preview preserves Arms, Legs and Trunk in pounds.',collapsed('Regional Tissue Lean Mass','Regional lean tissue in pounds.',leanRows.slice(0,3)),{back:'‹ DEXA',title:'DEXA'}));
const regionExpanded=(title,sub,rows,tone)=>`${collapsed(title,sub,rows,'Close')}${rows.map(([n,v])=>chart(n,v.replace('lb',''),'lb',tone)).join('')}`;
screens.push(article('D6','dexa','Regional Lean — expanded','All five regions remain, followed by all five interactive lean-mass graphs.',regionExpanded('Regional Tissue Lean Mass','Regional lean tissue in pounds.',leanRows,'green'),{back:'‹ DEXA',title:'DEXA',tall:1890}));
screens.push(article('D7','dexa','Regional Fat — collapsed','The three-row preview preserves Arms, Legs and Trunk in pounds.',collapsed('Regional Tissue Fat Mass','Regional fat tissue in pounds.',fatRows.slice(0,3)),{back:'‹ DEXA',title:'DEXA'}));
screens.push(article('D8','dexa','Regional Fat — expanded','All five regions remain, followed by all five interactive fat-mass graphs.',regionExpanded('Regional Tissue Fat Mass','Regional fat tissue in pounds.',fatRows,'amber'),{back:'‹ DEXA',title:'DEXA',tall:1890}));

const scans=[['Aug 30, 2026','9.4%','16.9 lb fat · 159.5 lb lean · 2,240 kcal/day RMR',true],['Aug 16, 2026','9.0%','15.9 lb fat · 158.0 lb lean · 2,220 kcal/day RMR',true],['Jul 18, 2026','8.2%','14.1 lb fat · 155.0 lb lean · 2,185 kcal/day RMR',false],['Jun 20, 2026','11.5%','20.5 lb fat · 154.6 lb lean · 2,160 kcal/day RMR',false],['May 24, 2026','14.8%','27.4 lb fat · 154.8 lb lean · 2,140 kcal/day RMR',false]];
const scanCards=(rows)=>rows.map(([date,bf,metrics,pdf])=>`<div class="scan"><div class="scan-top"><div><div class="row-label">${date}</div><div class="row-copy">BodySpec</div></div><b style="color:var(--green);font-size:13px">${bf}</b></div><div class="scan-metrics">${metrics}</div>${pdf?'<div class="action" style="margin-top:8px">View BodySpec PDF</div>':''}</div>`).join('');
const history=(expanded)=>`<section class="section card"><div class="disclosure-row"><span class="section-title">Scan History</span><span class="action">${expanded?'Close':'Show All'}</span></div><div style="margin-top:11px">${scanCards(expanded?scans:scans.slice(0,3))}</div></section>`;
screens.push(article('D9','dexa','Scan History — collapsed','Exactly three newest-first rows appear in the preview; current PDF actions remain attached.',history(false),{back:'‹ DEXA',title:'DEXA',tall:1040}));
screens.push(article('D10','dexa','Scan History — expanded','Show All expands all rows inline; Close reverses it and no scan-detail route is introduced.',history(true),{back:'‹ DEXA',title:'DEXA',tall:1370}));

el.innerHTML=screens.join('');
