import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe,expect,it } from "vitest";
import { createDexaAppointmentManagementService,DEXA_APPOINTMENT_ID,formatDexaAppointmentSummary,validateDexaAppointmentDraft } from "./DexaAppointmentManagementService";
describe("next DEXA appointment",()=>{
  it("creates and updates a separate future appointment without touching completed evidence",async()=>{const f=setup();const evidenceBefore=JSON.stringify(f.live.dexaScans);const created=await f.service.save(command());const updated=await f.service.save(command({expectedRevision:1,draft:draft({localTime:"08:00"})}));expect(created).toMatchObject({outcome:"success",created:true});expect(updated).toMatchObject({outcome:"success",created:false,executionId:DEXA_APPOINTMENT_ID});expect(f.live.executionItems.find((i)=>i.id==="execution_dexa")).toEqual(f.completed);expect(JSON.stringify(f.live.dexaScans)).toBe(evidenceBefore);});
  it("supports multiple optional reminders and natural summaries",async()=>{const f=setup();await f.service.save(command());const item=f.live.executionItems.find((i)=>i.id===DEXA_APPOINTMENT_ID);expect(item).toMatchObject({reminderPreferences:["week_before","day_before","morning_of"],uploadReminder:true});expect(formatDexaAppointmentSummary(item)).toBe("August 15 · 7:30 AM");});
  it("rejects today and past dates",()=>{expect(validateDexaAppointmentDraft(draft({plannedDate:"2026-07-25"}),{today:"2026-07-25"})).toEqual(["Choose a future date for your next DEXA."]);expect(validateDexaAppointmentDraft(draft({plannedDate:"2026-07-24"}),{today:"2026-07-25"})).toHaveLength(1);});
  it("clears only the future appointment",async()=>{const f=setup();await f.service.save(command());const cleared=await f.service.save(command({expectedRevision:1,draft:draft({plannedDate:"",localTime:"",reminderPreferences:[],uploadReminder:false})}));expect(cleared).toMatchObject({outcome:"success",cleared:true});expect(f.live.executionItems).toEqual([f.completed]);expect(f.live.dexaScans).toHaveLength(1);});
  it("rejects unchanged and stale saves and rolls back failures",async()=>{const f=setup();await f.service.save(command());const before=fs.readFileSync(f.file,"utf8");expect((await f.service.save(command({expectedRevision:1}))).outcome).toBe("unchanged");expect((await f.service.save(command({expectedRevision:0,draft:draft({localTime:"08:00"})}))).outcome).toBe("version_conflict");expect(fs.readFileSync(f.file,"utf8")).toBe(before);const broken=setup({afterWrite(){throw new Error("fail");}});const original=fs.readFileSync(broken.file,"utf8");expect((await broken.service.save(command())).outcome).toBe("persistence_failure");expect(fs.readFileSync(broken.file,"utf8")).toBe(original);});
});
function setup(faults={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"dexa-appointment-"));const file=path.join(dir,"runtime.json");const completed={id:"execution_dexa",userId:"founder",type:"evidence",completedAt:"2026-07-18",preferredSchedule:{date:"2026-07-18"}};const live={version:"test",revision:0,executionItems:[completed],dexaScans:[{id:"scan",date:"2026-07-18"}]};fs.writeFileSync(file,JSON.stringify(live));return{file,live,completed,service:createDexaAppointmentManagementService({runtimeStorePath:file,liveStore:live,faults,now:()=>new Date("2026-07-25T12:00:00Z")})};}
function command(overrides={}){return{userId:"founder",goalId:"goal",timezone:"America/Los_Angeles",expectedRevision:null,draft:draft(),author:{type:"user",id:"founder"},...overrides};}
function draft(overrides={}){return{plannedDate:"2026-08-15",localTime:"07:30",reminderPreferences:["week_before","day_before","morning_of"],uploadReminder:true,preparationNote:"Morning scan",...overrides};}
