import fs from "node:fs";
import path from "node:path";
import { describe,expect,it } from "vitest";
import { buildGoalEditDraft } from "./GoalEditDraftService";
import { acceptInterpretedPhase,beginPhaseIntent,confirmInterpretedPhaseStartDate,extendGoalEditDraftWithPhases,interpretPhaseIntentDraft,revisePhaseIntentDraft,setPhaseIntentText,setPhaseRevisionText,updateAuthoredPhase } from "./GoalEditPhaseDraftService";
import { assessPhaseTimelineIntegrity,expectedPhaseReviewDate,phaseTimingSnapshot,PHASE_DATE_ARITHMETIC_CONVENTION } from "./GoalPhaseTimelineIntegrityService";

const goal={id:"goal",userId:"user",status:"active",primary:true,title:"Build Lean Mass",updatedAt:"2026-07-21T00:00:00Z"};
const fresh=()=>extendGoalEditDraftWithPhases(buildGoalEditDraft(goal),{goal,capability:{available:true,blockingReasons:[]},now:new Date("2026-07-21")});
function interpret(text){let d=beginPhaseIntent(fresh());d=setPhaseIntentText(d,text);return interpretPhaseIntentDraft(d,{now:new Date("2026-07-21T18:00:00Z")})}

describe("Goal Phase timeline capture",()=>{
 it("preserves duration without downgrading missing-start timing",()=>{const d=interpret("For four weeks establish maintenance calories.");expect(d.phaseEditing.intentPlanning.result.proposedPhase).toMatchObject({timingMode:"fixed_duration",duration:{value:4,unit:"weeks"},startDate:null});expect(d.phaseEditing.intentPlanning.result.proposedPhases[0].unresolvedValues).toContain("startDate");expect(()=>acceptInterpretedPhase(d)).toThrow(/Choose when this 4-week phase should begin/)});
 it("confirms Today through a trusted date and preserves timing on acceptance",()=>{let d=interpret("For four weeks establish maintenance calories.");d=confirmInterpretedPhaseStartDate(d,"today",{today:new Date("2026-07-21T23:00:00Z")});d=acceptInterpretedPhase(d,{createId:()=>"opaque"});expect(phaseTimingSnapshot(d.phaseEditing.workingAuthoredPhases[0])).toEqual({timingMode:"fixed_duration",startDate:"2026-07-21",targetDate:null,duration:{value:4,unit:"weeks"}});expect(d.phaseEditing.allocatedPhaseIds).toEqual(["opaque"])});
 it("uses start plus calendar duration and reaches August 18",()=>{expect(expectedPhaseReviewDate({timingMode:"fixed_duration",startDate:"2026-07-21",duration:{value:4,unit:"weeks"}})).toBe("2026-08-18");expect(PHASE_DATE_ARITHMETIC_CONVENTION).toBe("start_plus_duration_calendar_days")});
 it("supports timing revisions without losing unrelated fields",()=>{let d=interpret("Starting July 21, spend four weeks establishing maintenance calories and training performance.");const purpose=d.phaseEditing.intentPlanning.result.proposedPhase.purpose;d=setPhaseRevisionText(d,"Make it six weeks.");d=revisePhaseIntentDraft(d);expect(d.phaseEditing.intentPlanning.result.proposedPhase).toMatchObject({startDate:"2026-07-21",duration:{value:6,unit:"weeks"},purpose});d=setPhaseRevisionText(d,"Start it July 20.");d=revisePhaseIntentDraft(d,{now:new Date("2026-07-21")});expect(d.phaseEditing.intentPlanning.result.proposedPhase).toMatchObject({startDate:"2026-07-20",duration:{value:6,unit:"weeks"}});d=setPhaseRevisionText(d,"End it August 18.");d=revisePhaseIntentDraft(d,{now:new Date("2026-07-21")});expect(d.phaseEditing.intentPlanning.result.proposedPhase).toMatchObject({timingMode:"target_date",targetDate:"2026-08-18",duration:null});d=setPhaseRevisionText(d,"Make this untimed and review it based on evidence.");d=revisePhaseIntentDraft(d);expect(d.phaseEditing.intentPlanning.result.proposedPhase).toMatchObject({timingMode:"completion_criteria",duration:null,targetDate:null})});
 it("blocks supplied-to-authored timing loss",()=>{let d=interpret("Starting July 21, spend four weeks establishing maintenance calories.");d=acceptInterpretedPhase(d,{createId:()=>"opaque"});const corrupted=structuredClone(d);Object.assign(corrupted.phaseEditing.workingAuthoredPhases[0],{timingMode:"completion_criteria",duration:null,startDate:null});const result=assessPhaseTimelineIntegrity(corrupted);expect(result.valid).toBe(false);expect(result.errors.map(x=>x.code)).toEqual(expect.arrayContaining(["PHASE_TIMING_FINGERPRINT_MISMATCH","PHASE_SUPPLIED_DURATION_LOST"]))});
 it("repairs malformed Phase 1 without altering Phase 2 or lifecycle",()=>{const phases=[{id:"p1",goalId:"goal",name:"Establish Maintenance",purpose:"Baseline",status:"active",order:0,startDate:null,targetDate:null,duration:null,timingMode:"completion_criteria",successCriteria:[],guardrails:[],transitionPolicy:"evidence_review"},{id:"p2",goalId:"goal",name:"Lean Mass Build",purpose:"Build",status:"upcoming",order:1,startDate:null,targetDate:"2026-10-31",duration:null,timingMode:"target_date",successCriteria:[],guardrails:[],transitionPolicy:"manual_review"}],live={...goal,phases};let d=extendGoalEditDraftWithPhases(buildGoalEditDraft(live),{goal:live,capability:{available:true,blockingReasons:[]},now:new Date("2026-07-21")});const phaseTwo=structuredClone(d.phaseEditing.workingAuthoredPhases[1]);d=updateAuthoredPhase(d,"p1",{timingMode:"fixed_duration",startDate:"2026-07-21",targetDate:null,duration:{value:4,unit:"weeks"}});expect(assessPhaseTimelineIntegrity(d).valid).toBe(true);expect(d.phaseEditing.workingAuthoredPhases[1]).toEqual(phaseTwo);expect(d.phaseEditing.workingAuthoredPhases.map(x=>x.status)).toEqual(["active","upcoming"]);expect(d.phaseEditing.diff.timingChanged.map(x=>x.phaseId)).toEqual(["p1"])});
 it("shows complete Final Review timing and gates token issuance",()=>{const screen=fs.readFileSync(path.resolve(process.cwd(),"src/screens/GoalEditWizardScreen.jsx"),"utf8"),actions=fs.readFileSync(path.resolve(process.cwd(),"src/app/goals/[goalId]/edit/actions.js"),"utf8");for(const copy of ["Planned duration:","Planned review:","Target date:","Timing may be adjusted based on progress."])expect(screen).toContain(copy);expect(screen).not.toContain("Timing: Completion readiness");expect(actions).toContain("assessPhaseTimelineIntegrity");expect(actions.indexOf("assessPhaseTimelineIntegrity")).toBeLessThan(actions.lastIndexOf("createFinalReview"))});
});
