import { GoalPhaseTimingMode, GoalPhaseTransitionPolicy } from "../models/goalPhase";

export const GOAL_PHASE_INTENT_INTERPRETATION_VERSION = "goal_phase_intent_v1";
const PROPOSAL_STATES=new Set(["pending_review","accepted","revised","skipped","replaced"]);

export function interpretGoalPhaseIntent(input = {}) {
  assertInput(input);
  const intent=normalize(input.userIntent);
  if(!intent)return result("rejected",{clarificationQuestions:["Describe what you want this phase to accomplish."],warnings:["Phase intent is required."]});
  const split=segmentJourney(intent);
  const proposals=split.segments.map((segment,index)=>buildProposal(segment,{...input,phasePosition:(input.phasePosition??0)+index,proposalIndex:index,proposalCount:split.segments.length}));
  const duplicate=findDuplicate(proposals,input.existingAuthoredPhases??[])??findPendingDuplicate(proposals);
  if(duplicate)return result("clarification_required",{normalizedIntent:intent,clarificationRequired:true,clarificationQuestions:[`This sounds very similar to ${duplicate.existing.name}. Are you trying to revise that phase or add a different one?`],proposedPhases:[],remainingUnconsumedIntent:intent,sequencingRelationships:split.relationships});
  const dateOwnershipQuestion=split.segments.length>1&&/\bby (?:January|February|March|April|May|June|July|August|September|October|November|December)\b/i.test(intent)&&!proposals.some(x=>x.phase.targetDate)?["What exact date do you have in mind, and which phase should reach it?"]:[];
  const questions=[...proposals.flatMap(item=>item.clarificationQuestions),...dateOwnershipQuestion];
  if(questions.length)return result("clarification_required",{normalizedIntent:intent,clarificationRequired:true,clarificationQuestions:[...new Set(questions)],proposedPhases:proposals,remainingUnconsumedIntent:intent,sequencingRelationships:split.relationships});
  return result("interpreted",{normalizedIntent:intent,proposedPhases:proposals,currentProposalIndex:0,remainingUnconsumedIntent:remainingIntent(proposals,0),sequencingRelationships:split.relationships,suppliedValuesByPhase:proposals.map(x=>x.suppliedValues),inferredValuesByPhase:proposals.map(x=>x.inferredValues),unresolvedValuesByPhase:proposals.map(x=>x.unresolvedValues),confidence:proposals.every(x=>x.quality==="high")?"high":"medium",ownershipNotes:ownershipNotes(intent,input.knownGoalLevelGuardrails),rationale:"The journey is separated into distinct stages while the overall destination remains shared."});
}

export function reviseGoalPhaseIntent(input = {}) {
  const current=normalizeResult(input.currentResult);const instruction=normalize(input.revisionInstruction);
  if(!current.proposedPhases.length||!instruction)return result("rejected",{clarificationQuestions:["Describe the change you want to make."],warnings:["A current plan and revision instruction are required."]});
  const index=revisionIndex(instruction,current.currentProposalIndex,current.proposedPhases.length);const proposals=structuredClone(current.proposedPhases);const envelope=proposals[index];let phase={...envelope.phase};const changed=[];
  const duration=parseDuration(instruction);if(duration){phase={...phase,timingMode:"fixed_duration",duration,targetDate:null};changed.push("duration")}
  const startDate=parseStart(instruction,input.currentDate);if(startDate){phase={...phase,startDate};changed.push("start date")}
  const targetDate=parseTargetDate(instruction,input.currentDate);if(targetDate){phase={...phase,timingMode:"target_date",targetDate,duration:null};changed.push("target date")}
  if(/(?:make|keep) (?:this|it) untimed|open-ended|based on evidence/i.test(instruction)){phase={...phase,timingMode:"completion_criteria",duration:null,targetDate:null};changed.push("evidence-led timing")}
  const name=instruction.match(/(?:call (?:this|it)|name (?:this|it)) +["“]?(.+?)["”]?(?=\s+and\s+focus|[.!]|$)/i)?.[1]?.trim();if(name){phase={...phase,name};changed.push("phase name")}
  if(/focus more on ([^.!]+)/i.test(instruction)){const focus=instruction.match(/focus more on ([^.!]+)/i)[1];phase={...phase,purpose:`${phase.purpose.replace(/[.]$/,'')} with added focus on ${focus}.`};changed.push("purpose")}
  if(!changed.length)return result("clarification_required",{...current,clarificationRequired:true,clarificationQuestions:["I couldn’t identify the change. Tell me the new duration, date, name, or focus for this phase."]});
  proposals[index]={...envelope,state:"revised",phase:strictProposal(phase)};
  return result("interpreted",{...current,proposedPhases:proposals,currentProposalIndex:index,changedFields:changed,rationale:`Updated ${proposals[index].phase.name} and preserved the rest of the plan.`});
}

export function normalizeGoalPhaseInterpretationResult(value){return deepFreeze(normalizeResult(value))}
export const GoalPhaseIntentInterpretationService=Object.freeze({interpret:interpretGoalPhaseIntent,revise:reviseGoalPhaseIntent,normalizeResult:normalizeGoalPhaseInterpretationResult});

function buildProposal(text,context){
  const duration=parseDuration(text),startDate=parseStart(text,context.currentDate),targetDate=parseTargetDate(text,context.currentDate);const ambiguous=/for (?:a |some )?while/i.test(text)&&!duration;const evidence=evidencePlan(text);const completion=criteria(text);const phase=strictProposal({name:phaseName(text),purpose:phasePurpose(text,context),timingMode:duration?GoalPhaseTimingMode.FIXED_DURATION:targetDate?GoalPhaseTimingMode.TARGET_DATE:GoalPhaseTimingMode.COMPLETION_CRITERIA,duration,startDate,targetDate,successCriteria:completion.map(({evaluationMode,...item})=>item),guardrails:phaseSpecificGuardrails(text),transitionPolicy:/evidence|performance|training|before moving|ready|once/i.test(text)?GoalPhaseTransitionPolicy.EVIDENCE_REVIEW:GoalPhaseTransitionPolicy.MANUAL_REVIEW,order:context.phasePosition});
  return strictEnvelope({proposalKey:`proposal_${context.proposalIndex+1}_${fingerprint(text)}`,state:"pending_review",phase,sourceIntent:text,sequencingRole:context.proposalIndex===0?"first":context.proposalIndex===context.proposalCount-1?"final":"middle",evidenceMonitoringPlan:evidence,completionCriteria:completion,suppliedValues:compact({duration,startDate:explicitDateMention(text)?startDate:null,targetDate,evidenceAreas:evidence.map(x=>x.area)}),inferredValues:compact({name:{value:phase.name,source:"phase_specific_interpretation"},purpose:{value:phase.purpose,source:"phase_specific_interpretation"},startDate:/starting (?:now|today)/i.test(text)&&startDate?{value:startDate,source:"deterministic_calculation"}:null}),unresolvedValues:omitted(duration,startDate,targetDate),timingProvenance:{supplied:compact({duration,startDate:explicitDateMention(text)?startDate:null,targetDate}),interpreted:timingOf(phase),confirmed:null,deliberateUntimed:phase.timingMode==="completion_criteria"&&!duration&&!targetDate&&!ambiguous},clarificationQuestions:ambiguous?["How long should this phase last, or what progress would tell us it is complete?"]:[],quality:duration||targetDate?"high":"medium"});
}
function strictEnvelope(value){if(!value.proposalKey||!PROPOSAL_STATES.has(value.state)||!value.phase)throw new TypeError("Invalid phase proposal envelope.");return deepFreeze({proposalKey:value.proposalKey,state:value.state,phase:strictProposal(value.phase),sourceIntent:normalize(value.sourceIntent),sequencingRole:value.sequencingRole,evidenceMonitoringPlan:structuredClone(value.evidenceMonitoringPlan??[]),completionCriteria:structuredClone(value.completionCriteria??[]),suppliedValues:structuredClone(value.suppliedValues??{}),inferredValues:structuredClone(value.inferredValues??{}),unresolvedValues:[...(value.unresolvedValues??[])],timingProvenance:structuredClone(value.timingProvenance??{supplied:{},interpreted:timingOf(value.phase),confirmed:null,deliberateUntimed:false}),clarificationQuestions:[...(value.clarificationQuestions??[])],quality:value.quality??"medium"})}
function strictProposal(value){const allowed=["name","purpose","timingMode","duration","startDate","targetDate","successCriteria","guardrails","transitionPolicy","order"];for(const key of Object.keys(value))if(!allowed.includes(key))throw new TypeError(`Unsupported proposed phase field: ${key}`);if(!value.name||!value.purpose||!Number.isInteger(value.order))throw new TypeError("Phase proposal name, purpose, and order are required.");return deepFreeze({name:value.name,purpose:value.purpose,timingMode:value.timingMode,duration:value.duration??null,startDate:value.startDate??null,targetDate:value.targetDate??null,successCriteria:structuredClone(value.successCriteria??[]),guardrails:structuredClone(value.guardrails??[]),transitionPolicy:value.transitionPolicy,order:value.order})}
function result(status,value={}){const proposedPhases=validateProposals(value.proposedPhases??(value.proposedPhase?[strictEnvelope({proposalKey:"proposal_1_legacy",state:"pending_review",phase:value.proposedPhase,sourceIntent:value.normalizedIntent,sequencingRole:"first",evidenceMonitoringPlan:value.evidenceMonitoringPlan,completionCriteria:value.completionCriteria,suppliedValues:value.suppliedValues,inferredValues:value.inferredValues,unresolvedValues:value.omittedValues})]:[]));const index=proposedPhases.length?Math.min(Math.max(value.currentProposalIndex??0,0),proposedPhases.length-1):0;const current=proposedPhases[index]??null;return deepFreeze({status,normalizedIntent:value.normalizedIntent??"",proposedPhases,currentProposalIndex:index,remainingUnconsumedIntent:value.remainingUnconsumedIntent??remainingIntent(proposedPhases,index),sequencingRelationships:value.sequencingRelationships??[],suppliedValuesByPhase:value.suppliedValuesByPhase??proposedPhases.map(x=>x.suppliedValues),inferredValuesByPhase:value.inferredValuesByPhase??proposedPhases.map(x=>x.inferredValues),unresolvedValuesByPhase:value.unresolvedValuesByPhase??proposedPhases.map(x=>x.unresolvedValues),confidence:value.confidence??"low",clarificationRequired:value.clarificationRequired===true,clarificationQuestions:value.clarificationQuestions??[],warnings:value.warnings??[],interpretationVersion:GOAL_PHASE_INTENT_INTERPRETATION_VERSION,proposedPhase:status==="interpreted"?current?.phase??null:null,evidenceMonitoringPlan:current?.evidenceMonitoringPlan??value.evidenceMonitoringPlan??[],completionCriteria:current?.completionCriteria??value.completionCriteria??[],ownershipNotes:value.ownershipNotes??[],inferredValues:current?.inferredValues??value.inferredValues??{},suppliedValues:current?.suppliedValues??value.suppliedValues??{},omittedValues:current?.unresolvedValues??value.omittedValues??[],rationale:value.rationale??null,changedFields:value.changedFields??[]})}
function normalizeResult(value={}){return result(value.status??"interpreted",value)}
function validateProposals(items){if(!Array.isArray(items))throw new TypeError("Phase proposals must be an array.");const keys=new Set();const output=items.map((item,index)=>{const normalized=strictEnvelope(item.phase?item:{proposalKey:`proposal_${index+1}_legacy`,state:"pending_review",phase:item,sequencingRole:index?"final":"first"});if(keys.has(normalized.proposalKey))throw new TypeError("Phase proposal keys must be unique.");keys.add(normalized.proposalKey);if(normalized.phase.order!==items[0]?.phase?.order+index&&items[0]?.phase)throw new TypeError("Phase proposal order must be contiguous.");return normalized});return output}
function segmentJourney(intent){let marked=intent.replace(/\.\s*(?=(?:once|then|next|after that|phase (?:two|three|2|3))\b)/gi," || ").replace(/[,;]\s*(?:then|next)\s+/gi," || ").replace(/\s+followed by\s+/gi," || ").replace(/\s+and later\s+/gi," || ").replace(/\s+before moving into\s+/gi," || ").replace(/\s+before\s+(?=(?:a |an |the )?(?:fat[- ]?loss|lean[- ]?mass|build|taper|peak|base|mileage))/gi," || ");let segments=marked.split(/\s*\|\|\s*/).map(cleanSegment).filter(Boolean);segments=segments.flatMap(x=>/peak training and taper/i.test(x)?x.split(/\s+and\s+(?=taper\b)/i):[x]).map(cleanSegment);if(segments.length<2||!segments.every(materialStage))segments=[intent];return {segments,relationships:segments.slice(1).map((_,i)=>({fromIndex:i,toIndex:i+1,type:"precedes"}))}}
function cleanSegment(value){return normalize(value.replace(/^(?:once [^,]+,?\s*|after [^,]+,?\s*|phase (?:one|two|three|1|2|3)[:,-]?\s*)/i,""))}
function materialStage(text){return /maintenan|calibrat|baseline|lean[ -]?mass|muscle|run|mileage|base train|peak|taper|fat[ -]?loss|recover|capacity|performance|strength/i.test(text)}
function findDuplicate(proposals,accepted){for(const proposal of proposals){for(const existing of accepted){if(normalize(proposal.phase.name).toLowerCase()===normalize(existing.name).toLowerCase()||similarity(signature(proposal.phase),signature(existing))>=0.75)return {proposal,existing}}}return null}
function findPendingDuplicate(proposals){for(let index=1;index<proposals.length;index+=1){const duplicate=findDuplicate([proposals[index]],proposals.slice(0,index).map(x=>x.phase));if(duplicate)return duplicate}return null}
function signature(phase){return new Set(normalize(`${phase.name} ${phase.purpose}`).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>3&&!new Set(["phase","build","while","before","progress","establish"]).has(x)))}
function similarity(a,b){const common=[...a].filter(x=>b.has(x)).length;return common/Math.max(1,Math.min(a.size,b.size))}
function remainingIntent(proposals,index){return proposals.filter((x,i)=>i>=index&&!["accepted","skipped","replaced"].includes(x.state)).map(x=>x.sourceIntent).join(" Then ")}
function revisionIndex(text,current,count){const match=text.match(/(?:phase\s*)?(\d+|one|two|three|first|second|third)/i)?.[1]?.toLowerCase();const map={"1":0,one:0,first:0,"2":1,two:1,second:1,"3":2,three:2,third:2};return Math.min(map[match]??current??0,count-1)}
function evidencePlan(text){const map=[[/calorie|nutrition|energy balance|intake|lean[ -]?mass|muscle/i,"nutrition_intake","Nutrition intake","To understand whether intake is supporting the work without pulling you away from the overall goal."],[/activity|expenditure|calories? (?:in and )?out|steps/i,"activity","Activity and energy expenditure","To see whether day-to-day movement is keeping the plan sustainable."],[/weight|maintenance|lean[ -]?mass|muscle|fat[ -]?loss/i,"body_weight","Body-weight trend","To distinguish meaningful progress from normal day-to-day changes."],[/lean[ -]?mass|muscle|body fat|body composition|dexa|photo/i,"body_composition","Body-composition evidence when available","To check that the changes are moving body composition in the intended direction."],[/training|performance|strength|lean[ -]?mass|muscle/i,"training_performance","Training performance","To see whether training is adapting and progression remains productive."],[/recover|sleep|fatigue/i,"recovery","Recovery","To make sure fatigue is manageable and the pace remains sustainable."]];return map.filter(([pattern])=>pattern.test(text)).map(([,area,label,purpose])=>({area,label,purpose,requiredForCompletion:false}))}
function criteria(text){const values=[];if(/maintenance|energy balance/i.test(text))values.push("A usable maintenance range has been established");if(/lean[ -]?mass|muscle/i.test(text))values.push("Measurable progress toward the lean-mass target");if(/performance|training|lean[ -]?mass|muscle/i.test(text))values.push("Training performance supports continued progression");if(/body fat|body composition|dexa/i.test(text))values.push("Body-composition evidence remains compatible with the overall guardrail");if(/before moving|ready|once|maintenance/i.test(text))values.push("Enough evidence exists to review the transition");return values.map((label,index)=>({key:`intent_criterion_${index+1}`,label,evaluationMode:"evidence_tracked"}))}
function phaseName(text){if(/maintenance|energy balance/i.test(text))return "Establish Maintenance";if(/lean[ -]?mass|muscle|hypertrophy/i.test(text))return "Lean Mass Build";if(/mileage/i.test(text))return "Mileage Build";if(/running habit|run consistently|consistent running/i.test(text))return "Build Running Habit";if(/running|run capacity/i.test(text))return "Build Running Capacity";if(/base train|aerobic base/i.test(text))return "Base Training";if(/peak/i.test(text))return "Peak Training";if(/taper/i.test(text))return "Taper";if(/fat[ -]?loss/i.test(text))return "Fat-Loss Block";if(/calibrat|baseline/i.test(text))return "Establish the Baseline";if(/recover/i.test(text))return "Recovery";if(/performance|training|strength/i.test(text))return "Build Performance";return "Working title"}
function phasePurpose(text,context){if(/maintenance|energy balance/i.test(text))return /lean[ -]?mass|muscle/i.test(context.userIntent)?"Establish a sustainable maintenance baseline before beginning the dedicated lean-mass build.":"Establish a sustainable maintenance baseline before increasing the demands of the next phase.";if(/lean[ -]?mass|muscle|hypertrophy/i.test(text))return /body fat|body composition|8\s*[–-]\s*9/i.test(text)?"Build meaningful lean mass from the newly established maintenance baseline while protecting body composition.":"Build meaningful lean mass while keeping training and recovery sustainable.";if(/mileage/i.test(text))return "Increase running mileage from the established base while keeping the workload sustainable.";if(/peak/i.test(text))return "Turn the fitness already built into readiness for the target event.";if(/taper/i.test(text))return "Reduce fatigue while preserving readiness for the target event.";if(/fat[ -]?loss/i.test(text))return "Create a focused fat-loss block while protecting training performance and recovery.";if(/running|run/i.test(text))return "Build a dependable running foundation that can support more purposeful training later.";if(/recover/i.test(text))return "Restore readiness while protecting the progress already made.";return "Create a clear stage that moves the journey forward and gives us meaningful progress to review."}
function ownershipNotes(text,guardrails=[]){const refs=overallGuardrailReferences(text,guardrails);return ["Your destination and the things you want to protect still apply throughout every phase.",...refs.map(x=>`${x} will stay in view throughout the journey.`)]}
function overallGuardrailReferences(text,guardrails=[]){if(!/body fat|body composition|8\s*[–-]\s*9\s*%/i.test(text))return [];const matches=guardrails.filter(x=>/body fat|body composition|8\s*[–-]\s*9/i.test(x.label??x.text??"")).map(x=>x.label??x.text);return matches.length?matches:["Maintain approximately 8–9% body fat"]}
function phaseSpecificGuardrails(text){const match=text.match(/(?:during this phase|for this phase),?\s*(?:keep|protect|avoid)\s+([^.!]+)/i);return match?[{key:"intent_guardrail_1",label:match[1].trim()}]:[]}
function parseDuration(text){const match=text.match(/(?:(?:for|spend|make it|instead)\s+)?(?:(\d+)|(?:about\s+)?(four|six|eight|twelve|thirty))\s+(day|week|month)s?/i);if(!match)return null;const words={four:4,six:6,eight:8,twelve:12,thirty:30};return {value:Number(match[1]??words[match[2].toLowerCase()]),unit:`${match[3].toLowerCase()}s`}}
function parseStart(text,currentDate){if(/start(?:ing)?(?: it)? (?:now|today)/i.test(text))return dateKey(currentDate);const iso=text.match(/start(?:ing)?(?: it)? (?:on )?(\d{4}-\d{2}-\d{2})/i)?.[1];if(iso)return validDate(iso)?iso:null;const named=text.match(/start(?:ing)?(?: it)? (?:on )?([A-Z][a-z]+ \d{1,2}(?:,? \d{4})?)/i)?.[1];return named?namedDate(named,currentDate):null}
function parseTargetDate(text,currentDate){const iso=text.match(/(?:(?:by|on)|end(?: it)?|finish(?: it)?) (\d{4}-\d{2}-\d{2})/i)?.[1];if(iso)return validDate(iso)?iso:null;const named=text.match(/(?:(?:by|on)|end(?: it)?|finish(?: it)?) ([A-Z][a-z]+ \d{1,2}(?:,? \d{4})?)/i)?.[1];return named?namedDate(named,currentDate):null}
function explicitDateMention(text){return /start(?:ing)?|today|now|\d{4}-\d{2}-\d{2}/i.test(text)}
function assertInput(input){if(!input||typeof input!=="object"||!input.sourceGoalId||!input.canonicalGoalPlan||!Array.isArray(input.existingAuthoredPhases)||input.interpretationVersion!==GOAL_PHASE_INTENT_INTERPRETATION_VERSION)throw new TypeError("A strict Goal Phase intent interpretation input is required.")}
function omitted(duration,start,target){return [["duration",duration],["startDate",start],["targetDate",target]].filter(([,v])=>!v).map(([k])=>k)}function timingOf(phase){return {timingMode:phase.timingMode,startDate:phase.startDate??null,targetDate:phase.targetDate??null,duration:structuredClone(phase.duration??null)}}function compact(value){return Object.fromEntries(Object.entries(value).filter(([,v])=>v!=null))}function normalize(value){return typeof value==="string"?value.trim().replace(/\s+/g," "):""}function fingerprint(value){let hash=2166136261;for(const c of value){hash^=c.charCodeAt(0);hash=Math.imul(hash,16777619)}return (hash>>>0).toString(16)}function dateKey(value){const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString().slice(0,10)}function validDate(v){return dateKey(`${v}T00:00:00Z`)===v}function namedDate(v,current){const withYear=/\d{4}/.test(v)?v:`${v}, ${new Date(current).getUTCFullYear()}`;return dateKey(new Date(`${withYear} 12:00:00 UTC`))}function deepFreeze(value){if(!value||typeof value!=="object"||Object.isFrozen(value))return value;Object.values(value).forEach(deepFreeze);return Object.freeze(value)}
