import { describe, expect, it } from "vitest";
import { createGoalPlanningInput } from "../models/goalPlanningInput";
import { diffGoalPlans } from "./GoalPlanDiffService";
import {
  GoalEditDraftError, addGoalEditItem, assessGoalEditReview, buildGoalEditDraft,
  editGoalEditItem, getGoalEditStepSequence, moveGoalEditStep, removeGoalEditItem,
  normalizeGoalEditDraftNavigation, normalizeGoalEditSectionIdentifier, selectGoalEditSections, sourceRevision, updateGoalEditWorkingPlan,
} from "./GoalEditDraftService";

function goal(overrides={}) { return { id:"goal-active", userId:"user", title:"Build Lean Mass", type:"build_lean_mass", status:"active", primary:true, updatedAt:"2026-07-21T00:00:00Z", guardrails:[{id:"body-fat",text:"Protect body composition",accepted:true}], progressMeasurement:{outcomeMeasures:[{id:"lean-mass",label:"Gain lean mass",accepted:true}]}, ...overrides }; }

describe("Goal Edit draft lifecycle",()=>{
  it("builds a deterministic immutable draft without mutating the active goal",()=>{const source=goal();const before=structuredClone(source);const draft=buildGoalEditDraft(source,{now:new Date("2026-07-21T12:00:00Z")});expect(source).toEqual(before);expect(draft).toMatchObject({sourceGoalId:"goal-active",completionState:"editing",currentStep:"choose_sections",originalPlan:{schemaVersion:"goal_planning_v1"}});expect(draft.originalPlan).not.toBe(draft.workingPlan);expect(draft.originalPlan).toEqual(draft.workingPlan);expect(Object.isFrozen(draft.workingPlan)).toBe(true)});
  it("rejects unavailable or non-active goals",()=>{expect(()=>buildGoalEditDraft(goal({status:"completed"}))).toThrowError(expect.objectContaining({code:"GOAL_EDIT_SOURCE_UNAVAILABLE"}))});
  it("navigates only selected sections and preserves edits backward and forward",()=>{let draft=buildGoalEditDraft(goal());draft=selectGoalEditSections(draft,["goal","guardrails"]);expect(getGoalEditStepSequence(draft)).toEqual(["choose_sections","goal_and_purpose","guardrails","review"]);draft=updateGoalEditWorkingPlan(draft,{name:"New name"});draft=moveGoalEditStep(draft,"forward");draft=moveGoalEditStep(draft,"back");expect(draft.currentStep).toBe("goal_and_purpose");expect(draft.workingPlan.name).toBe("New name")});
  it("uses canonical phase-first ordering independent of checkbox order and legacy draft order",()=>{const capable={...buildGoalEditDraft(goal()),phaseEditing:{capability:{available:true}}};const first=selectGoalEditSections(capable,["target_timeline","phases","goal"]);const second=selectGoalEditSections(capable,["phases","goal_and_purpose","overall_goal"]);expect(first.selectedSections).toEqual(["goal_and_purpose","phases","overall_goal"]);expect(second.selectedSections).toEqual(first.selectedSections);expect(getGoalEditStepSequence({...first,selectedSections:["target_and_timeline","phases","goal"]})).toEqual(["choose_sections","goal_and_purpose","phases","overall_goal","review"])});
  it("supports independent phase-only and overall-goal-only navigation",()=>{const capable={...buildGoalEditDraft(goal()),phaseEditing:{capability:{available:true}}};expect(getGoalEditStepSequence(selectGoalEditSections(capable,["phases"]))).toEqual(["choose_sections","phases","review"]);expect(getGoalEditStepSequence(selectGoalEditSections(capable,["overall_goal"]))).toEqual(["choose_sections","overall_goal","review"])});
  it("normalizes legacy aliases without merging distinct sections",()=>{expect(normalizeGoalEditSectionIdentifier("target_and_timeline")).toBe("overall_goal");expect(normalizeGoalEditSectionIdentifier("goal")).toBe("goal_and_purpose");expect(()=>normalizeGoalEditSectionIdentifier("mystery")).toThrowError(expect.objectContaining({code:"GOAL_EDIT_SECTION_UNSUPPORTED"}));const normalized=normalizeGoalEditDraftNavigation({...buildGoalEditDraft(goal()),selectedSections:["target_timeline","overall_goal","goal"],currentStep:"target_and_timeline"});expect(normalized).toMatchObject({selectedSections:["goal_and_purpose","overall_goal"],currentStep:"overall_goal"})});
  it("keeps phases visibly unavailable",()=>{const draft=buildGoalEditDraft(goal());expect(()=>selectGoalEditSections(draft,["phases"])).toThrowError(expect.objectContaining({code:"GOAL_EDIT_PHASES_UNAVAILABLE"}))});
  it("supports target and timeline edits through canonical validation",()=>{let draft=buildGoalEditDraft(goal());draft=updateGoalEditWorkingPlan(draft,{target:{type:"numeric_change",metric:"lean_mass",direction:"increase",amount:10,unit:"lb",targetDate:"2026-10-31"},timeline:{mode:"target_date",targetDate:"2026-10-31",flexibility:"aspirational",ambition:"ambitious"}});expect(draft.workingPlan).toMatchObject({target:{amount:10},timeline:{ambition:"ambitious",flexibility:"aspirational"}});expect(()=>updateGoalEditWorkingPlan(draft,{timeline:{mode:"fixed_duration",duration:{value:0,unit:"weeks"}}})).toThrow(/Duration/)});
  it("adds, edits, and removes criteria and guardrails with globally unique durable keys",()=>{let draft=buildGoalEditDraft(goal({guardrails:[],progressMeasurement:{outcomeMeasures:[]}}));draft=addGoalEditItem(draft,"successCriteria",{label:"Criterion"});const criterionKey=draft.workingPlan.successCriteria[0].key;draft=addGoalEditItem(draft,"guardrails",{label:"Guardrail"});const guardrailKey=draft.workingPlan.guardrails[0].key;expect(criterionKey).not.toBe(guardrailKey);draft=editGoalEditItem(draft,"successCriteria",criterionKey,{label:"Changed"});draft=removeGoalEditItem(draft,"successCriteria",criterionKey);draft=addGoalEditItem(draft,"successCriteria",{label:"Later"});expect(draft.workingPlan.successCriteria[0].key).not.toBe(criterionKey);expect(draft.usedLocalKeys).toContain(criterionKey);expect(()=>addGoalEditItem(draft,"guardrails",{key:guardrailKey,label:"Duplicate"})).toThrowError(expect.objectContaining({code:"GOAL_EDIT_LOCAL_KEY_DUPLICATE"}))});
  it("generates missing keys deterministically without rewriting supplied keys",()=>{const source=goal({guardrails:[{text:"No key"},{id:"keep-me",text:"Keep"}],progressMeasurement:{outcomeMeasures:[{label:"No key"}]}});const draft=buildGoalEditDraft(source);expect(draft.workingPlan.guardrails.find(x=>x.label==="Keep").key).toBe("keep-me");expect(draft.workingPlan.successCriteria[0].key).toBe("criterion_1");expect(draft.workingPlan.guardrails[0].key).toBe("guardrail_1")});
  it("blocks duplicate supplied keys explicitly",()=>{expect(()=>buildGoalEditDraft(goal({guardrails:[{id:"same",text:"One"}],progressMeasurement:{outcomeMeasures:[{id:"same",label:"Two"}]}}))).toThrow(/unique/)});
  it("detects stale source revisions while preserving the draft",()=>{const source=goal();const draft=buildGoalEditDraft(source);expect(sourceRevision(source)).toBe(draft.sourceRevision);const stale=assessGoalEditReview(draft,{...source,updatedAt:"2026-07-22"});expect(stale).toMatchObject({completionState:"blocked_stale_source",finalReview:{stale:true,status:"blocked"}});expect(stale.workingPlan).toEqual(draft.workingPlan)});
  it("produces review readiness but intentionally blocks commit",()=>{const source=goal();const reviewed=assessGoalEditReview(buildGoalEditDraft(source),source);expect(reviewed).toMatchObject({completionState:"review_ready",finalReview:{status:"ready",stale:false}});expect(reviewed.finalReview.message).toMatch(/requires a revision-checked/)});
});

describe("Goal Plan Diff",()=>{
  const plan=()=>createGoalPlanningInput({name:"Goal",purpose:"Purpose",primaryOutcome:"Outcome",target:{type:"unspecified"},timeline:{mode:"unspecified"},successCriteria:[{key:"c1",label:"One"}],guardrails:[{key:"g1",label:"Guard"}],coachingPreferences:{tone:"direct"}});
  it("returns an empty immutable diff for equivalent normalized plans",()=>{const diff=diffGoalPlans(plan(),structuredClone(plan()));expect(diff).toMatchObject({empty:true,changedSections:[],evidenceAndHistoryPreserved:true});expect(Object.isFrozen(diff)).toBe(true)});
  it("returns deterministic before-and-after changes keyed by stable local key",()=>{const original=plan();const working=createGoalPlanningInput({...structuredClone(original),name:"New Goal",timeline:{mode:"open_ended"},successCriteria:[{key:"c1",label:"Changed"},{key:"c2",label:"Added"}],guardrails:[]});const first=diffGoalPlans(original,working);expect(diffGoalPlans(original,working)).toEqual(first);expect(first).toMatchObject({empty:false,destinationChanged:true,criteria:{added:[{key:"c2"}],modified:[{key:"c1"}]},guardrails:{removed:[{key:"g1"}]},evidenceAndHistoryPreserved:true});expect(first.scalarChanges[0]).toMatchObject({field:"name",before:"Goal",after:"New Goal"})});
});
