import { describe,expect,it } from "vitest";
import { buildGoalEditDraft } from "./GoalEditDraftService";
import { acceptInterpretedPhase,beginPhaseIntent,discardPendingPhaseProposals,extendGoalEditDraftWithPhases,interpretPhaseIntentDraft,isPhaseSectionResolved,selectActiveAuthoredPhase,selectInterpretedPhaseProposal,setPhaseIntentText,skipInterpretedPhaseProposal } from "./GoalEditPhaseDraftService";

const goal={id:"goal",userId:"user",status:"active",primary:true,title:"Build Lean Mass",updatedAt:"2026-07-21T00:00:00Z",guardrails:[{id:"g",text:"Maintain 8–9% body fat",accepted:true}]};
const fresh=()=>extendGoalEditDraftWithPhases(buildGoalEditDraft(goal),{goal,capability:{available:true,blockingReasons:[]},now:new Date("2026-07-21")});
const journey="Starting July 21, spend four weeks establishing maintenance energy balance for calories in and out and improving training performance. Once maintenance is established, build 10 pounds of lean mass by October 31 while maintaining 8–9% body fat.";
function interpreted(){let d=beginPhaseIntent(fresh());d=setPhaseIntentText(d,journey);return interpretPhaseIntentDraft(d,{now:new Date("2026-07-21")})}

describe("multi-phase intent draft consumption",()=>{
 it("retains the original journey and presents every proposal before allocating IDs",()=>{const d=interpreted();expect(d.phaseEditing.intentPlanning).toMatchObject({mode:"plan_review",fullPlanIntent:journey,currentProposalIndex:0});expect(d.phaseEditing.intentPlanning.result.proposedPhases).toHaveLength(2);expect(d.phaseEditing.allocatedPhaseIds).toEqual([]);expect(d.phaseEditing.workingAuthoredPhases).toEqual([])});
 it("accepts one proposal at a time and automatically opens the next",()=>{let d=selectInterpretedPhaseProposal(interpreted(),0);d=acceptInterpretedPhase(d,{createId:()=>"opaque_1"});expect(d.phaseEditing.workingAuthoredPhases.map(x=>x.name)).toEqual(["Establish Maintenance"]);expect(d.phaseEditing.intentPlanning).toMatchObject({mode:"review",currentProposalIndex:1});expect(d.phaseEditing.intentPlanning.result.proposedPhase.name).toBe("Lean Mass Build");expect(d.phaseEditing.intentPlanning.result.proposedPhases.map(x=>x.state)).toEqual(["accepted","pending_review"]);expect(d.phaseEditing.allocatedPhaseIds).toEqual(["opaque_1"]);d=acceptInterpretedPhase(d,{createId:()=>"opaque_2"});expect(d.phaseEditing.workingAuthoredPhases.map(x=>x.id)).toEqual(["opaque_1","opaque_2"]);expect(d.phaseEditing.workingAuthoredPhases.every(x=>x.status==="upcoming")).toBe(true)});
 it("blocks advancement until pending proposals receive an explicit decision",()=>{let d=selectInterpretedPhaseProposal(interpreted(),0);d=acceptInterpretedPhase(d,{createId:()=>"opaque_1"});d=selectActiveAuthoredPhase(d,"opaque_1");expect(isPhaseSectionResolved(d)).toBe(false);d=skipInterpretedPhaseProposal(d);expect(d.phaseEditing.intentPlanning.result.proposedPhases[1].state).toBe("skipped");expect(isPhaseSectionResolved(d)).toBe(true)});
 it("requires deliberate discard before restarting and preserves accepted phases",()=>{let d=selectInterpretedPhaseProposal(interpreted(),0);d=acceptInterpretedPhase(d,{createId:()=>"opaque_1"});expect(()=>beginPhaseIntent(d)).toThrow(/Accept, skip, or discard/);d=discardPendingPhaseProposals(d);d=beginPhaseIntent(d);expect(d.phaseEditing.workingAuthoredPhases.map(x=>x.id)).toEqual(["opaque_1"]);expect(d.phaseEditing.intentPlanning.mode).toBe("describe")});
});
