import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createNodeFounderStoreFileSystem, createFounderStoreUnitOfWork } from "../../data/repositories/FounderStoreUnitOfWork";
import { normalizeAuthoredGoalPhases } from "../models/authoredGoalPhase";
import { resolveGoalPhases } from "../models/goalPhase";
import { sourceRevision } from "./GoalEditDraftService";
import { diffGoalPhases } from "./GoalPhaseDiffService";
import { GOAL_PHASE_UPDATE_COMMAND_VERSION, ProductionGoalPhasePersistenceService, createGoalPhasePersistenceService, createGoalPhaseUpdateCommand, phaseFingerprint } from "./GoalPhasePersistenceService";
import { createFullFounderMemoryProbe } from "../../testSupport/fullFounderMemoryProbe";

const dirs=[];afterEach(()=>{for(const dir of dirs.splice(0))fs.rmSync(dir,{recursive:true,force:true})});
function goal(extra={}){return{id:"goal",userId:"user",title:"Goal",type:"build_lean_mass",primary:true,status:"active",purpose:"Purpose",primaryOutcome:"Outcome",target:{type:"unspecified",direction:"unspecified",metric:null,amount:null,unit:null,targetValue:null,baselineValue:null,targetDate:null,description:null},timeline:{mode:"unspecified",startDate:null,targetDate:null,duration:null,eventDate:null,flexibility:null,ambition:null},guardrails:[{id:"goal-g",text:"Goal guardrail",accepted:true}],metadata:{keep:true},activationMetadata:{keep:true},evidenceLinks:["e1"],protocolIds:["p1"],updatedAt:"2026-07-21T00:00:00Z",...extra}}
function store(){return{version:"test",revision:5,updatedAt:"2026-07-21",user:{id:"user"},goals:[goal(),{id:"support",userId:"user",primary:false,status:"active",keep:true}],protocols:[{id:"p1"}],protocolVersions:[],energyStrategyLinks:[],executionItems:[],reminders:[],dailyBriefings:[{id:"b1"}],evidencePackages:[{id:"e1"}],canonicalEvidenceObjects:[],evidenceReviews:[],progressPhotos:[],dexaScans:[],goalTransitionDrafts:[],goalProtocolTransitionDrafts:[]}}
function phases(goalId="goal"){return[{id:"phase-1",goalId,name:"Foundation",purpose:"Calibrate",status:"active",order:0,startDate:"2026-07-21",targetDate:null,duration:{value:4,unit:"weeks"},timingMode:"fixed_duration",successCriteria:[{label:"Calibrated"}],guardrails:[],transitionPolicy:"manual_review"},{id:"phase-2",goalId,name:"Outcome",purpose:"Build",status:"upcoming",order:1,startDate:null,targetDate:"2026-10-31",duration:null,timingMode:"target_date",successCriteria:[{label:"Outcome reached"}],guardrails:[],transitionPolicy:"evidence_review"}]}
function fixture({fileSystem,serialize,corrupt=false,tokenVersion,clock}={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"phase-persist-"));dirs.push(dir);const filePath=path.join(dir,"runtime-store.json");const liveStore=store();fs.writeFileSync(filePath,`${JSON.stringify(liveStore)}\n`);let token=0,tick=0;const now=clock?()=>new Date(clock.value):()=>new Date(`2026-07-21T00:00:0${tick++}.000Z`);const service=createGoalPhasePersistenceService({runtimeStorePath:filePath,liveStore,readPersistedStore:()=>JSON.parse(fs.readFileSync(filePath,"utf8")),now,createTokenId:()=>`phase-token-${++token}`,reviewTokenVersion:tokenVersion,createUnitOfWork:(options)=>{const unit=createFounderStoreUnitOfWork({...options,fileSystem,serialize,createCommitId:()=>"phase-commit",createTransactionId:()=>"phase-tx"});if(!corrupt)return unit;return{...unit,begin(){const tx=unit.begin(),mutate=tx.mutate.bind(tx);tx.mutate=(callback)=>mutate(async staged=>{await callback(staged);staged.protocols.push({id:"corrupt"})});return tx}}}});return{filePath,liveStore,service}}
async function reviewed(f,proposed=phases()){const g=f.liveStore.goals[0];const input={founderUserId:"user",sourceGoalId:g.id,expectedSourceRevision:sourceRevision(g),originalPhaseFingerprint:phaseFingerprint(g.phases??[]),proposedAuthoredPhases:proposed,draftId:"phase-draft"};const review=await f.service.createFinalReview(input);const command=createGoalPhaseUpdateCommand({commandVersion:GOAL_PHASE_UPDATE_COMMAND_VERSION,sourceGoalId:g.id,expectedSourceRevision:input.expectedSourceRevision,originalPhaseFingerprint:input.originalPhaseFingerprint,proposedAuthoredPhases:review.proposedAuthoredPhases,approvedPhaseDiff:review.diff,finalReviewToken:review.token.id,draftId:input.draftId,requestedAt:"2026-07-21T00:01:00Z"});return{input,review,command}}

describe("authored GoalPhase persistence",()=>{
  it("normalizes a strict two-phase collection without mutating input",()=>{const input=phases(),before=structuredClone(input);const result=normalizeAuthoredGoalPhases(input,{goalId:"goal",now:new Date("2026-07-21T00:00:00Z")});expect(input).toEqual(before);expect(result).toHaveLength(2);expect(result[0]).toMatchObject({status:"active",timingMode:"fixed_duration",duration:{value:4,unit:"weeks"}});expect(result[1]).toMatchObject({status:"upcoming",timingMode:"target_date",targetDate:"2026-10-31"});expect(Object.isFrozen(result[0])).toBe(true)});
  it("rejects implicit and recommendation metadata instead of persisting it",()=>{for(const extra of [{implicit:true},{recommendationMetadata:{advisory:true}},{draftId:"draft"}])expect(()=>normalizeAuthoredGoalPhases([{...phases()[0],...extra}],{goalId:"goal"})).toThrowError(expect.objectContaining({code:"AUTHORED_PHASE_FIELD_UNSUPPORTED"}))});
  it.each([[p=>[p[0],{...p[1],id:"phase-1"}],"GOAL_PHASE_ID_DUPLICATE"],[p=>[p[0],{...p[1],order:0}],"GOAL_PHASE_ORDER_DUPLICATE"],[p=>[p[0],{...p[1],status:"active"}],"GOAL_PHASE_MULTIPLE_ACTIVE"],[p=>[{...p[0],status:"upcoming"},{...p[1],status:"completed"}],"GOAL_PHASE_SEQUENCE_INVALID"],[p=>[{...p[0],duration:{value:0,unit:"weeks"}},p[1]],"GOAL_PHASE_DURATION_INVALID"],[p=>[p[0],{...p[1],targetDate:null}],"GOAL_PHASE_TARGET_DATE_REQUIRED"],[p=>[{...p[0],goalId:"wrong"},p[1]],"AUTHORED_PHASE_GOAL_MISMATCH"]])("rejects malformed aggregates",(mutate,code)=>{expect(()=>normalizeAuthoredGoalPhases(mutate(phases()),{goalId:"goal"})).toThrowError(expect.objectContaining({code}))});
  it("allows legacy absence and explicit empty collections",()=>{expect(resolveGoalPhases(goal())[0].implicit).toBe(true);expect(normalizeAuthoredGoalPhases([],{goalId:"goal"})).toEqual([])});
});

describe("Goal Phase Diff",()=>{
  it("is empty for equivalent normalized collections",()=>{const normalized=normalizeAuthoredGoalPhases(phases(),{goalId:"goal",now:new Date("2026-07-21")});expect(diffGoalPhases(normalized,structuredClone(normalized),{goalId:"goal"})).toMatchObject({empty:true,changesOverallGoalDestination:false});});
  it("reports stable-ID changes and active operational identity",()=>{const original=normalizeAuthoredGoalPhases(phases(),{goalId:"goal",now:new Date("2026-07-21")});const proposed=original.map((phase,index)=>({...phase,name:index?phase.name:"Renamed",status:index?"active":"completed"}));const diff=diffGoalPhases(original,proposed,{goalId:"goal"});expect(diff).toMatchObject({empty:false,renamed:[{phaseId:"phase-1"}],activePhaseIdentityChanged:true,altersCurrentOperationalPhase:true,changesOverallGoalDestination:false})});
});

describe("revision-checked phase commit",()=>{
  it("commits two phases atomically, rehydrates them, and advances once",async()=>{const f=fixture(),before=structuredClone(f.liveStore);const {command}=await reviewed(f);const result=await f.service.commit(command,{founderUserId:"user"});expect(result).toMatchObject({status:"committed",previousRevision:5,committedRevision:6,activePhaseId:"phase-1",reviewTokenConsumed:true});const persisted=JSON.parse(fs.readFileSync(f.filePath,"utf8"));expect(resolveGoalPhases(persisted.goals[0]).map(p=>p.id)).toEqual(["phase-1","phase-2"]);for(const field of ["title","purpose","primaryOutcome","target","timeline","guardrails","metadata","activationMetadata","evidenceLinks","protocolIds","status"])expect(persisted.goals[0][field]).toEqual(before.goals[0][field]);expect(persisted.goals[1]).toEqual(before.goals[1]);for(const root of ["protocols","dailyBriefings","reminders","evidencePackages","goalTransitionDrafts"])expect(persisted[root]).toEqual(before[root]);expect(persisted.revision).toBe(6)});
  it("returns prior success for duplicate submit without another revision",async()=>{const f=fixture();const {command}=await reviewed(f);const first=await f.service.commit(command,{founderUserId:"user"});expect(await f.service.commit(command,{founderUserId:"user"})).toEqual(first);expect(f.liveStore.revision).toBe(6)});
  it("rejects stale goal revisions and stale phase fingerprints without overwrite",async()=>{for(const mutate of [g=>{g.updatedAt="2026-07-22"},g=>{g.phases=normalizeAuthoredGoalPhases(phases(),{goalId:"goal"})}]){const f=fixture();const {command}=await reviewed(f);mutate(f.liveStore.goals[0]);fs.writeFileSync(f.filePath,`${JSON.stringify(f.liveStore)}\n`);const before=fs.readFileSync(f.filePath);const result=await f.service.commit(command,{founderUserId:"user"});expect(result).toMatchObject({status:"stale",draftPreserved:true});expect(fs.readFileSync(f.filePath).equals(before)).toBe(true);expect(f.liveStore.revision).toBe(5)}});
  it("rejects altered phases, diffs, tokens, wrong goal, and unsupported commands",async()=>{expect(()=>createGoalPhaseUpdateCommand({commandVersion:"future"})).toThrow(/Unsupported/);for(const mutate of [c=>({...c,proposedAuthoredPhases:c.proposedAuthoredPhases.map((p,i)=>i?{...p,name:"Altered"}:p)}),c=>({...c,approvedPhaseDiff:{...c.approvedPhaseDiff,changesOverallGoalDestination:true}}),c=>({...c,finalReviewToken:"wrong"}),c=>({...c,sourceGoalId:"wrong"})]){const f=fixture();const {command}=await reviewed(f);const result=await f.service.commit(mutate(structuredClone(command)),{founderUserId:"user"});expect(result.status).toBe("rejected");expect(f.liveStore.revision).toBe(5)}});
  it("does not write or issue a token for an empty diff",async()=>{const f=fixture();const g=f.liveStore.goals[0];const review=await f.service.createFinalReview({founderUserId:"user",sourceGoalId:g.id,expectedSourceRevision:sourceRevision(g),originalPhaseFingerprint:phaseFingerprint([]),proposedAuthoredPhases:[],draftId:"empty"});expect(review).toMatchObject({status:"no_changes",token:null});expect(f.liveStore.revision).toBe(5)});
  it("blocks removing the operational phase outside the Phase Review coordinator",async()=>{const f=fixture();f.liveStore.goals[0].phases=normalizeAuthoredGoalPhases(phases(),{goalId:"goal"});fs.writeFileSync(f.filePath,`${JSON.stringify(f.liveStore)}\n`);const g=f.liveStore.goals[0];const review=await f.service.createFinalReview({founderUserId:"user",sourceGoalId:g.id,expectedSourceRevision:sourceRevision(g),originalPhaseFingerprint:phaseFingerprint(g.phases),proposedAuthoredPhases:[],draftId:"phase-draft"});expect(review).toMatchObject({status:"rejected",reasonCode:"PHASE_REVIEW_COORDINATOR_REQUIRED",draftPreserved:true});expect(JSON.parse(fs.readFileSync(f.filePath,"utf8")).goals[0].phases).toHaveLength(2)});
  it("blocks switching the active phase outside the Phase Review coordinator",async()=>{const f=fixture();f.liveStore.goals[0].phases=normalizeAuthoredGoalPhases(phases(),{goalId:"goal"});fs.writeFileSync(f.filePath,`${JSON.stringify(f.liveStore)}\n`);const g=f.liveStore.goals[0],proposed=g.phases.map((phase,index)=>({...phase,status:index?"active":"completed",completedAt:index?null:"2026-08-15"}));const review=await f.service.createFinalReview({founderUserId:"user",sourceGoalId:g.id,expectedSourceRevision:sourceRevision(g),originalPhaseFingerprint:phaseFingerprint(g.phases),proposedAuthoredPhases:proposed,draftId:"phase-draft"});expect(review).toMatchObject({status:"rejected",reasonCode:"PHASE_REVIEW_COORDINATOR_REQUIRED"});expect(JSON.parse(fs.readFileSync(f.filePath,"utf8")).goals[0].phases[0].status).toBe("active")});
  it("propagates serialization, candidate, and atomic replacement failures without revision advance",async()=>{const base=createNodeFounderStoreFileSystem();for(const options of [{serialize(){throw new Error("serialize")}}, {corrupt:true}, {fileSystem:{...base,atomicReplace(){throw new Error("replace")}}}]){const f=fixture(options);const {command}=await reviewed(f);const result=await f.service.commit(command,{founderUserId:"user"});expect(result.status).toBe("failed");expect(f.liveStore.revision).toBe(5)}});
  it("rejects unsupported and expired phase review tokens",async()=>{const unsupported=fixture({tokenVersion:"future"});let value=await reviewed(unsupported);expect(await unsupported.service.commit(value.command,{founderUserId:"user"})).toMatchObject({status:"rejected",reasonCode:"REVIEW_TOKEN_VERSION_UNSUPPORTED"});const clock={value:"2026-07-21T00:00:00Z"},expired=fixture({clock});value=await reviewed(expired);clock.value="2026-07-21T00:11:00Z";expect(await expired.service.commit(value.command,{founderUserId:"user"})).toMatchObject({status:"rejected",reasonCode:"REVIEW_TOKEN_EXPIRED"})});
  it("reports read-only capability without creating phases",async()=>{const f=fixture();const before=fs.readFileSync(f.filePath);expect(await f.service.getCapability({founderUserId:"user",sourceGoalId:"goal"})).toMatchObject({available:true,explicitPhaseCount:0,hasExplicitPhases:false,aggregateValid:true,atomicCommitAvailable:true,staleWriteProtectionAvailable:true,reviewTokenAvailable:true,blockingReasons:[]});expect(fs.readFileSync(f.filePath).equals(before)).toBe(true)});
  it("reports production capability for the real explicit phase collection without writing",async()=>{const file="private/founder/runtime-store.json",before=fs.readFileSync(file);const memory=createFullFounderMemoryProbe({label:"GoalPhasePersistenceService production capability",logicalStoreBytes:before.length,maxHeapUsedBytes:512*1024*1024,maxRssBytes:768*1024*1024});const state=JSON.parse(before),g=state.goals.find(x=>x.primary&&x.status==="active"),count=Array.isArray(g.phases)?g.phases.length:0;memory.checkpoint("production_store_parsed");const capability=await ProductionGoalPhasePersistenceService.getCapability({founderUserId:state.user.id,sourceGoalId:g.id});memory.checkpoint("production_capability_resolved");expect(capability).toMatchObject({available:true,explicitPhaseCount:count,hasExplicitPhases:count>0,aggregateValid:true});expect(fs.readFileSync(file).equals(before)).toBe(true);memory.finish({testOwnedFullStoreParses:1,serviceFullStoreParses:1,testOwnedFullStoreClones:0,testOwnedFullStoreSerializations:0,fullStoreDeepFreezes:0,productionSingletonStores:1,temporaryStoreInstances:0})},60000);
});
