import { describe, expect, it } from "vitest";
import { buildGoalEditDraft, selectGoalEditSections, updateGoalEditWorkingPlan } from "./GoalEditDraftService";
import { acceptInterpretedPhase, acceptPhaseSuggestions, addManualPhase, assessPhaseRecommendationResult, beginPhaseIntent, chooseContinuousGoal, duplicateAuthoredPhase, extendGoalEditDraftWithPhases, interpretPhaseIntentDraft, isPhaseSectionResolved, moveAuthoredPhase, removeAuthoredPhase, requestPhaseRecommendation, resolvePhasePlanningEntry, restoreOriginalPhases, returnToPhaseStructureChoice, selectActiveAuthoredPhase, setPhaseIntentText, updateAuthoredPhase, validatePhaseEditingDraft } from "./GoalEditPhaseDraftService";

const goal={id:"goal_live",userId:"founder",status:"active",primary:true,title:"Build Lean Mass",goalType:"lean_mass",planningSignals:{baselineRequired:true,strategyChangesOverTime:true},updatedAt:"2026-07-21T00:00:00.000Z"};
const draft=()=>extendGoalEditDraftWithPhases(buildGoalEditDraft(goal),{goal,capability:{available:true,blockingReasons:[]},now:new Date("2026-07-21T00:00:00Z")});

describe("Goal Edit phase draft",()=>{
 it("opens without authoring implicit phases and keeps immutable collections",()=>{const d=draft();expect(d.phaseEditing.originalAuthoredPhases).toEqual([]);expect(d.phaseEditing.workingAuthoredPhases).toEqual([]);expect(d.phaseEditing.recommendationResult).toBeNull();expect(Object.isFrozen(d)).toBe(true)});
 it("gates the selectable section by persistence capability",()=>{expect(selectGoalEditSections(draft(),["phases"]).selectedSections).toEqual(["phases"]);const blocked=extendGoalEditDraftWithPhases(buildGoalEditDraft(goal),{goal,capability:{available:false,blockingReasons:["blocked"]}});expect(()=>selectGoalEditSections(blocked,["phases"])).toThrow(/blocked/)});
 it("runs intelligence explicitly and allocates IDs only on acceptance",()=>{const planned=updateGoalEditWorkingPlan(draft(),{proposedStages:[{name:"Foundation",purpose:"Prepare",order:0,timing:{},successCriteria:[]},{name:"Build",purpose:"Grow",order:1,timing:{},successCriteria:[]}]});const requested=requestPhaseRecommendation(planned);expect(requested.phaseEditing.workingAuthoredPhases).toEqual([]);let n=0;const accepted=acceptPhaseSuggestions(requested,{createId:()=>`opaque_${++n}`});expect(accepted.phaseEditing.workingAuthoredPhases.length).toBeGreaterThan(1);expect(accepted.phaseEditing.allocatedPhaseIds).toEqual(["opaque_1","opaque_2"]);expect(accepted.phaseEditing.workingAuthoredPhases.every(x=>x.guardrails.length===0)).toBe(true)});
 it("keeps identity stable across rename/reorder and reserves deletions",()=>{let n=0;const id=()=>`opaque_${++n}`;let d=addManualPhase(draft(),{createId:id});d=addManualPhase(d,{createId:id});const first=d.phaseEditing.workingAuthoredPhases[0].id;d=updateAuthoredPhase(d,first,{name:"Foundation",purpose:"Prepare"});d=moveAuthoredPhase(d,first,"later");expect(d.phaseEditing.workingAuthoredPhases[1].id).toBe(first);d=removeAuthoredPhase(d,first);d=addManualPhase(d,{createId:id});expect(d.phaseEditing.allocatedPhaseIds).toEqual(["opaque_1","opaque_2","opaque_3"])});
 it("duplicates using a fresh upcoming identity",()=>{let d=addManualPhase(draft(),{createId:()=>"opaque_1"});d=duplicateAuthoredPhase(d,"opaque_1",{createId:()=>"opaque_2"});expect(d.phaseEditing.workingAuthoredPhases.map(x=>x.id)).toEqual(["opaque_1","opaque_2"]);expect(d.phaseEditing.workingAuthoredPhases[1].status).toBe("upcoming")});
 it("requires explicit active selection and authoritative timing validation",()=>{let d=addManualPhase(draft(),{createId:()=>"opaque_1"});d=updateAuthoredPhase(d,"opaque_1",{name:"Establish Maintenance",purpose:"Stabilize",timingMode:"fixed_duration",duration:{value:4,unit:"weeks"}});expect(validatePhaseEditingDraft(d).valid).toBe(false);d=selectActiveAuthoredPhase(d,"opaque_1");expect(validatePhaseEditingDraft(d).valid).toBe(true);d=updateAuthoredPhase(d,"opaque_1",{duration:{value:0,unit:"weeks"}});expect(validatePhaseEditingDraft(d).valid).toBe(false)});
 it("supports scoped fields, continuous removal, and restore",()=>{let d=addManualPhase(draft(),{createId:()=>"opaque_1"});d=updateAuthoredPhase(d,"opaque_1",{purpose:"Operate",successCriteria:[{label:"Stable intake"}],guardrails:[{label:"No deficit"}],transitionPolicy:"automatic"});expect(d.phaseEditing.workingAuthoredPhases[0].transitionPolicy).toBe("automatic");expect(removeAuthoredPhase(d,"opaque_1").phaseEditing.workingAuthoredPhases).toEqual([]);expect(chooseContinuousGoal(d).phaseEditing.workingAuthoredPhases).toEqual([]);expect(restoreOriginalPhases(d).phaseEditing.workingAuthoredPhases).toEqual([])});
 it("authors intent-first only after explicit interpretation acceptance",()=>{let d=beginPhaseIntent(draft());expect(d.phaseEditing.workingAuthoredPhases).toEqual([]);d=setPhaseIntentText(d,"Starting July 21, spend four weeks establishing maintenance calories and training performance.");d=interpretPhaseIntentDraft(d,{now:new Date("2026-07-21")});expect(d.phaseEditing.intentPlanning.result.proposedPhase).not.toHaveProperty("id");expect(d.phaseEditing.workingAuthoredPhases).toEqual([]);d=acceptInterpretedPhase(d,{createId:()=>"opaque_intent"});expect(d.phaseEditing.workingAuthoredPhases[0]).toMatchObject({id:"opaque_intent",status:"upcoming",startDate:"2026-07-21",duration:{value:4,unit:"weeks"}})});
 it("gates empty and malformed recommendation results without allocating identity",()=>{expect(assessPhaseRecommendationResult({recommendation:"not_recommended",suggestedPhases:[]})).toMatchObject({available:false,kind:"not_recommended"});expect(assessPhaseRecommendationResult({recommendation:"optional",suggestedPhases:[]})).toMatchObject({available:false,kind:"optional_empty"});expect(assessPhaseRecommendationResult({recommendation:"recommended",suggestedPhases:[]})).toMatchObject({available:false,kind:"malformed",diagnosticCode:"PHASE_RECOMMENDATION_EMPTY"});expect(assessPhaseRecommendationResult({recommendation:"recommended",suggestedPhases:[{name:"Broken"}]})).toMatchObject({available:false,kind:"malformed"});expect(()=>acceptPhaseSuggestions({...draft(),phaseEditing:{...draft().phaseEditing,recommendationResult:{recommendation:"recommended",suggestedPhases:[]}}})).toThrow(/No valid suggested/)});
 it("returns safely from recommendation review without clearing authored phases or allocating IDs",()=>{const d=requestPhaseRecommendation(draft());const returned=returnToPhaseStructureChoice(d);expect(returned.phaseEditing).toMatchObject({recommendationResult:null,recommendationDecision:"not_requested",allocatedPhaseIds:[],workingAuthoredPhases:[]});expect(returned.phaseEditing.intentPlanning.mode).toBe("idle")});
 it("opens an unphased no-suggestion goal directly in broad intent entry",()=>{const entered=resolvePhasePlanningEntry({...draft(),currentStep:"phases",selectedSections:["phases","overall_goal"]});expect(entered.phaseEditing.intentPlanning.mode).toBe("describe");expect(entered.phaseEditing.recommendationDecision).toBe("intent_required");expect(entered.phaseEditing.workingAuthoredPhases).toEqual([]);expect(isPhaseSectionResolved(entered)).toBe(false)});
 it("advances an explicit continuous decision directly to the next selected step",()=>{const withOverall={...draft(),currentStep:"phases",selectedSections:["phases","overall_goal"]};expect(chooseContinuousGoal(withOverall)).toMatchObject({currentStep:"overall_goal",phaseEditing:{recommendationDecision:"continuous",workingAuthoredPhases:[],diff:{empty:true}}});const phaseOnly={...draft(),currentStep:"phases",selectedSections:["phases"]};expect(chooseContinuousGoal(phaseOnly).currentStep).toBe("review")});
 it("cannot resolve interpreted but unaccepted or accepted-without-active phase state",()=>{let d=resolvePhasePlanningEntry({...draft(),currentStep:"phases",selectedSections:["phases"]});d=setPhaseIntentText(d,"Starting July 21, spend four weeks establishing maintenance calories and training performance.");d=interpretPhaseIntentDraft(d,{now:new Date("2026-07-21")});expect(isPhaseSectionResolved(d)).toBe(false);d=acceptInterpretedPhase(d,{createId:()=>"opaque_unresolved"});expect(isPhaseSectionResolved(d)).toBe(false);d=selectActiveAuthoredPhase(d,"opaque_unresolved");expect(isPhaseSectionResolved(d)).toBe(true)});
});
