import { createClientDraftId } from "../../lib/clientDraftId";
import { normalizeAuthoredGoalPhases } from "../models/authoredGoalPhase";
import { GoalPhaseStatus, GoalPhaseTimingMode, GoalPhaseTransitionPolicy } from "../models/goalPhase";
import { adaptSuggestedPhaseToGoalPhaseInput, recommendGoalPhases } from "./GoalPhaseRecommendationService";
import { diffGoalPhases } from "./GoalPhaseDiffService";
import { GOAL_PHASE_INTENT_INTERPRETATION_VERSION, interpretGoalPhaseIntent, normalizeGoalPhaseInterpretationResult, reviseGoalPhaseIntent } from "./GoalPhaseIntentInterpretationService";
import { expectedPhaseReviewDate, phaseTimingSnapshot } from "./GoalPhaseTimelineIntegrityService";

export function extendGoalEditDraftWithPhases(draft, { goal, capability, now = new Date() } = {}) {
  if (draft.phaseEditing) return draft;
  const original = Array.isArray(goal?.phases) ? normalizeAuthoredGoalPhases(goal.phases, { goalId: goal.id, parentGoalStatus: goal.status, now, existingPhases: goal.phases }) : Object.freeze([]);
  return deepFreeze({ ...structuredClone(draft), phaseEditing: {
    originalAuthoredPhases: original, workingAuthoredPhases: structuredClone(original), originalPhaseFingerprint: phaseFingerprint(original),
    capability: structuredClone(capability), recommendationResult: null, recommendationDecision: "not_requested",
    allocatedPhaseIds: original.map((phase) => phase.id), selectedActivePhaseId: original.find((phase) => phase.status === "active")?.id ?? null,
    validation: { valid: original.length === 0, errors: [] }, diff: diffGoalPhases(original, original, { goalId: goal.id }),
    finalReview: { status: "not_requested", token: null }, commitResult: null, structureChoice: original.length ? "existing" : null,
    timingProvenance: Object.fromEntries(original.map(phase=>[phase.id,{source:"persisted",suppliedTiming:null,interpretedTiming:null,confirmedTiming:phaseTimingSnapshot(phase),deliberateUntimed:phase.timingMode==="completion_criteria"}])),
    intentPlanning: { mode: "idle", intentText: "", revisionText: "", result: null, acceptedCount: 0, fullPlanIntent: "", proposalStates: [], currentProposalIndex: 0, clarificationAnswers: [] },
  }});
}

export function requestPhaseRecommendation(draft) {
  const result = recommendGoalPhases(draft.workingPlan);
  return phaseUpdate(draft, { recommendationResult: result, recommendationDecision: "reviewing", structureChoice: "suggested" });
}
export function resolvePhasePlanningEntry(draft) { if(draft.phaseEditing.capability?.available!==true)return phaseUpdate(draft,{recommendationDecision:"unavailable"});if(draft.phaseEditing.workingAuthoredPhases.length)return phaseUpdate(draft,{recommendationDecision:"existing_review",intentPlanning:{...structuredClone(draft.phaseEditing.intentPlanning),mode:"accepted"}});const recommended=requestPhaseRecommendation(draft);const availability=assessPhaseRecommendationResult(recommended.phaseEditing.recommendationResult);if(availability.available)return recommended;const intent=beginPhaseIntent(recommended);return phaseUpdate(intent,{recommendationResult:recommended.phaseEditing.recommendationResult,recommendationDecision:"intent_required",entryDiagnostic:availability.diagnosticCode}); }
export function retainExistingPhaseStructure(draft) { return phaseUpdate(draft, { recommendationDecision: "existing_retained", intentPlanning: { ...structuredClone(draft.phaseEditing.intentPlanning), mode: "accepted" } }); }
export function isPhaseSectionResolved(draft) { if(draft.phaseEditing?.recommendationDecision==="continuous")return true;if(draft.phaseEditing?.recommendationDecision==="existing_retained")return true;if(!(draft.phaseEditing?.workingAuthoredPhases?.length>0)||!draft.phaseEditing?.selectedActivePhaseId)return false;const planning=draft.phaseEditing?.intentPlanning;const pending=planning?.result?.proposedPhases?.some(x=>!["accepted","skipped","replaced"].includes(x.state));return validatePhaseEditingDraft(draft).valid&&!pending&&!["describe","clarification_required","plan_review","review","revise","rejected"].includes(planning?.mode); }
export function returnToPhaseStructureChoice(draft) { return phaseUpdate(draft, { recommendationResult: null, recommendationDecision: "not_requested", structureChoice: draft.phaseEditing.workingAuthoredPhases.length ? draft.phaseEditing.structureChoice : null, intentPlanning: { ...structuredClone(draft.phaseEditing.intentPlanning), mode: draft.phaseEditing.workingAuthoredPhases.length ? draft.phaseEditing.intentPlanning.mode : "idle", result: null, revisionText: "" } }); }

export function acceptPhaseSuggestions(draft, { customize = false, now = new Date(), createId = () => createClientDraftId("goal_phase") } = {}) {
  const availability = assessPhaseRecommendationResult(draft.phaseEditing?.recommendationResult);
  const suggestions = availability.suggestions;
  if (!availability.available) throw new GoalEditPhaseDraftError(availability.diagnosticCode, "No valid suggested phases are available to accept.");
  let state = draft; const authored = [];
  for (const suggestion of suggestions) {
    const allocated = allocatePhaseId(state, createId); state = allocated.draft;
    authored.push(adaptSuggestedPhaseToGoalPhaseInput(suggestion, { id: allocated.id, goalId: draft.sourceGoalId, status: GoalPhaseStatus.UPCOMING, createdAt: new Date(now).toISOString(), updatedAt: new Date(now).toISOString() }));
  }
  return setWorking(state, authored, { recommendationDecision: customize ? "customizing" : "accepted", structureChoice: customize ? "customized_suggestions" : "accepted_suggestions", selectedActivePhaseId: null });
}

export function assessPhaseRecommendationResult(result) { const level=result?.recommendation;const raw=result?.suggestedPhases;if(!Array.isArray(raw))return deepFreeze({available:false,kind:"malformed",suggestions:[],diagnosticCode:"PHASE_RECOMMENDATION_SUGGESTIONS_INVALID"});const valid=raw.filter(validSuggestion);if(raw.length!==valid.length)return deepFreeze({available:false,kind:"malformed",suggestions:[],diagnosticCode:"PHASE_RECOMMENDATION_SUGGESTION_MALFORMED"});if(!["recommended","optional"].includes(level))return deepFreeze({available:false,kind:"not_recommended",suggestions:[],diagnosticCode:"PHASE_RECOMMENDATION_NOT_AVAILABLE"});if(!valid.length)return deepFreeze({available:false,kind:level==="optional"?"optional_empty":"malformed",suggestions:[],diagnosticCode:level==="optional"?"PHASE_RECOMMENDATION_OPTIONAL_EMPTY":"PHASE_RECOMMENDATION_EMPTY"});return deepFreeze({available:true,kind:level,suggestions:valid,diagnosticCode:null}); }

export function chooseContinuousGoal(draft) { const resolved=setWorking(draft, [], { recommendationDecision: "continuous", structureChoice: "continuous", selectedActivePhaseId: null });if(draft.currentStep!=="phases")return resolved;const sequence=["choose_sections",...(draft.selectedSections??[]),"review"];const index=sequence.indexOf("phases");return deepFreeze({...structuredClone(resolved),currentStep:sequence[Math.min(sequence.length-1,index+1)]??"review"}); }
export function chooseManualPhases(draft) { return setWorking(draft, [], { recommendationDecision: "manual", structureChoice: "manual", selectedActivePhaseId: null }); }

export function beginPhaseIntent(draft) { const previous=draft.phaseEditing?.intentPlanning??{};if(previous.result?.proposedPhases?.some(x=>x.state==="pending_review"))throw new GoalEditPhaseDraftError("PENDING_PHASE_PROPOSALS_REQUIRE_DECISION","Accept, skip, or discard the remaining phase proposals before starting over.");return phaseUpdate(draft, { structureChoice: "manual", intentPlanning: { mode: "describe", intentText: "", revisionText: "", result: null, acceptedCount: previous.acceptedCount??0, fullPlanIntent:"", proposalStates:[], currentProposalIndex:0, clarificationAnswers:structuredClone(previous.clarificationAnswers??[]) } }); }
export function setPhaseIntentText(draft, intentText) { return phaseUpdate(draft, { intentPlanning: { ...structuredClone(draft.phaseEditing.intentPlanning), intentText: String(intentText ?? "") } }); }
export function interpretPhaseIntentDraft(draft, { now = new Date() } = {}) { const planning=draft.phaseEditing.intentPlanning;const accepted=draft.phaseEditing.workingAuthoredPhases;const previous=accepted.at(-1)??null;const result=interpretGoalPhaseIntent({sourceGoalId:draft.sourceGoalId,canonicalGoalPlan:draft.workingPlan,existingAuthoredPhases:accepted,phasePosition:accepted.length,userIntent:planning.intentText,fullOriginalIntent:planning.fullPlanIntent||planning.intentText,remainingUnconsumedIntent:planning.result?.remainingUnconsumedIntent??planning.intentText,currentDate:now,knownGoalLevelTarget:draft.workingPlan.target,knownGoalLevelTimeline:draft.workingPlan.timeline,knownGoalLevelGuardrails:draft.workingPlan.guardrails,surroundingPhaseContext:{previousPhase:previous,nextKnownPhase:null,acceptedPhases:accepted},interpretationVersion:GOAL_PHASE_INTENT_INTERPRETATION_VERSION});const mode=result.status==="interpreted"?(result.proposedPhases.length>1?"plan_review":"review"):result.status;return phaseUpdate(draft,{intentPlanning:{...structuredClone(planning),mode,result,fullPlanIntent:planning.fullPlanIntent||planning.intentText,proposalStates:result.proposedPhases.map(x=>({proposalKey:x.proposalKey,state:x.state})),currentProposalIndex:result.currentProposalIndex}}); }
export function selectInterpretedPhaseProposal(draft,index){const planning=draft.phaseEditing.intentPlanning,result=planning.result;if(!result?.proposedPhases?.[index])throw new GoalEditPhaseDraftError("PHASE_PROPOSAL_NOT_FOUND","Choose an available phase proposal.");const normalized=normalizeGoalPhaseInterpretationResult({...structuredClone(result),currentProposalIndex:index,remainingUnconsumedIntent:remainingProposalIntent(result.proposedPhases,index)});return phaseUpdate(draft,{intentPlanning:{...structuredClone(planning),mode:"review",result:normalized,currentProposalIndex:index}})}
export function confirmInterpretedPhaseStartDate(draft,startDate,{today=new Date()}={}){const planning=draft.phaseEditing.intentPlanning,result=planning.result,index=result?.currentProposalIndex??0,envelope=result?.proposedPhases?.[index];if(!envelope)throw new GoalEditPhaseDraftError("PHASE_PROPOSAL_NOT_FOUND","Choose an available phase proposal.");const value=startDate==="today"?dateKey(today):startDate;if(!validDate(value))throw new GoalEditPhaseDraftError("PHASE_START_DATE_INVALID","Choose a valid phase start date.");const phase={...structuredClone(envelope.phase),startDate:value};const proposals=structuredClone(result.proposedPhases);proposals[index]={...proposals[index],phase,timingProvenance:{...structuredClone(envelope.timingProvenance),confirmed:phaseTimingSnapshot(phase)}};const normalized=normalizeGoalPhaseInterpretationResult({...structuredClone(result),proposedPhases:proposals,currentProposalIndex:index});return phaseUpdate(draft,{intentPlanning:{...structuredClone(planning),result:normalized}})}
export function setPhaseRevisionText(draft, revisionText) { return phaseUpdate(draft, { intentPlanning: { ...structuredClone(draft.phaseEditing.intentPlanning), revisionText: String(revisionText ?? ""), mode: "revise" } }); }
export function revisePhaseIntentDraft(draft, { now = new Date() } = {}) { const planning=draft.phaseEditing.intentPlanning; const result=reviseGoalPhaseIntent({currentResult:planning.result,revisionInstruction:planning.revisionText,currentDate:now,canonicalGoalPlan:draft.workingPlan,existingAuthoredPhases:draft.phaseEditing.workingAuthoredPhases}); return phaseUpdate(draft,{intentPlanning:{...structuredClone(planning),mode:result.status==="interpreted"?"review":result.status,result,proposalStates:result.proposedPhases.map(x=>({proposalKey:x.proposalKey,state:x.state})),currentProposalIndex:result.currentProposalIndex,revisionText:""}}); }
export function acceptInterpretedPhase(draft, { now = new Date(), createId = () => createClientDraftId("goal_phase") } = {}) { const planning=draft.phaseEditing.intentPlanning,result=planning?.result,index=result?.currentProposalIndex??0,envelope=result?.proposedPhases?.[index],proposal=envelope?.phase??result?.proposedPhase;if(!proposal)throw new GoalEditPhaseDraftError("PHASE_INTENT_ACCEPTANCE_UNAVAILABLE","Interpret a valid phase before accepting it.");assertProposalTimingComplete(proposal,envelope?.timingProvenance);const allocated=allocatePhaseId(draft,createId);const phase={...structuredClone(proposal),id:allocated.id,goalId:draft.sourceGoalId,status:GoalPhaseStatus.UPCOMING,order:allocated.draft.phaseEditing.workingAuthoredPhases.length,createdAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString()};const accepted=setWorking(allocated.draft,[...allocated.draft.phaseEditing.workingAuthoredPhases,phase],{structureChoice:"manual"});const timingProvenance={...structuredClone(accepted.phaseEditing.timingProvenance),[phase.id]:{source:"interpreted",proposalKey:envelope?.proposalKey??null,suppliedTiming:structuredClone(envelope?.timingProvenance?.supplied??{}),interpretedTiming:structuredClone(envelope?.timingProvenance?.interpreted??phaseTimingSnapshot(proposal)),confirmedTiming:phaseTimingSnapshot(phase),deliberateUntimed:envelope?.timingProvenance?.deliberateUntimed===true}};const proposals=structuredClone(result.proposedPhases);proposals[index]={...proposals[index],state:"accepted"};const next=proposals.findIndex((x,i)=>i>index&&x.state==="pending_review");const nextIndex=next>=0?next:index;const normalized=normalizeGoalPhaseInterpretationResult({...structuredClone(result),proposedPhases:proposals,currentProposalIndex:nextIndex,remainingUnconsumedIntent:remainingProposalIntent(proposals,nextIndex)});return phaseUpdate(accepted,{timingProvenance,intentPlanning:{...structuredClone(planning),mode:next>=0?"review":"accepted",intentText:"",revisionText:"",result:normalized,acceptedCount:(planning.acceptedCount??0)+1,proposalStates:proposals.map(x=>({proposalKey:x.proposalKey,state:x.state})),currentProposalIndex:nextIndex}}); }
export function skipInterpretedPhaseProposal(draft){return decidePendingProposal(draft,"skipped")}
export function discardPendingPhaseProposals(draft){const planning=draft.phaseEditing.intentPlanning,result=planning.result;if(!result)return draft;const proposals=result.proposedPhases.map(x=>x.state==="pending_review"?{...structuredClone(x),state:"skipped"}:structuredClone(x));const normalized=normalizeGoalPhaseInterpretationResult({...structuredClone(result),proposedPhases:proposals,remainingUnconsumedIntent:""});return phaseUpdate(draft,{intentPlanning:{...structuredClone(planning),mode:draft.phaseEditing.workingAuthoredPhases.length?"accepted":"idle",result:normalized,proposalStates:proposals.map(x=>({proposalKey:x.proposalKey,state:x.state}))}})}
export function openPhaseIntentManualDetails(draft, options = {}) { const result=draft.phaseEditing.intentPlanning?.result;if(!result?.proposedPhase)return openAdvancedPhaseDetails(addManualPhase(draft,options));return openAdvancedPhaseDetails(acceptInterpretedPhase(draft,options)); }
export function openAdvancedPhaseDetails(draft) { return phaseUpdate(draft, { intentPlanning: { ...structuredClone(draft.phaseEditing.intentPlanning), mode: "advanced" } }); }

export function addManualPhase(draft, { now = new Date(), createId = () => createClientDraftId("goal_phase") } = {}) {
  const allocated = allocatePhaseId(draft, createId); const phases = [...allocated.draft.phaseEditing.workingAuthoredPhases, {
    id: allocated.id, goalId: draft.sourceGoalId, name: "New phase", purpose: "", status: GoalPhaseStatus.UPCOMING,
    order: allocated.draft.phaseEditing.workingAuthoredPhases.length, startDate: null, targetDate: null, duration: null,
    timingMode: GoalPhaseTimingMode.COMPLETION_CRITERIA, successCriteria: [], guardrails: [], transitionPolicy: GoalPhaseTransitionPolicy.MANUAL_REVIEW,
    createdAt: new Date(now).toISOString(), updatedAt: new Date(now).toISOString(),
  }];
  return setWorking(allocated.draft, phases, { structureChoice: "manual" });
}

export function updateAuthoredPhase(draft, phaseId, patch) {
  if (patch.id != null && patch.id !== phaseId) throw new GoalEditPhaseDraftError("PHASE_ID_IMMUTABLE", "Phase identity cannot be changed.");
  const phases = draft.phaseEditing.workingAuthoredPhases.map((phase) => phase.id === phaseId ? { ...structuredClone(phase), ...structuredClone(patch), id: phaseId, goalId: draft.sourceGoalId } : structuredClone(phase));
  if (!phases.some((phase) => phase.id === phaseId)) throw new GoalEditPhaseDraftError("PHASE_NOT_FOUND", "Phase was not found.");
  const updated=setWorking(draft, phases),phase=updated.phaseEditing.workingAuthoredPhases.find(item=>item.id===phaseId),prior=updated.phaseEditing.timingProvenance?.[phaseId]??{source:"manual",suppliedTiming:null,interpretedTiming:null};return phaseUpdate(updated,{timingProvenance:{...structuredClone(updated.phaseEditing.timingProvenance??{}),[phaseId]:{...structuredClone(prior),confirmedTiming:phaseTimingSnapshot(phase),deliberateUntimed:phase.timingMode==="completion_criteria"}}});
}

export function removeAuthoredPhase(draft, phaseId) { return setWorking(draft, normalizeOrders(draft.phaseEditing.workingAuthoredPhases.filter((phase) => phase.id !== phaseId)), { selectedActivePhaseId: draft.phaseEditing.selectedActivePhaseId === phaseId ? null : draft.phaseEditing.selectedActivePhaseId }); }
export function moveAuthoredPhase(draft, phaseId, direction) { const phases = [...draft.phaseEditing.workingAuthoredPhases]; const index = phases.findIndex((phase) => phase.id === phaseId); const other = direction === "earlier" ? index - 1 : index + 1; if (index < 0 || other < 0 || other >= phases.length) return draft; [phases[index], phases[other]] = [phases[other], phases[index]]; return setWorking(draft, normalizeOrders(phases)); }
export function duplicateAuthoredPhase(draft, phaseId, { now = new Date(), createId = () => createClientDraftId("goal_phase") } = {}) { const source = draft.phaseEditing.workingAuthoredPhases.find((phase) => phase.id === phaseId); if (!source) throw new GoalEditPhaseDraftError("PHASE_NOT_FOUND", "Phase was not found."); const allocated = allocatePhaseId(draft, createId); const copy = { ...structuredClone(source), id: allocated.id, name: `${source.name} copy`, status: GoalPhaseStatus.UPCOMING, order: allocated.draft.phaseEditing.workingAuthoredPhases.length, createdAt: new Date(now).toISOString(), updatedAt: new Date(now).toISOString() }; return setWorking(allocated.draft, [...allocated.draft.phaseEditing.workingAuthoredPhases, copy]); }
export function restoreOriginalPhases(draft) { return setWorking(draft, draft.phaseEditing.originalAuthoredPhases, { selectedActivePhaseId: draft.phaseEditing.originalAuthoredPhases.find((phase) => phase.status === "active")?.id ?? null, structureChoice: draft.phaseEditing.originalAuthoredPhases.length ? "existing" : null }); }

export function selectActiveAuthoredPhase(draft, phaseId) {
  if (!draft.phaseEditing.workingAuthoredPhases.some((phase) => phase.id === phaseId)) throw new GoalEditPhaseDraftError("PHASE_NOT_FOUND", "Choose an authored phase.");
  const selectedIndex = draft.phaseEditing.workingAuthoredPhases.findIndex((phase) => phase.id === phaseId);
  const phases = draft.phaseEditing.workingAuthoredPhases.map((phase, index) => ({ ...structuredClone(phase), status: index < selectedIndex ? ([GoalPhaseStatus.COMPLETED, GoalPhaseStatus.SKIPPED].includes(phase.status) ? phase.status : GoalPhaseStatus.COMPLETED) : index === selectedIndex ? GoalPhaseStatus.ACTIVE : GoalPhaseStatus.UPCOMING }));
  return setWorking(draft, phases, { selectedActivePhaseId: phaseId });
}

export function validatePhaseEditingDraft(draft) {
  const phases = draft.phaseEditing?.workingAuthoredPhases ?? [];
  try {
    const normalized = normalizeAuthoredGoalPhases(phases, { goalId: draft.sourceGoalId, parentGoalStatus: "active", now: new Date(draft.updatedAt), existingPhases: draft.phaseEditing.originalAuthoredPhases });
    if (normalized.length > 0 && !draft.phaseEditing.selectedActivePhaseId) throw new GoalEditPhaseDraftError("ACTIVE_PHASE_SELECTION_REQUIRED", "Choose which phase you are in now.");
    return { valid: true, errors: [], phases: normalized };
  } catch (error) { return { valid: false, errors: [{ code: error.code ?? "PHASE_VALIDATION_FAILED", message: error.message, details: error.details ?? {} }], phases: null }; }
}

export function estimatedPhaseTargetDate(phase) { return phase?.timingMode==="fixed_duration"?expectedPhaseReviewDate(phase):null; }

function setWorking(draft, phases, extra = {}) { const next = phaseUpdate(draft, { workingAuthoredPhases: normalizeOrders(structuredClone(phases)), ...extra }); const validation = validatePhaseEditingDraft(next); const diff = validation.valid ? diffGoalPhases(next.phaseEditing.originalAuthoredPhases, validation.phases, { goalId: draft.sourceGoalId }) : null; return phaseUpdate(next, { validation: { valid: validation.valid, errors: validation.errors }, diff }); }
function allocatePhaseId(draft, createId) { let id; for (let attempt = 0; attempt < 20; attempt += 1) { id = createId(); if (id && !draft.phaseEditing.allocatedPhaseIds.includes(id)) break; id = null; } if (!id) throw new GoalEditPhaseDraftError("PHASE_ID_ALLOCATION_FAILED", "A unique phase ID could not be allocated."); return { id, draft: phaseUpdate(draft, { allocatedPhaseIds: [...draft.phaseEditing.allocatedPhaseIds, id] }) }; }
function normalizeOrders(phases) { return phases.map((phase, order) => ({ ...structuredClone(phase), order })); }
function assertProposalTimingComplete(phase,provenance){if(phase.timingMode==="fixed_duration"&&!phase.duration)throw new GoalEditPhaseDraftError("PHASE_DURATION_REQUIRED","Add a valid planned duration.");if(phase.timingMode==="fixed_duration"&&!validDate(phase.startDate))throw new GoalEditPhaseDraftError("PHASE_START_DATE_REQUIRED",`Choose when this ${phase.duration?.value??"planned"}-${phase.duration?.unit?.replace(/s$/,"")??"duration"} phase should begin.`);if(phase.timingMode==="target_date"&&!validDate(phase.targetDate))throw new GoalEditPhaseDraftError("PHASE_TARGET_DATE_REQUIRED","Add the date you want this phase to reach.");if(phase.timingMode==="completion_criteria"&&provenance?.deliberateUntimed!==true)throw new GoalEditPhaseDraftError("PHASE_UNTIMED_CONFIRMATION_REQUIRED","Confirm that you want this phase to remain open-ended and evidence-led.")}
function validDate(value){return typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value}function dateKey(value){return new Date(value).toISOString().slice(0,10)}
function decidePendingProposal(draft,state){const planning=draft.phaseEditing.intentPlanning,result=planning.result,index=result?.currentProposalIndex??0;if(!result?.proposedPhases?.[index])throw new GoalEditPhaseDraftError("PHASE_PROPOSAL_NOT_FOUND","Choose an available phase proposal.");const proposals=structuredClone(result.proposedPhases);proposals[index]={...proposals[index],state};const next=proposals.findIndex((x,i)=>i>index&&x.state==="pending_review");const nextIndex=next>=0?next:index;const normalized=normalizeGoalPhaseInterpretationResult({...structuredClone(result),proposedPhases:proposals,currentProposalIndex:nextIndex,remainingUnconsumedIntent:remainingProposalIntent(proposals,nextIndex)});return phaseUpdate(draft,{intentPlanning:{...structuredClone(planning),mode:next>=0?"review":draft.phaseEditing.workingAuthoredPhases.length?"accepted":"idle",result:normalized,proposalStates:proposals.map(x=>({proposalKey:x.proposalKey,state:x.state})),currentProposalIndex:nextIndex}})}
function remainingProposalIntent(proposals,index){return proposals.filter((x,i)=>i>=index&&x.state==="pending_review").map(x=>x.sourceIntent).join(" Then ")}
function validSuggestion(value) { return value && typeof value === "object" && typeof value.name === "string" && value.name.trim() && typeof value.purpose === "string" && value.purpose.trim() && Number.isInteger(value.order) && ["fixed_duration", "target_date", "completion_criteria"].includes(value.timingMode) && ["manual_review", "evidence_review", "automatic"].includes(value.transitionPolicy) && Array.isArray(value.successCriteria) && Array.isArray(value.guardrails); }
function phaseUpdate(draft, patch) { return deepFreeze({ ...structuredClone(draft), phaseEditing: { ...structuredClone(draft.phaseEditing), ...structuredClone(patch) } }); }
function phaseFingerprint(value) { const text = stableStringify(value ?? []); let hash = 2166136261; for (let i = 0; i < text.length; i += 1) { hash ^= text.charCodeAt(i); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, "0"); }
function stableStringify(value) { if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableStringify(value[key])}`).join(",")}}`; return JSON.stringify(value); }
export class GoalEditPhaseDraftError extends Error { constructor(code, message) { super(message); this.name = "GoalEditPhaseDraftError"; this.code = code; } }
function deepFreeze(value) { if (!value || typeof value !== "object" || Object.isFrozen(value)) return value; Object.values(value).forEach(deepFreeze); return Object.freeze(value); }
