import { describe, expect, it } from "vitest";
import { mapHomeHero } from "./HomeBriefingService";

const goal = { id: "goal_visible_abs_at_rest", title: "Visible Abs at Rest" };
function evaluation(overrides = {}) { return { metricKey: "visualDefinition", title: "Visible Abs", goalConfidence: { value: 97 }, projection: { id: "projection-one", currentCompletionStage: "visual_confirmation_developing", numericalThresholdStatus: "reached", projectedFinish: "Jul 20-26", daysRemaining: "1-2 weeks", ...overrides } }; }

describe("Home Trajectory Hero contract", () => {
  it("renders the polished current Founder presentation model", () => expect(mapHomeHero({ activeGoal: goal, evaluation: evaluation() })).toEqual(expect.objectContaining({ goalLabel: "Visible Abs at Rest", headline: "Final stretch.", supportLine: "You're close—keep executing the plan.", confidence: 97, projectedFinish: "Jul 20-26", daysRemaining: "1-2 weeks" })));
  it("shares projection identity and presentation values without recalculation", () => { const first = mapHomeHero({ activeGoal: goal, evaluation: evaluation() }); const changed = mapHomeHero({ activeGoal: goal, evaluation: evaluation({ id: "projection-two", projectedFinish: "Jul 27-Aug 2", daysRemaining: "2-3 weeks" }) }); expect(first.projectionId).toBe("projection-one"); expect(changed).toEqual(expect.objectContaining({ projectionId: "projection-two", projectedFinish: "Jul 27-Aug 2", daysRemaining: "2-3 weeks" })); });
  it("removes internal stage and clinical range language", () => expect(JSON.stringify(mapHomeHero({ activeGoal: goal, evaluation: evaluation() }))).not.toMatch(/Visual confirmation developing|estimated body composition is already in range/i));
  it("uses progress language while the numerical target is still progressing", () => expect(mapHomeHero({ activeGoal: goal, evaluation: evaluation({ currentCompletionStage: "progressing_toward_numerical_target", numericalThresholdStatus: "not_reached" }) })).toEqual(expect.objectContaining({ headline: "On track.", supportLine: "Keep executing the plan.", projectedFinish: "Jul 20-26", daysRemaining: "1-2 weeks", confidence: 97 })));
  it("maps confirmed and unavailable stages to non-empty natural copy", () => { expect(mapHomeHero({ activeGoal: goal, evaluation: evaluation({ currentCompletionStage: "goal_visually_confirmed" }) })).toEqual(expect.objectContaining({ headline: "Goal achieved.", supportLine: "Your progress is confirmed." })); expect(mapHomeHero({ activeGoal: goal, evaluation: null })).toEqual(expect.objectContaining({ headline: "Progress update.", supportLine: "More evidence is needed to update the outlook.", projectedFinish: "Unavailable", daysRemaining: "Unavailable", confidence: null })); });
  it("contains no evidence list, raw estimate, or technical projection mechanics", () => expect(JSON.stringify(mapHomeHero({ activeGoal: goal, evaluation: evaluation() }))).not.toMatch(/bullets|bodyFat|assumptions|evidenceId|stability bucket/i));
});
