import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach,describe,expect,it } from "vitest";
import { createFounderStoreUnitOfWork } from "../../data/repositories/FounderStoreUnitOfWork";
import { buildGoalEditDraft,selectGoalEditSections,updateGoalEditWorkingPlan } from "./GoalEditDraftService";
import { createGoalPlanUpdateCommand,createGoalPlanUpdateService,GOAL_PLAN_UPDATE_COMMAND_VERSION } from "./GoalPlanUpdateService";
import { interpretGoalOutcome } from "./GoalOutcomeInterpretationService";

const dirs=[];afterEach(()=>dirs.splice(0).forEach(dir=>fs.rmSync(dir,{recursive:true,force:true})));
function store(){return{version:"test",revision:2,updatedAt:"2026-07-20",user:{id:"user"},goals:[{id:"goal",userId:"user",title:"Build Lean Mass",type:"build_lean_mass",primary:true,status:"active",updatedAt:"2026-07-20",guardrails:[{id:"protect",text:"Protect body composition",accepted:true}],phases:[{id:"p1",name:"Establish Maintenance",status:"active",order:0,timingMode:"completion_criteria",successCriteria:[],guardrails:[],transitionPolicy:"manual_review"}]}],protocols:[{id:"protocol"}],protocolVersions:[],energyStrategyLinks:[],executionItems:[],reminders:[],dailyBriefings:[],evidencePackages:[],canonicalEvidenceObjects:[],evidenceReviews:[],progressPhotos:[],dexaScans:[],goalTransitionDrafts:[],goalProtocolTransitionDrafts:[]}}

describe("overall destination isolated round trip",()=>{
 it("commits and reloads the complete goal-owned target without changing phases or protocols",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"overall-goal-"));dirs.push(dir);const filePath=path.join(dir,"runtime-store.json"),liveStore=store(),before=structuredClone(liveStore);fs.writeFileSync(filePath,JSON.stringify(liveStore));const now=()=>new Date("2026-07-21T00:00:00Z");const service=createGoalPlanUpdateService({runtimeStorePath:filePath,liveStore,readPersistedStore:()=>JSON.parse(fs.readFileSync(filePath,"utf8")),now,createTokenId:()=>"token",createUnitOfWork:options=>createFounderStoreUnitOfWork({...options,createCommitId:()=>"commit",createTransactionId:()=>"tx"})});let draft=selectGoalEditSections(buildGoalEditDraft(liveStore.goals[0],{now:now()}),["target_timeline"]);const target={...interpretGoalOutcome("Build 10 lb of lean mass").target,targetDate:"2026-10-31"};draft=updateGoalEditWorkingPlan(draft,{primaryOutcome:target.description,target,timeline:{mode:"target_date",startDate:"2026-07-20",targetDate:"2026-10-31",duration:null,eventDate:null}});const review=await service.createFinalReview({founderUserId:"user",draft});expect(review.status).toBe("ready");const command=createGoalPlanUpdateCommand({commandVersion:GOAL_PLAN_UPDATE_COMMAND_VERSION,sourceGoalId:"goal",expectedSourceRevision:draft.sourceRevision,originalPlanFingerprint:review.token.originalPlanFingerprint,proposedCanonicalPlan:draft.workingPlan,approvedDiff:review.diff,finalReviewToken:review.token.id,draftId:draft.id,requestedAt:"2026-07-21T00:00:00Z"});const result=await service.commit(command,{founderUserId:"user"});expect(result).toMatchObject({status:"committed",previousRevision:2,committedRevision:3});const persisted=JSON.parse(fs.readFileSync(filePath,"utf8")),reloaded=buildGoalEditDraft(persisted.goals[0]);expect(reloaded.workingPlan).toMatchObject({primaryOutcome:"Build 10 lb of lean mass",target,timeline:{startDate:"2026-07-20",targetDate:"2026-10-31"}});expect(persisted.goals[0].phases).toEqual(before.goals[0].phases);expect(persisted.protocols).toEqual(before.protocols)});
 it("blocks final review and preserves the draft when the selected destination is incomplete",async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"overall-goal-incomplete-"));dirs.push(dir);const filePath=path.join(dir,"runtime-store.json"),liveStore=store();fs.writeFileSync(filePath,JSON.stringify(liveStore));const service=createGoalPlanUpdateService({runtimeStorePath:filePath,liveStore,readPersistedStore:()=>JSON.parse(fs.readFileSync(filePath,"utf8"))});let draft=selectGoalEditSections(buildGoalEditDraft(liveStore.goals[0]),["target_timeline"]);draft=updateGoalEditWorkingPlan(draft,{primaryOutcome:"Build lean mass"});const review=await service.createFinalReview({founderUserId:"user",draft});expect(review).toMatchObject({status:"rejected",reasonCode:"OVERALL_GOAL_INCOMPLETE",draftPreserved:true});expect(liveStore.revision).toBe(2)});
});
