import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe,expect,it } from "vitest";
import { buildPeptideExecutionDraftFromFormData,classifyPeptideExecutionState,createPeptideExecutionHydrationModel,createPeptideExecutionManagementService,formatPeptideExecutionSummary,PeptideExecutionState,resolvePeptideDose,validatePeptideExecutionDraft } from "./PeptideExecutionManagementService";

describe("shared peptide Execution",()=>{
  it.each([["Retatrutide",["thursday"]],["Tesamorelin",["sunday","monday","tuesday","wednesday","thursday"]]])("uses one service for %s and preserves the stable legacy record on a schedule-only save",async(name,days)=>{const fixture=setup(name,days,true);const result=await fixture.service.save(command(fixture,{expectedRevision:1,draft:draft(days,{timeline:[]})}));expect(result).toMatchObject({outcome:"success",created:false,executionId:`execution_${name.toLowerCase()}`});expect(fixture.live.executionItems).toHaveLength(1);expect(fixture.live.executionItems[0]).toMatchObject({type:"peptide",protocolRootId:"peptide",executionRevision:2,timeline:[]});});
  it("creates then updates one protocol-root-owned record",async()=>{const fixture=setup("Retatrutide",["thursday"]);const created=await fixture.service.save(command(fixture));const updated=await fixture.service.save(command(fixture,{expectedRevision:1,draft:draft(["thursday"],{priority:"high"})}));expect(created).toMatchObject({outcome:"success",created:true});expect(updated).toMatchObject({outcome:"success",created:false,executionId:created.executionId});expect(fixture.live.executionItems).toHaveLength(1);});
  it("accepts an empty timeline but rejects invalid configured phases",()=>{expect(validatePeptideExecutionDraft(draft(["thursday"],{timeline:[]}))).toEqual([]);expect(validatePeptideExecutionDraft(draft(["thursday"],{timeline:[phase("2026-07-01",null),phase("2026-07-08",null)]}))).toContain("Only the final dosing phase can continue until changed.");expect(validatePeptideExecutionDraft(draft(["thursday"],{timeline:[phase("2026-07-01","2026-07-10"),phase("2026-07-10",null)]}))).toContain("Dosing phases cannot overlap.");});
  it("resolves current and next doses using an explicit local date",()=>{const item=draft(["thursday"],{timeline:[phase("2026-07-01","2026-07-25","2"),phase("2026-07-26",null,"1.5")]});expect(resolvePeptideDose(item,"2026-07-25")).toMatchObject({current:{dose:{amount:"2"}},next:{dose:{amount:"1.5"}}});expect(formatPeptideExecutionSummary(item,"2026-07-25")).toBe("Thu · 9:45 PM · 2 mg");});
  it("hydrates authoritative schedules but does not manufacture a timeline",()=>{const model=createPeptideExecutionHydrationModel({protocol:{startDate:"2026-05-24",schedule:{type:"weekly_days",daysOfWeek:["sunday","monday"],timeOfDay:"night",timingContext:"fasted_before_bed"}}});expect(model).toMatchObject({configured:false,draft:{cadence:{type:"specific_days"},preferredSchedule:{daysOfWeek:["sunday","monday"],timeOfDay:"before_bed"},timingContext:"fasted_before_bed",timeline:[]}});});
  it.each([
    ["Retatrutide","weekly",["thursday"],"2026-05-21"],
    ["Tesamorelin","specific_days",["sunday","monday","tuesday","wednesday","thursday"],"2026-05-24"],
  ])("hydrates the compatible legacy %s record with protocol context",(name,cadence,days,startDate)=>{const protocol={name,startDate,schedule:{type:name==="Retatrutide"?"weekly":"weekly_days",daysOfWeek:days,timeOfDay:"night",timingContext:"fasted_before_bed"}};const executionItem={id:`execution_${name.toLowerCase()}`,type:"protocol",title:name,cadence:{type:name==="Retatrutide"?"weekly":"specific_weekdays"},preferredSchedule:{daysOfWeek:days,timeOfDay:"21:45"},reminderPreference:"in_app",notes:"",timeline:[]};expect(createPeptideExecutionHydrationModel({executionItem,protocol})).toMatchObject({configured:false,executionRevision:1,draft:{cadence:{type:cadence},preferredSchedule:{daysOfWeek:days,timeOfDay:"21:45",startDate},timingContext:"fasted_before_bed",timeline:[]}});});
  it("rejects unchanged and stale commands without writes",async()=>{const fixture=setup("Retatrutide",["thursday"]);await fixture.service.save(command(fixture));const before=fs.readFileSync(fixture.file,"utf8");expect((await fixture.service.save(command(fixture,{expectedRevision:1}))).outcome).toBe("unchanged");expect((await fixture.service.save(command(fixture,{expectedRevision:0,draft:draft(["thursday"],{priority:"high"})}))).outcome).toBe("version_conflict");expect(fs.readFileSync(fixture.file,"utf8")).toBe(before);});
  it("rolls back an injected persistence failure exactly",async()=>{const fixture=setup("Retatrutide",["thursday"],false,{afterWrite(){throw new Error("fail");}});const before=fs.readFileSync(fixture.file,"utf8");expect((await fixture.service.save(command(fixture))).outcome).toBe("persistence_failure");expect(fs.readFileSync(fixture.file,"utf8")).toBe(before);expect(fixture.live.executionItems).toEqual([]);});
  it.each(["Retatrutide","Tesamorelin"])("round-trips configured %s phases through one JSON parser",async(name)=>{const days=name==="Retatrutide"?["thursday"]:["sunday","monday","tuesday","wednesday","thursday"];const fixture=setup(name,days,true);const phases=[phase("2026-07-01","2026-07-07","0.5"),phase("2026-07-08",null,"1")];const form=formData(days,phases);const parsed=buildPeptideExecutionDraftFromFormData(form);expect(parsed.timeline).toEqual(phases);expect(validatePeptideExecutionDraft(parsed)).toEqual([]);const result=await fixture.service.save(command(fixture,{expectedRevision:1,draft:parsed}));expect(result).toMatchObject({outcome:"success",executionId:`execution_${name.toLowerCase()}`});expect(fixture.live.executionItems[0].timeline).toEqual(phases);const hydrated=createPeptideExecutionHydrationModel({executionItem:fixture.live.executionItems[0],protocol:fixture.live.protocols[0]});expect(hydrated.draft.timeline).toEqual(phases);});
  it("distinguishes omitted, explicit empty, and configured replacement timelines",async()=>{const fixture=setup("Retatrutide",["thursday"],true);const original=fixture.live.executionItems[0].timeline;const preserved=await fixture.service.save(command(fixture,{expectedRevision:1,draft:draft(["thursday"],{timelineOperation:"preserve",timeline:[],priority:"high"})}));expect(preserved.outcome).toBe("success");expect(fixture.live.executionItems[0].timeline).toEqual(original);const replacedPhases=[phase("2026-08-01",null,"1.5")];const replaced=await fixture.service.save(command(fixture,{expectedRevision:2,draft:draft(["thursday"],{timelineOperation:"replace",timeline:replacedPhases})}));expect(replaced.outcome).toBe("success");expect(fixture.live.executionItems[0].timeline).toEqual(replacedPhases);const cleared=await fixture.service.save(command(fixture,{expectedRevision:3,draft:draft(["thursday"],{timelineOperation:"replace",timeline:[]})}));expect(cleared.outcome).toBe("success");expect(fixture.live.executionItems[0].timeline).toEqual([]);});
  it.each([
    ["one closed",[phase("2026-07-01","2026-07-07")],[]],
    ["one open",[phase("2026-07-01",null)],[]],
    ["multiple closed",[phase("2026-07-01","2026-07-07"),phase("2026-07-08","2026-07-14")],[]],
    ["last open",[phase("2026-07-01","2026-07-07"),phase("2026-07-08",null)],[]],
    ["shared boundary overlap",[phase("2026-07-01","2026-07-08"),phase("2026-07-08",null)],["Dosing phases cannot overlap."]],
    ["after open",[phase("2026-07-01",null),phase("2026-07-08",null)],["Only the final dosing phase can continue until changed.","Dosing phases cannot overlap."]],
    ["missing dose",[{...phase("2026-07-01",null),dose:{amount:"",unit:"mg"}}],["Add a dose and unit for every phase."]],
    ["missing unit",[{...phase("2026-07-01",null),dose:{amount:"1",unit:""}}],["Add a dose and unit for every phase."]],
    ["invalid start",[phase("2026-02-30",null)],["Review each dosing phase and try again."]],
    ["invalid end",[phase("2026-07-10","2026-07-09")],["Check the start and end dates for each phase."]],
    ["invalid order",[phase("2026-07-08","2026-07-14"),phase("2026-07-01","2026-07-07")],["Arrange dosing phases in chronological order."]],
    ["duplicate",[phase("2026-07-01","2026-07-07"),phase("2026-07-01","2026-07-07")],["Review each dosing phase and try again."]],
  ])("validates the %s timeline case",(_label,timeline,expected)=>{const errors=validatePeptideExecutionDraft(draft(["thursday"],{timelineOperation:"replace",timeline}));expected.forEach((message)=>expect(errors).toContain(message));if(!expected.length)expect(errors).toEqual([]);});
  it("preserves date-only strings at timezone boundaries",()=>{const phases=[phase("2026-03-08","2026-03-14"),phase("2026-11-01",null)];const parsed=buildPeptideExecutionDraftFromFormData(formData(["thursday"],phases));expect(parsed.timeline.map((item)=>[item.startDate,item.endDate])).toEqual([["2026-03-08","2026-03-14"],["2026-11-01",null]]);});
  it("rejects malformed JSON as a typed validation result",async()=>{const fixture=setup("Retatrutide",["thursday"],true);const form=formData(["thursday"],[]);form.set("timelineJson","{bad");const result=await fixture.service.save(command(fixture,{expectedRevision:1,draft:buildPeptideExecutionDraftFromFormData(form)}));expect(result).toMatchObject({outcome:"invalid",committed:false,reason:"Review each dosing phase and try again."});});
  it.each(["Retatrutide","Tesamorelin"])("supports sequential %s timeline replacements using each authoritative revision",async(name)=>{const days=name==="Retatrutide"?["thursday"]:["sunday","monday","tuesday","wednesday","thursday"];const fixture=setup(name,days,true);fixture.live.executionItems[0].timeline=[];fs.writeFileSync(fixture.file,JSON.stringify(fixture.live));const stableId=fixture.live.executionItems[0].id;let revision=1;for(const timeline of [[phase("2026-07-01","2026-07-07")],[phase("2026-07-01","2026-07-07"),phase("2026-07-08","2026-07-14")],[phase("2026-07-01","2026-07-07"),phase("2026-07-08","2026-07-14"),phase("2026-07-15",null)]]){const parsed=buildPeptideExecutionDraftFromFormData(formData(days,timeline));const saved=await fixture.service.save(command(fixture,{expectedRevision:revision,draft:parsed}));revision+=1;expect(saved).toMatchObject({outcome:"success",executionId:stableId,executionRevision:revision});const authoritative=fixture.live.executionItems[0];expect(authoritative.timeline).toEqual(timeline);expect(createPeptideExecutionHydrationModel({executionItem:authoritative,protocol:fixture.live.protocols[0]}).draft.timeline).toEqual(timeline);}expect(fixture.live.executionItems).toHaveLength(1);});
  it("rejects a phase after Until changed, then succeeds after closing the previous phase",async()=>{const fixture=setup("Retatrutide",["thursday"],true);fixture.live.executionItems[0].timeline=[phase("2026-07-01",null)];fs.writeFileSync(fixture.file,JSON.stringify(fixture.live));const invalid=[phase("2026-07-01",null),phase("2026-07-08",null)];const rejected=await fixture.service.save(command(fixture,{expectedRevision:1,draft:draft(["thursday"],{timeline:invalid})}));expect(rejected).toMatchObject({outcome:"invalid",committed:false,reason:"Only the final dosing phase can continue until changed."});expect(fixture.live.executionItems[0].executionRevision).toBe(1);const valid=[phase("2026-07-01","2026-07-07"),phase("2026-07-08",null)];const saved=await fixture.service.save(command(fixture,{expectedRevision:1,draft:draft(["thursday"],{timeline:valid})}));expect(saved).toMatchObject({outcome:"success",executionRevision:2});expect(fixture.live.executionItems[0].timeline).toEqual(valid);});
  it("classifies unconfigured, legacy-compatible, canonical, and ambiguous states",()=>{const protocol={id:"peptide",userId:"founder",name:"Shared Peptide",category:"peptide"};expect(classifyPeptideExecutionState({protocol,executionItems:[]}).state).toBe(PeptideExecutionState.UNCONFIGURED);const legacy={id:"legacy",userId:"founder",type:"protocol",title:"Shared Peptide"};expect(classifyPeptideExecutionState({protocol,executionItems:[legacy]})).toMatchObject({state:PeptideExecutionState.LEGACY_COMPATIBLE,record:legacy});const canonical={...legacy,type:"peptide",protocolRootId:"peptide",executionRevision:1,cadence:{type:"weekly"},preferredSchedule:{},timeline:[]};expect(classifyPeptideExecutionState({protocol,executionItems:[canonical]}).state).toBe(PeptideExecutionState.CANONICAL);expect(classifyPeptideExecutionState({protocol,executionItems:[legacy,canonical]}).state).toBe(PeptideExecutionState.INVALID);});
  it("canonicalizes a Tesamorelin-shaped legacy record with one open-ended phase, then detects no changes",async()=>{const fixture=setup("Tesamorelin",["sunday","monday","tuesday","wednesday","thursday"],true);fixture.live.protocols[0].startDate="2026-05-24";fixture.live.protocols[0].schedule={type:"weekly_days",daysOfWeek:fixture.days,timeOfDay:"night",timingContext:"fasted_before_bed"};fixture.live.executionItems[0].timeline=undefined;delete fixture.live.executionItems[0].executionRevision;fs.writeFileSync(fixture.file,JSON.stringify(fixture.live));const hydration=createPeptideExecutionHydrationModel({executionItem:fixture.live.executionItems[0],protocol:fixture.live.protocols[0]});const timeline=[phase("2026-05-24",null)];const requested={...hydration.draft,timelineOperation:"replace",timeline};const saved=await fixture.service.save(command(fixture,{expectedRevision:1,draft:requested}));expect(saved).toMatchObject({outcome:"success",created:false,executionId:"execution_tesamorelin",executionRevision:1});expect(fixture.live.executionItems).toHaveLength(1);expect(fixture.live.executionItems[0]).toMatchObject({id:"execution_tesamorelin",type:"peptide",protocolRootId:"peptide",executionRevision:1,preferredSchedule:{startDate:"2026-05-24",timeOfDay:"21:45"},timingContext:"fasted_before_bed",timeline});expect(classifyPeptideExecutionState({protocol:fixture.live.protocols[0],executionItems:fixture.live.executionItems}).state).toBe(PeptideExecutionState.CANONICAL);const unchanged=await fixture.service.save(command(fixture,{expectedRevision:1,draft:requested}));expect(unchanged).toMatchObject({outcome:"unchanged",committed:false});});
});
function setup(name,days,legacy=false,faults={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"peptide-execution-"));const file=path.join(dir,"runtime.json");const live={version:"test",revision:0,protocols:[{id:"peptide",userId:"founder",name,category:"peptide",status:"active",currentGoalIds:["goal"]}],executionItems:legacy?[{id:`execution_${name.toLowerCase()}`,userId:"founder",type:"protocol",title:name,cadence:{type:"specific_weekdays"},preferredSchedule:{daysOfWeek:days,timeOfDay:"21:45"},reminderPreference:"in_app",notes:"legacy",timeline:[phase("2026-05-01",null)],executionRevision:1}]:[]};fs.writeFileSync(file,JSON.stringify(live));return{file,live,days,service:createPeptideExecutionManagementService({runtimeStorePath:file,liveStore:live,faults,now:()=>new Date("2026-07-25T12:00:00Z")})};}
function command(fixture,overrides={}){return{protocolId:"peptide",userId:"founder",expectedRevision:null,draft:draft(fixture.days),author:{type:"user",id:"founder"},...overrides};}
function draft(days,overrides={}){return{cadence:{type:days.length===1?"weekly":"specific_days"},preferredSchedule:{daysOfWeek:days,timeOfDay:"21:45",startDate:"2026-05-01",endDate:null},timingContext:"fasted_before_bed",reminderPreference:"remind",priority:"normal",notes:"legacy",timeline:[phase("2026-05-01",null)],...overrides};}
function phase(startDate,endDate,amount="0.5"){return{startDate,endDate,dose:{amount,unit:"mg"},notes:""};}
function formData(days,timeline){const form=new FormData();Object.entries({cadence:days.length===1?"weekly":"specific_days",days:days.join(","),timing:"specific",specificTime:"21:45",startDate:"2026-05-01",endDate:"",timingContext:"fasted_before_bed",reminderPreference:"remind",priority:"normal",notes:"",timelineOperation:"replace",timelineJson:JSON.stringify(timeline)}).forEach(([key,value])=>form.set(key,value));return form;}
