import { describe,expect,it } from "vitest";
import { classifyPhotoAnalysis,composePhotoEventNarrative,deriveExecutionSupport } from "./PhotoEventNarrativeService";

const view=(poseId,label,findings,mode="openai")=>({canonicalViewId:`view_${poseId}`,poseId,label,imageHref:`/${poseId}.jpg`,previousImageHref:`/old-${poseId}.jpg`,comparison:{previousDate:poseId==="front-relaxed"?"2026-07-03":"2026-07-05"},comparisonStatus:"comparable",analysisMode:mode,structuredFindings:findings.map((change)=>({change})),observedChanges:[],conditionDifferences:poseId==="front-relaxed"?["post workout"]:[]});
const session={id:"photo_session_user_founder_001_2026-07-11",sourceMode:"canonical",captureDate:"2026-07-11",date:"Jul 11",completionLabel:"3/3 complete",weight:"166.8 lb",sessionConditions:{postWorkout:true,fasted:false},synthesis:{id:"stable_synthesis",source:"embedded_photo_session",observations:[{change:"Waist tighter"}]},views:[view("front-relaxed","Front Relaxed",["Your waist looks a little tighter.","Waist appears modestly tighter.","Chest fullness appears maintained."]),view("back-relaxed","Rear Relaxed",["Overall shape appears stable."]),view("back-flexed","Rear Flexed",["Fallback mode cannot inspect visual change."],"fallback")]};

describe("PhotoEventNarrativeService",()=>{
  it("creates one five-card narrative from three canonical views",()=>{const result=composePhotoEventNarrative({session,goal:{title:"Visible Abs at Rest"},milestone:{date:"2026-07-18",label:"DEXA"},generatedAt:"2026-07-12T00:00:00Z"});expect(result.photoSessionId).toBe(session.id);expect(result.activeViews).toHaveLength(3);expect(Object.keys(result.cardContent)).toEqual(["hero","snapshot","progress","interpretation","coachInsight"]);expect(result.overallSummary).toBe("Waist appears modestly tighter.");expect(JSON.stringify(result)).not.toMatch(/Fallback mode|sourceEvidenceIds|analysisLookupPath/);expect(result.provenance.synthesisId).toBe("stable_synthesis");});
  it("gates fallback analyses from visible findings",()=>{expect(classifyPhotoAnalysis({analysisMode:"fallback"})).toBe("deterministic_fallback");const result=composePhotoEventNarrative({session});expect(result.activeViews[2].findings).toEqual([]);});
  it("keeps coaching in the coaching card",()=>{const result=composePhotoEventNarrative({session});expect(result.cardContent.interpretation.paragraphs.join(" ")).not.toMatch(/stay the course|keep the next/i);expect(result.cardContent.coachInsight.body).toMatch(/stay the course|keep the next/i);});
  it("keeps Snapshot descriptive and supporting evidence subordinate",()=>{const result=composePhotoEventNarrative({session,latestDexa:{measuredAt:"2026-04-01",bodyFatPercentage:{value:14}}});expect(JSON.stringify(result.cardContent.snapshot)).not.toMatch(/progress|DEXA|fat loss|maintained/i);expect(result.cardContent.interpretation.paragraphs[0]).toMatch(/front photos/i);expect(result.cardContent.interpretation.paragraphs[1]).toMatch(/weight trend.*DEXA/i);});
  it("uses cautious Hero language and distinct card contributions",()=>{const result=composePhotoEventNarrative({session});expect(result.cardContent.hero.title).toMatch(/suggest continued progress/i);expect(result.cardContent.hero.body).toMatch(/tighter waist/i);expect(result.cardContent.interpretation.paragraphs.join(" ")).not.toMatch(/tighter waist/i);expect(result.cardContent.coachInsight.body).not.toMatch(/tighter waist|upper-body muscle has been maintained/i);});
  it("includes only materially available execution support",()=>{const items=[...Array.from({length:3},(_,i)=>({evidence_type:"training",lastObservedAt:`2026-07-0${8+i}`,quality:{status:"active"},payload:{quality:{status:"complete"}}})),...Array.from({length:4},(_,i)=>({evidence_type:"activity_day",lastObservedAt:`2026-07-0${7+i}`,quality:{status:"active"},payload:{quality:{status:"complete"}}}))];expect(deriveExecutionSupport(items,"2026-07-11")).toEqual({training:"Resistance training was consistent through the week.",activity:"Activity remained sustained through the week."});expect(deriveExecutionSupport([],"2026-07-11")).toEqual({});});
  it("keeps photos first when execution support is present",()=>{const result=composePhotoEventNarrative({session,executionSupport:{training:"Resistance training was consistent through the week.",activity:"Activity remained sustained through the week."}});expect(result.cardContent.interpretation.paragraphs[0]).toMatch(/^The front photos/);expect(result.cardContent.interpretation.paragraphs[1]).toMatch(/weight trend.*resistance training.*activity/i);});
});
