import { describe, expect, it } from "vitest";
import { composeWeeklyNarrative, createWeeklyNarrativeService } from "./WeeklyNarrativeService";

const window={id:"weekly:2026-07-05:2026-07-11:America/Los_Angeles",startDate:"2026-07-05",endDate:"2026-07-11"};
const wrap=(id,type,date,payload)=>({canonicalId:id,evidence_type:type,lastObservedAt:date,quality:{status:"active"},payload:{id,evidence_type:type,observed_at:date,quality:{status:"complete"},...payload}});
const training=[5,7,10].map((day)=>wrap(`training-${day}`,"training",`2026-07-${String(day).padStart(2,"0")}`,{metadata:{activity_type:"Traditional Strength Training"},exercises:[{name:"Cable Rope Pushdowns",sets:[{reps:12,weight:100}]}]}));
const activity=[900,1000,950,1100,1025,975,1050].map((calories,index)=>wrap(`activity-${index}`,"activity_day",`2026-07-${String(5+index).padStart(2,"0")}`,{daily_activity:{move_calories:calories}}));
const nutrition=[9,10].map((day)=>wrap(`nutrition-${day}`,"nutrition",`2026-07-${String(day).padStart(2,"0")}`,{metadata:{completeness:"complete"},daily_totals:{calories:1950,protein_g:180}}));
const canonical=[...training,...activity,...nutrition,wrap("photos","photo_session","2026-07-11",{})];
const weights=[{measuredAt:"2026-07-01",weight:{value:169}},{measuredAt:"2026-07-05",weight:{value:168}},{measuredAt:"2026-07-11",weight:{value:166.8}}];
const photoEvent={id:"event_photo",trigger:{evidenceId:"photo_session_1"},briefing:{photoEventNarrative:{eventDate:"2026-07-11",activeViews:[{poseId:"front-relaxed",imageHref:"/front.jpg"}],overallSummary:"Waist appears tighter."}}};
const prReport={generated_at:"2026-07-12",exerciseObservations:[{exercise:{key:"cable_pushdown",name:"Cable Pushdown"},status:"improving",evidence_date_range:{end:"2026-07-10"},explanation_data:{pr_detection:{detected:true},volume_trend:{direction:"up"}}}]};
const compose=(overrides={})=>composeWeeklyNarrative({window,canonicalObjects:canonical,weights,photoEvent,goal:{title:"Visible Abs at Rest"},activityTarget:7000,trainingPerformance:prReport,generatedAt:"2026-07-12T12:00:00Z",...overrides});

describe("Weekly Narrative Intelligence V5.1",()=>{
  it("builds the approved five cards without confidence or software jargon",()=>{const n=compose();expect(Object.keys(n.cards)).toEqual(["hero","snapshot","progress","interpretation","coachInsight"]);expect(n.provenance.version).toBe("weekly_narrative_v5_1");expect(n.cards.hero.confidence).toBeUndefined();expect(JSON.stringify(n.cards)).not.toMatch(/visual movement|front-view change|\bsignals?\b|trajectory|coherent story|next adjustment/i);expect(n.cards.hero.highlights).toHaveLength(4);});
  it("maps supported weekly evidence into typed Hero tiles without manufacturing filler",()=>{const hero=compose().cards.hero;expect(hero.highlightTiles.map((item)=>item.domain)).toEqual(["photos","weight","training","energy_balance"]);expect(hero.highlightTiles).toHaveLength(4);const sparse=compose({canonicalObjects:[],weights:[],photoEvent:null,trainingPerformance:{exerciseObservations:[]}}).cards.hero;expect(sparse.highlightTiles).toEqual([]);expect(sparse.milestone).toBeNull();});
  it("adds a higher-order milestone only when the week supports it",()=>{expect(compose().cards.hero.milestone).toEqual({label:"Weekly Milestone",value:"Execution and outcome remained aligned across the full week."});const partial=compose({canonicalObjects:training,weights:[],photoEvent:null,trainingPerformance:{exerciseObservations:[]}}).cards.hero;expect(partial.highlightTiles).toHaveLength(1);expect(partial.milestone).toBeNull();});
  it("speaks to the athlete and recommends staying the course",()=>{const n=compose();expect(n.cards.hero.body).toMatch(/^Your /);expect(n.cards.interpretation.opening).toMatch(/^This week your /);expect(n.cards.interpretation.domains.filter((item)=>item.domain!=="photos").every((item)=>/\bYou\b|\bYour\b/.test(`${item.highlight} ${item.insight}`))).toBe(true);expect(n.cards.coachInsight.celebration).toMatch(/^This was a strong week/);expect(n.cards.coachInsight.preparation).toMatch(/Stay the course.*DEXA.*before making any changes/i);});
  it("keeps Snapshot semantics grounded in days and true sessions",()=>{const facts=compose().cards.snapshot.facts;expect(facts).toEqual(expect.arrayContaining([{label:"Training Days",value:"3 training days"},{label:"Activity Days",value:"7 complete days"},{label:"Photos",value:"1 session"},{label:"Nutrition",value:"2 of 7 days complete"}]));});
  it("summarizes Weekly Progress Photos without replaying the event",()=>{const n=compose();expect(n.cards.progress.photo.summary).toMatch(/waist tightening.*rear views/i);expect(n.cards.progress.photo.href).toBe("/briefings/photo/photo_session_1");expect(JSON.stringify(n)).not.toMatch(/comparisonBullets|previousImageHref/);});
  it("surfaces only supported PR or overload claims",()=>{const n=compose();const section=n.cards.interpretation.domains.find((item)=>item.domain==="training");expect(section.highlight).toMatch(/Cable Rope Pushdowns.*PR/);expect(section.insight).toMatch(/lean mass/i);const unsupported=compose({trainingPerformance:{exerciseObservations:[]}});expect(JSON.stringify(unsupported.cards)).not.toMatch(/new performance PR|progressive overload/);});
  it("combines canonical ActivityDays and limited Nutrition into Energy Balance",()=>{const section=compose().cards.interpretation.domains.find((item)=>item.domain==="energy_balance");expect(section.label).toBe("🔥 Energy Balance");expect(section.highlight).toMatch(/7,000 active calories.*7 complete days.*weekly target/i);expect(section.insight).toMatch(/Only 2 complete nutrition days.*cut/i);const progress=compose().cards.progress.activity;expect(progress).toMatchObject({completedDays:7,totalActiveCalories:7000,dailyAverage:1000,weeklyTarget:7000,difference:0});});
  it("provides Highlight, Insight, cross-domain synthesis, and recognition-led coaching",()=>{const n=compose();for(const item of n.cards.interpretation.domains){expect(item.highlight).toBeTruthy();expect(item.insight).toBeTruthy();}expect(n.cards.interpretation.synthesis).toMatch(/You continued losing weight.*waist.*resistance performance.*activity target/i);expect(n.cards.coachInsight.celebration).toMatch(/biggest win/i);expect(n.cards.coachInsight.explanation).toMatch(/resistance training.*activity/i);expect(n.cards.coachInsight.preparation).toMatch(/July 18 DEXA/i);});
  it("persists only through explicit generation and keeps Preview non-destructive",async()=>{const artifacts=[];const repositories={users:{getCurrentUser:async()=>({timeZone:"America/Los_Angeles"})},canonicalEvidence:{listCanonicalEvidenceObjects:async()=>canonical},weights:{listWeightEntries:async()=>weights},dailyBriefings:{listDailyBriefings:async()=>artifacts,getLatestWeeklyBriefing:async()=>artifacts.at(-1)??null,createDailyBriefing:async(a)=>{artifacts.push(a);return a;}},goals:{getActiveGoal:async()=>({title:"Visible Abs at Rest"})}};const service=createWeeklyNarrativeService({repositories,now:()=>new Date("2026-07-12T18:00:00Z")});const first=await service.generate({userId:"user",reason:"test"});expect(first.briefing.version).toBe("weekly_narrative_v5_1");expect(artifacts).toHaveLength(1);await service.preview({userId:"user"});expect(artifacts).toHaveLength(1);expect(await service.getLatest({userId:"user"})).toBe(first);});
});
