import {describe,expect,it} from "vitest";
import {composeWeeklyNarrative,createWeeklyNarrativeService} from "./WeeklyNarrativeService";

const window={id:"weekly:2026-07-05:2026-07-11:America/Los_Angeles",startDate:"2026-07-05",endDate:"2026-07-11"};
const canonical=[...Array.from({length:3},(_,i)=>({canonicalId:`training_${i}`,evidence_type:"training",lastObservedAt:`2026-07-${String(8+i).padStart(2,"0")}`,quality:{status:"active"},payload:{quality:{status:"complete"}}})),...Array.from({length:4},(_,i)=>({canonicalId:`activity_${i}`,evidence_type:"activity_day",lastObservedAt:`2026-07-${String(7+i).padStart(2,"0")}`,quality:{status:"active"},payload:{quality:{status:"complete"}}})),{canonicalId:"photos",evidence_type:"photo_session",lastObservedAt:"2026-07-11",quality:{status:"active"},payload:{}}];
const weights=[{measuredAt:"2026-07-05",weight:{value:168,unit:"lb"}},{measuredAt:"2026-07-11",weight:{value:166.8,unit:"lb"}}];
const photoEvent={id:"event_photo",trigger:{evidenceId:"photo_session_1"},briefing:{photoEventNarrative:{eventDate:"2026-07-11",overallSummary:"Waist appears tighter.",cardContent:{hero:{title:"Today’s photos suggest continued progress toward visible abs.",body:"The rear views suggest upper-body muscle has been maintained."}}}}};

describe("WeeklyNarrativeService",()=>{
  it("builds one narrative with exactly five shared cards",()=>{const n=composeWeeklyNarrative({window,canonicalObjects:canonical,weights,photoEvent,goal:{title:"Visible Abs at Rest"},generatedAt:"2026-07-12T12:00:00Z"});expect(n.weekId).toBe(window.id);expect(Object.keys(n.cards)).toEqual(["hero","snapshot","progress","interpretation","coachInsight"]);expect(n.cards.hero.title).toMatch(/cut is continuing/i);expect(n.cards.snapshot.facts).toEqual(expect.arrayContaining([expect.objectContaining({label:"Training",value:"3 training days"}),expect.objectContaining({label:"Average weight"})]));expect(n.cards.hero.highlights).toHaveLength(3);expect(n.cards.hero.confidence).toBeGreaterThan(0);});
  it("summarizes rather than replaying the Photo Event",()=>{const n=composeWeeklyNarrative({window,canonicalObjects:canonical,weights,photoEvent});const photo=n.cards.progress.items.find((item)=>item.domain==="Photos");expect(photo.href).toBe("/briefings/photo/photo_session_1");expect(n.cards.progress.items.map((item)=>item.domain)).toEqual(["Photos","Weight"]);expect(JSON.stringify(n)).not.toMatch(/activeViews|comparisonBullets|previousImageHref/);});
  it("keeps recommendations only in Coach and relevant support only",()=>{const n=composeWeeklyNarrative({window,canonicalObjects:canonical,weights,photoEvent});const interpretation=JSON.stringify(n.cards.interpretation);expect(interpretation).not.toMatch(/stay the course|should|keep execution/i);expect(n.cards.coachInsight.preparation).toMatch(/DEXA.*most important/i);expect(n.cards.interpretation.domains.map((item)=>item.domain)).toEqual(["Photos","Weight","Training","Activity"]);expect(interpretation).not.toMatch(/Nutrition/i);});
  it("gives every meaningful domain a Highlight and Insight",()=>{const nutrition=[...canonical,...Array.from({length:3},(_,i)=>({canonicalId:`nutrition_${i}`,evidence_type:"nutrition",lastObservedAt:`2026-07-${String(8+i).padStart(2,"0")}`,quality:{status:"active"},payload:{quality:{status:"complete"}}}))];const n=composeWeeklyNarrative({window,canonicalObjects:nutrition,weights,photoEvent});for(const item of n.cards.interpretation.domains){expect(item.highlight).toBeTruthy();expect(item.insight).toBeTruthy();}expect(n.cards.interpretation.domains.map((item)=>item.domain)).toContain("Nutrition");});
  it("celebrates a real weekly accomplishment and preserves uncertainty",()=>{const n=composeWeeklyNarrative({window,canonicalObjects:canonical,weights,photoEvent});expect(n.cards.coachInsight.celebration).toMatch(/1.2 lb lower/i);expect(n.cards.interpretation.uncertainty).toMatch(/DEXA.*objective/i);expect(n.cards.hero.title).not.toMatch(/evidence window|confidence|trajectory|direction/i);});
  it("persists a stable artifact and keeps preview non-destructive",async()=>{const artifacts=[];const repositories={users:{getCurrentUser:async()=>({timeZone:"America/Los_Angeles"})},canonicalEvidence:{listCanonicalEvidenceObjects:async()=>canonical},weights:{listWeightEntries:async()=>weights},dailyBriefings:{listDailyBriefings:async()=>artifacts,createDailyBriefing:async(a)=>{artifacts.push(a);return a;}},goals:{getActiveGoal:async()=>({title:"Visible Abs at Rest"})}};const service=createWeeklyNarrativeService({repositories,now:()=>new Date("2026-07-12T18:00:00Z")});const first=await service.getOrCreate({userId:"user"});const second=await service.getOrCreate({userId:"user"});expect(second).toBe(first);expect(artifacts).toHaveLength(1);await service.getOrCreate({userId:"user",preview:true});expect(artifacts).toHaveLength(1);});
});
