import { describe, expect, it, vi } from "vitest";
import { createDailyBriefingRepository } from "../../data/repositories/DailyBriefingRepository";
import { createWeeklyNarrativeService, getWeeklyVersionStatus } from "./WeeklyNarrativeService";

const old = { id: "weekly-old", userId: "u", artifactType: "scheduled", cadence: "weekly", generatedAt: "2026-01-01", briefing: { version: "daily-briefing-v29", hero: { title: "Old" } } };
function repos(records = [old]) { return { users: { getCurrentUser: async () => ({ timeZone: "America/Los_Angeles" }) }, dailyBriefings: { getLatestWeeklyBriefing: vi.fn(async () => records.at(-1) ?? null), listDailyBriefings: async () => records, createDailyBriefing: vi.fn(async (artifact) => { records.push(artifact); return artifact; }) }, canonicalEvidence: { listCanonicalEvidenceObjects: async () => [] }, weights: { listWeightEntries: async () => [] }, dexaScans: { listDEXAScans: async () => [] }, goals: { getActiveGoal: async () => null } }; }

describe("Weekly read safety", () => {
  it("reads an old version without mutation", async () => { const r = repos(); const service = createWeeklyNarrativeService({ repositories: r }); const result = await service.getLatest({ userId: "u" }); expect(result.id).toBe("weekly-old"); expect(getWeeklyVersionStatus(result).current).toBe(false); expect(r.dailyBriefings.createDailyBriefing).not.toHaveBeenCalled(); expect(old.generatedAt).toBe("2026-01-01"); });
  it("is equally available on Monday and Sunday because direct reads have no cadence gate", async () => { for (const current of [new Date("2026-07-13T18:00:00Z"), new Date("2026-07-19T18:00:00Z")]) { const r = repos(); const service = createWeeklyNarrativeService({ repositories: r, now: () => current }); expect((await service.getLatest({ userId: "u" })).id).toBe("weekly-old"); expect(r.dailyBriefings.createDailyBriefing).not.toHaveBeenCalled(); } });
  it("selects the latest final Weekly and excludes persisted previews and Daily artifacts", async () => { const finalOld = { ...old, id: "weekly-final-old", generatedAt: "2026-07-01" }; const finalNew = { ...old, id: "weekly-final-new", generatedAt: "2026-07-08" }; const preview = { ...old, id: "weekly-preview", generatedAt: "2026-07-10", preview: true }; const daily = { ...old, id: "daily-newest", cadence: "daily", generatedAt: "2026-07-11" }; const repository = createDailyBriefingRepository([finalOld, finalNew, preview, daily]); const service = createWeeklyNarrativeService({ repositories: { dailyBriefings: repository } }); expect((await service.getLatest({ userId: "u" })).id).toBe("weekly-final-new"); });
  it("returns null when none exists", async () => { expect(await createWeeklyNarrativeService({ repositories: repos([]) }).getLatest({ userId: "u" })).toBeNull(); });
  it("requires explicit generation and reason for regeneration", async () => { const r = repos([]); const service = createWeeklyNarrativeService({ repositories: r, now: () => new Date("2026-07-12T12:00:00Z") }); await service.generate({ userId: "u" }); expect(r.dailyBriefings.createDailyBriefing).toHaveBeenCalledTimes(1); await expect(service.regenerate({ userId: "u" })).rejects.toThrow(/reason/); await service.regenerate({ userId: "u", reason: "operator request" }); expect(r.dailyBriefings.createDailyBriefing).toHaveBeenCalledTimes(2); });
  it("uses cadence-aware version policy", () => { expect(getWeeklyVersionStatus(old)).toEqual(expect.objectContaining({ current: false, persistedVersion: "daily-briefing-v29", expectedVersion: "weekly_narrative_v5_1" })); });
});
