import Link from "next/link";
import { Activity, ArrowLeft, Dumbbell, Flame, Scale, ShieldCheck, Sparkles } from "lucide-react";
import Card from "../components/ui/Card";
import IconBadge from "../components/ui/IconBadge";

export default function MidweekBriefingScreen({ briefing }) {
  const { energyBalance: energy, training, activePhase: phase } = briefing;
  return <main className="app-surface min-h-screen overflow-x-hidden"><div className="mx-auto max-w-[393px] px-4 pb-32 pt-10">
    <Link className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]" href="/briefings/review"><ArrowLeft size={18}/>Briefing History</Link>
    <section className="rounded-[28px] border border-[color-mix(in_srgb,var(--chart-2)_20%,var(--divider))] bg-gradient-to-br from-[color-mix(in_srgb,var(--chart-2)_8%,var(--surface-elevated))] to-[var(--surface-elevated)] p-5 shadow-[var(--shadow-card)]" data-testid="midweek-hero">
      <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><IconBadge color="evidence" icon={Sparkles}/><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--chart-2)]">Midweek Briefing</p>{briefing.preview&&<p className="text-[9px] font-bold uppercase tracking-[.08em] text-[var(--text-muted)]">Preview</p>}</div></div><p className="text-right text-[10px] font-bold text-[var(--text-secondary)]">Sun–Tue<br/>{formatRange(briefing.evidenceWindow)}</p></div>
      <p className="mt-5 text-xs font-extrabold text-[var(--primary)]">{briefing.activeGoal?.name}</p><h1 className="mt-1 text-[28px] font-black leading-[1.12] text-[var(--text-primary)]">{briefing.hero.verdict}</h1><p className="mt-3 text-sm font-semibold leading-6 text-[var(--text-secondary)]">{briefing.hero.summary}</p>
      {phase && <div className="mt-4 flex flex-wrap gap-x-4 gap-y-1 border-t border-[var(--divider)] pt-3 text-[10px] font-bold text-[var(--text-secondary)]"><span>Current strategy: {phase.name}</span><span>{phase.weekLabel}</span><span>Review {shortDate(phase.plannedReviewDate)}</span></div>}
    </section>
    <div className="mt-3 space-y-3">
      <FeatureCard icon={Flame} label="Energy Balance" tone="effort" title={energyConclusion(energy)}><p className="text-[26px] font-black leading-8 text-[var(--text-primary)]">{balanceHeadline(energy)}</p><p className="mt-3 text-sm font-semibold leading-6 text-[var(--text-secondary)]">{energyInterpretation(energy)}</p>{energy.comparison&&<p className="mt-2 text-xs font-semibold leading-5 text-[var(--text-muted)]">{energyComparisonText(energy)}</p>}<div className="mt-4 space-y-2">{energy.chartPoints.map((point)=><EnergyDay key={point.date} point={point}/>)}</div>{briefing.charts.energy&&<EnergyChart chart={briefing.charts.energy}/>}</FeatureCard>
      <Card><SectionHeading icon={Scale}>Weight Context</SectionHeading><p className="mt-2 text-2xl font-black">{value(briefing.weightContext.averageWeight," lb")}</p><p className="text-[10px] font-bold text-[var(--text-muted)]">Sunday–Tuesday average · {briefing.weightContext.observations} observations</p><p className="mt-3 text-sm font-semibold leading-6 text-[var(--text-secondary)]">{briefing.weightContext.interpretation}</p></Card>
      <FeatureCard icon={Dumbbell} label="Training Response" tone="primary" title={training.performanceHeadline}><p className="text-sm font-semibold leading-6 text-[var(--text-secondary)]">{training.interpretation}</p>{training.highlights.length>0&&<TrainingHighlights items={training.highlights}/>} {training.watch.length>0&&<TrainingWatch items={training.watch}/>} {training.prioritySignals.length>0&&<div className="mt-5"><p className="text-[10px] font-black uppercase tracking-[.08em] text-[var(--text-muted)]">🎯 Priority Muscle Groups</p><div className="mt-2 grid gap-2">{training.prioritySignals.map((signal)=><PrioritySignal key={signal.key} signal={signal}/>)}</div></div>}</FeatureCard>
      <BodyComposition briefing={briefing}/>
      <section className="coach-take-card rounded-[24px] border border-white/10 bg-[color-mix(in_srgb,var(--primary)_82%,#171225)] p-5 text-white shadow-[0_18px_48px_rgba(12,8,28,.18)]" data-testid="coach-take"><p className="text-[10px] font-black uppercase tracking-[.12em] text-white/65">Coach&apos;s Take</p><CoachPoint emoji="💡" label="Biggest Takeaway">{coachOpinion(briefing)}</CoachPoint><CoachPoint emoji="🧠" label="My Recommendation" separated>{coachRecommendation(briefing)}</CoachPoint><div className="mt-7 border-t border-white/10 pt-5"><p className="text-[10px] font-black uppercase tracking-[.08em]"><span aria-hidden="true">🎯</span>{" "}<span className="text-white/70">Through Sunday</span></p><ol className="mt-3 space-y-3">{briefing.prioritiesThroughSunday.map((priority,index)=><li className="grid grid-cols-[1.25rem_1fr] items-start gap-2 text-sm font-semibold leading-6 text-white/90" key={priority}><span className="pt-px text-center font-black text-white/50">{index+1}</span><span>{priority}</span></li>)}</ol></div></section>
    </div>
  </div></main>;
}

function FeatureCard({icon,label,tone,title,children}) { return <Card><SectionHeading icon={icon} tone={tone}>{label}</SectionHeading><h2 className="mt-2 text-xl font-black leading-6">{title}</h2><div className="mt-3">{children}</div></Card>; }
function SectionHeading({icon:Icon,children,tone="primary"}) { return <div className="flex items-center gap-2"><IconBadge color={tone} icon={Icon} size="xs"/><p className="text-[10px] font-black uppercase tracking-[.1em] text-[var(--primary)]">{children}</p></div>; }
function EnergyDay({point}) { return <div className="flex items-center justify-between gap-3 rounded-xl bg-[var(--surface-muted)] p-3"><p className="text-xs font-black">{longDay(point.date)}</p><div className="text-right"><p className="text-[9px] font-bold uppercase tracking-[.08em] text-[var(--text-muted)]">{point.complete?"Energy Balance":""}</p><p className={`text-xs font-black ${point.complete?"text-[var(--text-primary)]":"text-[var(--text-muted)]"}`}>{point.complete?signedKcal(point.balance):"No data logged"}</p></div></div>; }
function MiniMetric({label,value:display}) { return <div className="min-w-0 rounded-xl bg-[var(--surface-muted)] p-3"><p className="text-[9px] font-extrabold uppercase tracking-[.07em] text-[var(--text-muted)]">{label}</p><p className="mt-1 break-words text-xs font-black leading-5 text-[var(--text-primary)]">{display??"Unavailable"}</p></div>; }
function TrainingHighlights({items}) { return <div className="mt-5"><p className="text-[10px] font-black uppercase tracking-[.08em] text-[var(--text-muted)]">🔥 Highlights</p><div className="mt-2 space-y-2">{items.map((item)=><div className="rounded-xl border border-[color-mix(in_srgb,var(--success)_22%,var(--divider))] bg-[var(--surface-muted)] p-3" key={`${item.exercise}-${item.label}`}><div className="flex items-start gap-2"><span aria-hidden>{item.icon}</span><div className="min-w-0"><p className="text-sm font-black text-[var(--text-primary)]">{item.exercise}</p><p className="text-[10px] font-extrabold uppercase tracking-[.06em] text-[var(--success)]">{item.label}</p></div></div><p className="mt-2 text-xl font-black">{trainingValue(item)}</p>{Number.isFinite(item.delta)&&<p className="mt-0.5 text-xs font-extrabold text-[var(--success)]">▲ {signedNumber(item.delta)} {item.unit} {Number.isFinite(item.percentChange)&&`(${signedNumber(item.percentChange)}%)`}</p>}</div>)}</div></div>; }
function TrainingWatch({items}) { return <div className="mt-5"><p className="text-[10px] font-black uppercase tracking-[.08em] text-[var(--text-muted)]">👀 Watch</p><div className="mt-2 space-y-2">{items.map((item)=><p className="rounded-xl bg-[var(--surface-muted)] p-3 text-xs font-bold leading-5 text-[var(--text-secondary)]" key={item.exercise}>{item.message}</p>)}</div></div>; }
function PrioritySignal({signal}) { const dot=signal.tone==="positive"?"🟢":signal.tone==="watch"?"🟠":"🟡"; return <div className="rounded-xl bg-[var(--surface-muted)] p-3"><p className="text-xs font-black">{dot} {signal.label}</p><p className="mt-1 text-[10px] font-bold leading-4 text-[var(--text-secondary)]">{signal.status}</p></div>; }
function BodyComposition({briefing}) { const body=briefing.bodyComposition,metrics=body?.newScan?body:body?.baseline; return <FeatureCard icon={body?.newScan?Activity:ShieldCheck} label="Body Composition" tone="evidence" title="Current Baseline">{metrics&&<div className="grid grid-cols-2 gap-2"><MiniMetric label="Body fat" value={value(metrics.bodyFatPercentage,"%")}/><MiniMetric label="Lean mass" value={value(metrics.leanMass," lb")}/><MiniMetric label="Fat mass" value={value(metrics.fatMass," lb")}/><MiniMetric label="DEXA date" value={longDate(metrics.date)}/></div>}<p className="mt-3 text-sm font-semibold leading-6 text-[var(--text-secondary)]">{body?.interpretation}</p><p className="mt-3 text-xs font-extrabold text-[var(--text-primary)]">Current objective: {body?.objective}</p></FeatureCard>; }
function CoachPoint({emoji,label,children,separated=false}) { return <div className={separated?"mt-7 border-t border-white/10 pt-5":"mt-5"}><p className="text-[10px] font-black uppercase tracking-[.08em]"><span aria-hidden="true">{emoji}</span>{" "}<span className="text-white/70">{label}</span></p><p className="mt-2 text-sm font-semibold leading-6 text-white/90">{children}</p></div>; }
function EnergyChart({chart}) { const max=Math.max(...chart.points.flatMap((p)=>[p.intake,p.expenditure]).filter(Number.isFinite),1); return <figure className="mt-4 overflow-visible" data-chart="midweek-energy"><figcaption className="mb-3 text-xs font-extrabold">{chart.title}</figcaption><div className="grid grid-cols-3 gap-3">{chart.points.map((point)=><details className="group relative min-w-0" key={point.date}><summary className="list-none cursor-pointer focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)]"><div className="flex h-24 items-end justify-center gap-1 rounded-lg bg-[var(--surface-muted)] px-2 pt-2"><Bar color="var(--chart-3)" max={max} value={point.intake}/><Bar color="var(--chart-2)" max={max} value={point.expenditure}/></div><p className="mt-1 text-center text-[10px] font-bold">{point.label}{!point.complete?" · missing":""}</p></summary><div className="absolute bottom-full left-1/2 z-20 mb-2 hidden w-44 -translate-x-1/2 rounded-xl bg-[var(--text-primary)] p-3 text-left text-[10px] font-bold leading-5 text-[var(--surface-elevated)] shadow-xl group-open:block group-hover:block"><p className="text-xs font-black">{longDate(point.date)}</p>{point.complete?<><p>Calories eaten: {point.intake.toLocaleString("en-US")} kcal</p><p>Estimated expenditure: {point.expenditure.toLocaleString("en-US")} kcal</p><p>Energy balance: {signedKcal(point.balance)}</p></>:<p>No data logged</p>}</div></details>)}</div><p className="mt-2 text-[9px] font-semibold text-[var(--text-muted)]"><span className="text-[var(--chart-3)]">■</span> Intake &nbsp; <span className="text-[var(--chart-2)]">■</span> Estimated expenditure</p></figure>; }
function Bar({color,max,value:amount}) { return <div className="w-4 rounded-t" style={{height:Number.isFinite(amount)?`${Math.max(4,amount/max*100)}%`:"2px",backgroundColor:Number.isFinite(amount)?color:"var(--divider)"}}/>; }
function energyConclusion(energy) { return ({probably_below:"Intake is below estimated expenditure",probably_above:"Intake is above estimated expenditure",roughly_at:"Intake and expenditure are close",unclear:"More food and activity data needed"})[energy.balanceDirection]; }
function balanceHeadline(energy) { const amount=Math.abs(Math.round(energy.estimatedDailyBalanceMidpoint)); if(!Number.isFinite(amount))return "No daily estimate yet"; if(amount<25)return "About even day to day"; return `${amount.toLocaleString("en-US")} kcal/day ${energy.estimatedDailyBalanceMidpoint<0?"below":"above"}`; }
function energyInterpretation(energy) { const complete=energy.chartPoints.filter((point)=>point.complete), missing=energy.chartPoints.filter((point)=>!point.complete); if(!complete.length)return "Food or activity is missing for each day so far. Keep the plan steady and fill in what you can before Sunday."; const days=complete.map((point)=>longDay(point.date)); const dayText=days.length===1?days[0]:days.length===2?`${days[0]} and ${days[1]}`:`${days[0]}, ${days[1]}, and ${days[2]}`; const missingText=missing.length?` ${longDay(missing[0].date)} is missing data, which is another reason to wait for Sunday’s review.`:""; return energy.balanceDirection==="probably_below"?`${dayText} ${days.length===1?"suggests":"suggest"} you’re still below maintenance.${missingText} Keep calories steady for now.`:`${dayText} look close to maintenance.${missingText} Keep calories steady for now.`; }
function energyComparisonText(energy) { const previous=energy.comparison?.averageBalance,current=energy.estimatedAverageDailyBalance;if(!Number.isFinite(previous)||!Number.isFinite(current))return "The prior comparable period does not have enough paired evidence for a directional comparison.";const change=Math.round(current-previous);const direction=Math.abs(change)<25?"was similar to":change>0?"was higher than":"was lower than";const rmr=energy.rmrProvenance?.sourceDexaDate?` Estimated expenditure uses the DEXA RMR available on ${shortDate(energy.rmrProvenance.sourceDexaDate)} plus active calories.`:" Estimated expenditure is limited because an eligible RMR source is unavailable.";return `Average estimated balance ${direction} the prior comparable period by ${Math.abs(change).toLocaleString("en-US")} kcal/day.${rmr}`; }
function coachOpinion(briefing) { const top=briefing.training.highlights[0]; if(top)return `Training is progressing the way we want at the start of a lean-mass goal, led by ${top.exercise}. I would rather protect that momentum than react to a few days of calorie math.`; return "The important thing this week is establishing a training rhythm we can build on. There is nothing here that calls for an early change."; }
function coachRecommendation(briefing) { const missing=briefing.energyBalance.chartPoints.filter((point)=>!point.complete).map((point)=>longDay(point.date)); if(missing.length)return `${missing.join(" and ")} ${missing.length===1?"is":"are"} still incomplete. I’d make the calorie decision after a few more days with food and activity recorded instead of guessing today.`; return "Keep calories and activity steady through Sunday. If training continues to progress while weight remains controlled, we will have a stronger case for staying the course."; }
function trainingValue(item) { return Number.isFinite(item.value)?`${Number(item.value).toLocaleString("en-US",{maximumFractionDigits:1})} ${item.unit}`:"Record set"; }
function signedNumber(number) { return `${number>0?"+":"−"}${Math.abs(Number(number)).toLocaleString("en-US",{maximumFractionDigits:1})}`; }
function signedKcal(number) { return `${number>0?"+":"−"}${Math.abs(Math.round(number)).toLocaleString("en-US")} kcal`; }
function value(number,suffix) { return Number.isFinite(number)?`${Number(number).toLocaleString("en-US",{maximumFractionDigits:1})}${suffix}`:"Unavailable"; }
function shortDate(value) { return value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`)):"Not established"; }
function longDate(value) { return value?new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`)):"Unavailable"; }
function longDay(value) { return new Intl.DateTimeFormat("en-US",{weekday:"long",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`)); }
function formatRange(window) { return `${shortDate(window.startDate)}–${shortDate(window.endDate)}`; }
