import Link from "next/link";
import { ArrowLeft, BookOpen } from "lucide-react";
import IconBadge from "../components/ui/IconBadge";
import ProgressLineChart from "../components/progress/ProgressLineChart";
import ProgressPhotoGallery from "../components/progress/ProgressPhotoGallery";
import EvidenceImage from "../components/progress/EvidenceImage";

export default function MonthlyBriefingScreen({ narrative }) { return <main className="app-surface min-h-screen overflow-x-hidden"><div className="mx-auto max-w-[393px] px-4 pb-32 pt-10">
  <Link className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-500" href="/briefings/review"><ArrowLeft size={18}/>Briefing History</Link>
  <section data-testid="monthly-hero" className="mb-5 space-y-4 rounded-[28px] border border-violet-200/80 bg-gradient-to-br from-violet-50 via-white to-amber-50 p-4 shadow-[0_22px_56px_-30px_rgba(79,70,229,.58)] dark:border-violet-300/15 dark:from-violet-400/[.1] dark:via-white/[.06] dark:to-amber-400/[.08]">
    <div className="flex items-center gap-3"><IconBadge color="primary" icon={BookOpen} size="md"/><div><p className="text-sm font-semibold uppercase tracking-[0.12em] text-indigo-600">Monthly Briefing</p><p className="text-[10px] font-bold text-slate-400">June 1–30 · Delivered July 1</p></div></div>
    <h1 className="text-[30px] font-extrabold leading-[1.12] text-slate-950">{narrative.hero.title}</h1><p className="text-sm font-semibold leading-6 text-slate-600">{narrative.hero.thesis}</p>
    <div className="grid grid-cols-2 gap-2">{narrative.hero.highlights.map((item)=><Highlight key={item.domain} item={item}/>)}</div>
    {narrative.hero.milestone&&<div className="rounded-2xl border border-emerald-200/80 bg-emerald-50/80 p-3 dark:border-emerald-300/15 dark:bg-emerald-300/5"><Eyebrow>{narrative.hero.milestone.label}</Eyebrow><p className="mt-1 text-sm font-extrabold leading-5 text-slate-900">{narrative.hero.milestone.value}</p></div>}
  </section>
  <section data-testid="monthly-weight-story" className="mb-3 rounded-[20px] border border-[var(--divider)] bg-[var(--surface-elevated)] p-4 shadow-[var(--shadow-card)]"><Eyebrow>June at a glance</Eyebrow><h2 className="mt-1 text-xl font-extrabold">{narrative.weightStory.title}</h2><p className="mt-1 text-xs font-semibold leading-5 text-slate-500">{narrative.weightStory.summary}</p><div className="mt-3"><ProgressLineChart ariaLabel="June daily weight trend" metricLabel="Weight" markers={narrative.weightStory.markers} points={narrative.weightStory.points} suffix=" lb"/></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Mini label="Began" value={narrative.weightStory.start}/><Mini label="Closed" value={narrative.weightStory.end}/><Mini label="Change" value={narrative.weightStory.change}/></div><div className="mt-3 flex gap-3 text-[10px] font-bold text-slate-400"><span>◆ DEXA</span><span>• Photo session</span></div></section>
  <div className="space-y-3">
    <Chapter title={narrative.whereMonthBegan.title}><p className="mt-2 text-sm font-semibold leading-6 text-slate-700">{narrative.whereMonthBegan.summary}</p><div className="mt-3 grid grid-cols-2 gap-2">{narrative.whereMonthBegan.facts.map((fact)=><Fact fact={fact} key={fact.label}/>)}</div></Chapter>
    <Chapter title={narrative.whatChanged.title}>{narrative.whatChanged.themes.map((theme)=><Theme key={theme.title} theme={theme}/>)}</Chapter>
    <Chapter title={narrative.definingMoments.title}><div className="relative mt-4 space-y-5 before:absolute before:bottom-2 before:left-[6px] before:top-2 before:w-px before:bg-violet-200">{narrative.definingMoments.moments.map((moment)=><section className="relative pl-7" key={moment.label}><span className="absolute left-0 top-1 h-[13px] w-[13px] rounded-full border-[3px] border-white bg-violet-500 shadow-sm"/><p className="text-[10px] font-black uppercase text-violet-600">{moment.date}</p><h3 className="mt-1 text-sm font-extrabold text-slate-900">{moment.label}</h3><p className="mt-1 text-xs font-semibold leading-5 text-slate-600">{moment.body}</p>{moment.media&&<PhotoMoment media={moment.media}/>}</section>)}</div></Chapter>
    <Chapter title={narrative.strategyReview.title}><p className="mt-2 text-sm font-extrabold leading-6 text-slate-800">{narrative.strategyReview.thesis}</p><div className="mt-3 grid grid-cols-2 gap-2">{narrative.strategyReview.items.map((item)=><Verdict item={item} key={item.label}/>)}</div></Chapter>
    {narrative.costOfProgress&&<Chapter title={narrative.costOfProgress.title}><p className="mt-2 text-sm font-semibold leading-6 text-slate-700">{narrative.costOfProgress.body}</p></Chapter>}
    <Chapter className="border-violet-200/70 bg-violet-50/45 dark:border-violet-300/15 dark:bg-violet-300/[.04]" title={narrative.chapterAhead.title}><p className="mt-2 text-sm font-extrabold leading-6 text-slate-900">{narrative.chapterAhead.thesis}</p><div className="mt-3 grid grid-cols-2 gap-2">{narrative.chapterAhead.guidance.map((item)=><section className="rounded-xl bg-[var(--surface-elevated)] p-3 shadow-sm" key={item.label}><span>{item.icon}</span><p className="mt-2 text-[9px] font-extrabold uppercase tracking-[.08em] text-violet-600">{item.label}</p><p className="mt-1 text-xs font-black text-slate-900">{item.value}</p><p className="mt-1 text-[10px] font-semibold leading-4 text-slate-500">{item.detail}</p></section>)}</div></Chapter>
  </div>
</div></main> }

function PhotoMoment({media}){return <ProgressPhotoGallery records={media.records} sets={media.sets} triggerOnly><div className="mt-3 grid grid-cols-2 gap-2">{media.sets.map((set,index)=><button className="overflow-hidden rounded-xl bg-[var(--surface-muted)] text-left" data-photo-set-id={set.id} key={set.id} type="button"><EvidenceImage alt={index?"Latest June progress photo":"First June progress photo"} className="aspect-[3/4] w-full object-cover" src={set.thumbnailHref}/><span className="block px-2 py-2 text-[10px] font-extrabold text-slate-600">{index?"Latest · ":"First · "}{set.date}</span></button>)}</div><p className="mt-2 text-[10px] font-bold text-violet-600">Tap either photo to open the Narrative gallery →</p></ProgressPhotoGallery>}
function Verdict({item}){const dot={positive:"bg-emerald-500",watch:"bg-amber-500",neutral:"bg-slate-400",decision:"bg-violet-500"}[item.tone];return <section className="rounded-xl bg-[var(--surface-muted)] p-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${dot}`}/><Eyebrow>{item.label}</Eyebrow></div><p className="mt-2 text-sm font-black text-slate-900">{item.value}</p><p className="mt-1 text-[10px] font-semibold leading-4 text-slate-500">{item.detail}</p></section>}
function Chapter({title,children,className=""}){return <section className={`rounded-[14px] border border-[var(--divider)] bg-[var(--surface-elevated)] p-4 text-[var(--text-primary)] shadow-[var(--shadow-card)] ${className}`}><Eyebrow>Chapter</Eyebrow><h2 className="mt-1 text-lg font-extrabold">{title}</h2>{children}</section>}
function Highlight({item}){const tone={transformation:"border-amber-200/80 bg-amber-50/80 dark:border-amber-300/15 dark:bg-amber-300/[.06]",confirmation:"border-sky-200/80 bg-sky-50/75 dark:border-sky-300/15 dark:bg-sky-300/[.06]",visual:"border-fuchsia-200/70 bg-fuchsia-50/65 dark:border-fuchsia-300/15 dark:bg-fuchsia-300/[.05]",finish:"border-emerald-200/80 bg-emerald-50/75 dark:border-emerald-300/15 dark:bg-emerald-300/[.06]"}[item.tone]??"border-violet-100/80 bg-white/75 dark:border-white/10 dark:bg-white/5";return <section className={`flex min-h-28 flex-col rounded-2xl border p-3 ${tone}`}><div className="flex items-center gap-1.5"><span aria-hidden>{item.icon}</span><p className="text-[9px] font-extrabold uppercase tracking-[.08em] text-violet-700 dark:text-violet-300">{item.label}</p></div><p className="mt-3 text-sm font-black leading-5 text-slate-900">{item.value}</p>{item.detail&&<p className="mt-auto pt-2 text-[10px] font-bold leading-4 text-slate-500">{item.detail}</p>}</section>}
function Mini({label,value}){return <div className="rounded-xl bg-[var(--surface-muted)] p-2"><Eyebrow>{label}</Eyebrow><p className="mt-1 text-xs font-black">{value}</p></div>}
function Fact({fact}){return <section className="rounded-xl bg-[var(--surface-muted)] p-3"><p className="text-[9px] font-extrabold uppercase tracking-[.08em] text-slate-400">{fact.label}</p><p className="mt-1 text-xs font-extrabold leading-5 text-slate-800">{fact.value}</p></section>}
function Theme({theme}){return <section className="mt-3 rounded-xl bg-[var(--surface-muted)] p-3"><h3 className="text-sm font-extrabold text-slate-900">{theme.title}</h3><p className="mt-1 text-xs font-semibold leading-5 text-slate-600">{theme.body}</p></section>}
function Eyebrow({children}){return <p className="text-[10px] font-extrabold uppercase tracking-[.1em] text-[var(--primary)]">{children}</p>}
