import Link from "next/link";
import { Activity, ArrowLeft, ArrowRight, CheckCircle2, Dumbbell, Gauge, ScanLine, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";

export default function PhaseAwareActiveGoalPreviewScreen({ preview }) {
  return <main className="app-surface mx-auto min-h-screen w-full max-w-[393px] overflow-x-hidden"><div className="px-4 pb-[calc(8rem+env(safe-area-inset-bottom))] pt-10">
    <Link className="mb-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[var(--text-secondary)]" href="/goals"><ArrowLeft size={18}/>Goals</Link>
    <section data-testid="active-goal-preview-hero" className="rounded-[30px] border border-violet-300/40 bg-gradient-to-br from-violet-100 via-[var(--surface-elevated)] to-emerald-50 p-5 shadow-[0_28px_70px_-40px_rgba(109,40,217,.7)] dark:border-violet-300/15 dark:from-violet-300/[.12] dark:via-white/[.06] dark:to-emerald-300/[.05]">
      <div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.15em] text-violet-700 dark:text-violet-300">{preview.hero.status}</p><h1 className="mt-3 break-words text-[32px] font-black leading-none text-[var(--text-primary)]">{preview.hero.title}</h1></div><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-violet-500/15 text-violet-700 dark:text-violet-300"><Dumbbell size={24}/></span></div>
      <p className="mt-5 text-base font-extrabold leading-6 text-[var(--text-primary)]">{preview.hero.destination}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-violet-300/30 pt-4 dark:border-white/10"><span className="inline-flex min-w-0 items-center gap-2 text-xs font-black text-[var(--text-secondary)]"><Gauge size={16} className="shrink-0 text-violet-600 dark:text-violet-300"/><span className="min-w-0 break-words">{preview.hero.confidence} · {preview.hero.confidenceBand}</span></span><Link className="inline-flex min-h-11 items-center rounded-xl px-2 text-sm font-black text-[var(--primary)]" href={preview.hero.editHref}>Edit Goal</Link></div>
    </section>

    <Section eyebrow="The path" title="Your Journey"><div className="mt-5 space-y-3">{preview.journey.map((phase,index)=><PhaseCard key={phase.name} phase={phase} number={index+1}/>)}</div></Section>
    <AccentSection color="orange" eyebrow="Where you are" icon={<Activity size={20}/>} title="Current Phase"><h3 className="mt-4 text-xl font-black text-[var(--text-primary)]">{preview.currentPhase.title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-[var(--text-secondary)]">{preview.currentPhase.purpose}</p><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="Current week" value={preview.currentPhase.week}/><Metric label="Planned review" value={preview.currentPhase.review}/></div><Subhead title="Evidence in view"/><p className="text-sm font-medium leading-6 text-[var(--text-secondary)]">{preview.currentPhase.evidence}</p><Subhead title="Readiness"/><p className="text-sm font-medium leading-6 text-[var(--text-secondary)]">{preview.currentPhase.readiness}</p></AccentSection>
    {preview.next?<AccentSection color="green" eyebrow="What comes next" icon={<Sparkles size={20}/>} title={preview.next.title}><p className="mt-4 text-base font-black text-[var(--text-primary)]">{preview.next.goal}</p><div className="mt-4 space-y-3">{[preview.next.outcome,preview.next.lead,preview.next.guardrail].map(item=><p className="flex gap-3 text-sm font-semibold leading-6 text-[var(--text-secondary)]" key={item}><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600 dark:text-emerald-300" size={17}/>{item}</p>)}</div></AccentSection>:<AccentSection color="green" eyebrow="Final planned phase" icon={<Sparkles size={20}/>} title="Goal review comes next"><p className="mt-4 text-sm font-semibold leading-6 text-[var(--text-secondary)]">This is the final planned phase. The next decision is based on Goal progress and evidence, not an assumed additional phase.</p></AccentSection>}
    <Section eyebrow="Phase decision" title="Ready to Move Forward When"><div className="mt-5 space-y-4">{preview.readiness.map((item,index)=><div className="grid grid-cols-[28px_minmax(0,1fr)] gap-3" key={item}><span className="grid h-7 w-7 place-items-center rounded-full bg-orange-100 text-xs font-black text-orange-800 dark:bg-orange-300/10 dark:text-orange-300">{index+1}</span><p className="text-sm font-semibold leading-6 text-[var(--text-secondary)]">{item}</p></div>)}</div></Section>
    <AccentSection color="purple" eyebrow="Non-negotiable" icon={<ShieldCheck size={20}/>} title="Guardrail"><h3 className="mt-4 text-xl font-black text-[var(--text-primary)]">{preview.guardrail.title}</h3><p className="mt-2 text-xs font-black uppercase tracking-[.1em] text-violet-700 dark:text-violet-300">{preview.guardrail.scope}</p><p className="mt-4 text-sm font-semibold leading-6 text-[var(--text-secondary)]">{preview.guardrail.body}</p></AccentSection>
    <Section eyebrow="What progress means" title="Evidence Anchors"><div className="mt-5 rounded-[24px] bg-slate-950 p-5 text-white dark:bg-white/[.07]"><div className="flex items-center gap-2 text-emerald-300"><ScanLine size={19}/><p className="text-[10px] font-black uppercase tracking-[.13em]">Authoritative DEXA · {formatDate(preview.evidence.dexa.date)}</p></div><div className="mt-5 grid grid-cols-2 gap-4">{[["Body Fat",preview.evidence.dexa.bodyFat],["Lean Mass",preview.evidence.dexa.leanMass],["Fat Mass",preview.evidence.dexa.fatMass],["Weight",preview.evidence.dexa.weight]].map(([label,value])=><Metric dark key={label} label={label} value={value}/>)}</div></div><Info icon={<Gauge size={18}/>} title="Weight and energy" body={preview.evidence.support}/></Section>
    <TrainingProgress progress={preview.trainingProgress}/>
    <Section eyebrow="Major milestones" title="Evidence Turning Points"><div className="mt-5 space-y-5">{preview.turningPoints.map((item)=><article className="border-l-2 border-[var(--divider)] pl-4" key={`${item.date}-${item.title}`}><p className="text-[10px] font-black uppercase tracking-[.1em] text-[var(--primary)]">{formatDate(item.date)}</p><h3 className="mt-1 text-base font-black text-[var(--text-primary)]">{item.title}</h3><p className="mt-1 text-sm font-medium leading-6 text-[var(--text-secondary)]">{item.body}</p></article>)}</div></Section>
    <Section eyebrow="How the goal is supported" title="Current Strategy"><div className="mt-5 grid grid-cols-2 gap-3">{preview.strategy.map((item)=><div className="rounded-2xl border border-[var(--divider)] bg-[var(--surface-elevated)] p-4" key={item.label}><p className="text-sm font-black text-[var(--text-primary)]">{item.label}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.08em] text-[var(--text-muted)]">Goal support</p></div>)}</div><div className="mt-5 space-y-3"><Action href={preview.actions.strategyHref} label="Review Strategy"/><Action href={preview.actions.protocolsHref} label="Review Protocols"/></div></Section>
  </div></main>;
}

function Section({eyebrow,title,children}){return <section className="border-b border-[var(--divider)] py-9 last:border-b-0"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--primary)]">{eyebrow}</p><h2 className="mt-2 text-2xl font-black leading-tight text-[var(--text-primary)]">{title}</h2>{children}</section>}
function AccentSection({color,eyebrow,icon,title,children}){const styles={orange:"border-orange-300/40 bg-orange-50/70 text-orange-700 dark:border-orange-300/15 dark:bg-orange-300/[.07] dark:text-orange-300",green:"border-emerald-300/40 bg-emerald-50/70 text-emerald-700 dark:border-emerald-300/15 dark:bg-emerald-300/[.07] dark:text-emerald-300",purple:"border-violet-300/40 bg-violet-50/70 text-violet-700 dark:border-violet-300/15 dark:bg-violet-300/[.07] dark:text-violet-300"};return <section className={`my-3 rounded-[28px] border p-5 ${styles[color]}`}><div className="flex items-center gap-2">{icon}<p className="text-[10px] font-black uppercase tracking-[.14em]">{eyebrow}</p></div><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">{title}</h2>{children}</section>}
function PhaseCard({phase,number}){const green=phase.color==="green";return <article className={`rounded-[24px] border p-4 ${green?"border-emerald-300/40 bg-emerald-50/60 dark:border-emerald-300/15 dark:bg-emerald-300/[.06]":"border-orange-300/40 bg-orange-50/60 dark:border-orange-300/15 dark:bg-orange-300/[.06]"}`}><div className="flex items-start gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl text-sm font-black ${green?"bg-emerald-500/15 text-emerald-700 dark:text-emerald-300":"bg-orange-500/15 text-orange-700 dark:text-orange-300"}`}>{number}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className={`text-[10px] font-black uppercase tracking-[.12em] ${green?"text-emerald-700 dark:text-emerald-300":"text-orange-700 dark:text-orange-300"}`}>Phase {number}</p><span className={`text-xs font-black ${green?"text-emerald-700 dark:text-emerald-300":"text-orange-700 dark:text-orange-300"}`}>{phase.status}</span></div><h3 className="mt-1 text-base font-black text-[var(--text-primary)]">{phase.name}</h3><p className="mt-1 text-xs font-bold text-[var(--text-muted)]">{phase.dates}</p></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-black/10 dark:bg-white/10"><div className={`h-full rounded-full ${green?"bg-emerald-500":"bg-orange-500"}`} style={{width:`${phase.percentage}%`}}/></div><div className="mt-3 flex flex-wrap justify-between gap-2 text-xs font-bold text-[var(--text-secondary)]"><span>{phase.progress}</span><span>{phase.support}</span></div></article>}
function Metric({label,value,dark=false}){return <div className="min-w-0"><p className={`text-[9px] font-black uppercase tracking-[.1em] ${dark?"text-slate-500":"text-[var(--text-muted)]"}`}>{label}</p><p className={`mt-1 break-words text-sm font-black ${dark?"text-white":"text-[var(--text-primary)]"}`}>{value}</p></div>}
function Subhead({title}){return <h4 className="mb-2 mt-5 text-[10px] font-black uppercase tracking-[.12em] text-[var(--text-muted)]">{title}</h4>}
function Info({icon,title,body}){return <div className="mt-3 rounded-2xl bg-[var(--surface-muted)] p-4"><div className="flex items-center gap-2 text-[var(--primary)]">{icon}<h3 className="text-sm font-black text-[var(--text-primary)]">{title}</h3></div><p className="mt-2 text-sm font-medium leading-6 text-[var(--text-secondary)]">{body}</p></div>}
function TrainingProgress({progress}){const ready=progress.readinessState==="ready",forming=progress.readinessState==="forming",limited=progress.readinessState==="limited";return <section data-testid="training-progress" className="border-b border-[var(--divider)] py-9"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--primary)]">Long-term performance</p><h2 className="mt-2 text-2xl font-black text-[var(--text-primary)]">Training Progress</h2></div><span className="shrink-0 rounded-full bg-violet-100 px-3 py-2 text-center text-[10px] font-black uppercase tracking-[.08em] text-violet-700 dark:bg-violet-300/10 dark:text-violet-300"><span className="block">First review</span>{formatDateShort(progress.reviewDate)}</span></div><div className="mt-5 rounded-[24px] border border-violet-300/35 bg-violet-50/60 p-5 dark:border-violet-300/15 dark:bg-violet-300/[.06]"><div className="flex items-center gap-2 text-violet-700 dark:text-violet-300"><TrendingUp size={19}/><p className="text-xs font-black">{ready?"Last four weeks":forming?"Review forming":limited?"Limited review":"First four-week review"}</p></div><p className="mt-4 text-[15px] font-bold leading-7 text-[var(--text-primary)]">{progress.overallInterpretation}</p>{forming&&<p className="mt-2 text-sm font-semibold text-[var(--text-secondary)]">The first full review remains scheduled for {formatDate(progress.reviewDate)}.</p>}{ready&&<MovementRows movements={progress.movementHighlights}/>} {limited&&<p className="mt-3 text-sm font-medium leading-6 text-[var(--text-secondary)]">More comparable sessions are needed before this becomes a completed journey checkpoint.</p>}</div><div className="mt-5"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--text-muted)]">PhysiqueOS will compare</p><div className="mt-3 grid grid-cols-1 gap-2">{["Priority movement workload","PRs and meaningful progression","Plateaus or regressions","Lower Body, Core, and Arms trends"].map(item=><p className="flex items-center gap-3 text-sm font-semibold text-[var(--text-secondary)]" key={item}><CheckCircle2 size={16} className="shrink-0 text-violet-600 dark:text-violet-300"/>{item}</p>)}</div></div>{ready&&<div className="mt-5 grid grid-cols-3 gap-2">{progress.priorityMuscleGroups.map(item=><div className="min-w-0 rounded-xl bg-[var(--surface-muted)] p-3 text-center" key={item.group}><p className="break-words text-xs font-black text-[var(--text-primary)]">{item.group}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[.06em] text-[var(--text-muted)]">{groupStatus(item.status)}</p></div>)}</div>}</section>}
function MovementRows({movements}){if(!movements.length)return null;return <div className="mt-5 space-y-3">{movements.map(item=><div className="rounded-2xl bg-[var(--surface-elevated)] p-4" key={item.id}><div className="flex items-start justify-between gap-3"><p className="text-sm font-black text-[var(--text-primary)]">{item.name}</p>{item.prs.length>0&&<span className="shrink-0 text-[9px] font-black uppercase tracking-[.08em] text-emerald-700 dark:text-emerald-300">PR</span>}</div>{Number.isFinite(item.currentVolumeLoad)&&<><p className="mt-2 text-lg font-black text-[var(--text-primary)]">{formatLoad(item.currentVolumeLoad)}</p><p className="mt-1 text-xs font-bold text-[var(--text-secondary)]">Previous: {formatLoad(item.previousVolumeLoad)} · {signed(item.absoluteChange)} · {signed(item.percentChange)}%</p></>}</div>)}</div>}
function groupStatus(value){return ({too_early_to_assess:"Too early",improving:"Improving",steady:"Steady",plateauing:"Plateauing",regressing:"Regressing"})[value]??"Too early"}
function formatLoad(value){return `${Math.round(value).toLocaleString("en-US")} lb`}
function signed(value){return `${value>=0?"+":""}${Number(value).toLocaleString("en-US")}`}
function Action({href,label}){return <Link className="flex min-h-12 items-center justify-between rounded-2xl border border-[var(--divider)] bg-[var(--surface-elevated)] px-4 text-sm font-black text-[var(--text-primary)]" href={href}>{label}<ArrowRight size={17} className="text-[var(--primary)]"/></Link>}
function formatDate(value){if(!value)return "Planned";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`))}
function formatDateShort(value){if(!value)return "Planned";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`))}
