import fs from "node:fs";
import {describe,expect,it} from "vitest";
const source=fs.readFileSync(new URL("./PhotoEventBriefingScreen.jsx",import.meta.url),"utf8");
describe("PhotoEventBriefingScreen V2",()=>{
  it("uses standard briefing hierarchy with a dark decision moment, not a dark report hero",()=>{expect(source).toContain("IconBadge");expect(source).toContain("Photo Event");expect(source).toContain("photo-event-user-decision");expect(source).toContain("bg-slate-950");});
  it("opens one reusable in-place touch viewer without Gallery navigation",()=>{expect(source).toContain("setViewer({items,index})");expect(source).toContain('role="dialog"');expect(source).toContain("onTouchStart");expect(source).toContain("onTouchEnd");expect(source).toContain("[touch-action:pinch-zoom]");expect(source).not.toContain("Open in Gallery");});
  it("restores scroll position and cycles the supplied gallery items",()=>{expect(source).toContain("scrollPosition.current=window.scrollY");expect(source).toContain("window.scrollTo");expect(source).toContain("items.length");});
  it("locks background scroll for the lifetime of the viewer",()=>{expect(source).toContain('body.style.position="fixed"');expect(source).toContain('body.style.overflow="hidden"');expect(source).toContain("overscroll-none");expect(source).toContain("overscroll-contain");});
  it("tracks drag distance and velocity, then completes or springs back",()=>{expect(source).toContain("setDragOffset(offset)");expect(source).toContain("const velocity=delta/elapsed");expect(source).toContain("window.innerWidth*.22");expect(source).toContain("transition-transform duration-300 ease-out");});
  it("gates paging during zoom and preloads adjacent photos",()=>{expect(source).toContain("setZooming(true)");expect(source).toContain("if(zooming)");expect(source).toContain("const preload=new Image()");expect(source).toContain("preload.src=items[index].imageHref");});
  it("renders the page itself as a centered mobile application viewport",()=>{for(const value of ["mx-auto min-h-screen max-w-[393px]","pb-32","overflow-x-hidden","space-y-3"]){expect(source).toContain(value);}expect(source).toContain("grid-cols-3");});
  it("presents a bounded final decision and inactive next-goal preview",()=>{for(const value of ["photo-event-user-decision","experience.userDecision.completeLabel","experience.userDecision.keepOpenLabel","Only your explicit choice closes the goal","next-goal-preview","Coming next"]){expect(source).toContain(value);}expect(source).toContain("disabled");expect(source).not.toContain('href="/goals/new"');});
  it("separates recent and full-journey comparison sections",()=>{expect(source).toContain("Since last check-in");expect(source).toContain("From first upload to now");expect(source).toContain("recentComparisons");expect(source).toContain("journeyComparisons");});
  it("removes the duplicate latest-comparison card",()=>{expect(source).not.toContain("Latest comparison");expect(source).not.toContain("Recent change");});
  it("shows a retry path without presenting completion controls for uncertain results",()=>{expect(source).toContain("photo-event-retry");expect(source).toContain("Upload Again");expect(source).toContain('experience.state==="confirmed"');});
  it("keeps first-recorded views separate without fake prior cards",()=>{expect(source).toContain("New baseline views");expect(source).toContain("new-pose-baseline");expect(source).toContain("First recorded view");});
});
