export const FOUNDATION_SOURCE_COLLECTIONS = Object.freeze([
  "user",
  "goals",
  "goalTransitionDrafts",
  "goalProtocolTransitionDrafts",
  "weightEntries",
  "dexaScans",
  "protocols",
  "protocolVersions",
  "energyStrategyLinks",
  "executionItems",
  "reminders",
  "nutritionContext",
  "operatingPlan",
  "operatingRhythm",
  "adaptiveTrustProfile",
  "milestones",
  "progressPhotos",
  "dailyCheckIns",
  "dailyBriefings",
  "briefingReconciliationWorkItems",
  "confidenceInitializationArtifacts",
  "analyses",
  "evidencePackages",
  "evidenceReviews",
  "canonicalEvidenceObjects",
  "trainingPerformanceEvents",
  "trainingPerformanceEventBatches",
  "canonicalExerciseLibrary",
  "piEnergyConfidenceWorkItems",
  "piEnergyFinalizationReceipts",
  "piTrainingConfidenceWorkItems",
  "piTrainingFinalizationReceipts",
  "piLowerLevelConfidenceWorkerRuns",
  "migrationMarkers",
  "goalConfidenceSnapshots",
  "goalConfidenceHistory",
  "goalConfidenceContinuitySeeds",
  "phaseReviewDecisions",
  "phaseReviewTransactions",
  "phaseStrategies",
  "phaseExpectedTrajectories",
  "phaseLifecycleReadModels",
]);

export const FOUNDATION_RUNTIME_METADATA_KEYS = Object.freeze([
  "version", "revision", "lastCommitId", "updatedAt", "importedAt",
]);
