import { Phase3Command } from "../commands/Phase3CommandService.js";
import { getProgressPhotoPoseContract } from "../../domain/models/progressPhotoPoseVocabulary.js";
import { ANALYSIS_DERIVATIVE_REQUIRED_MIME_TYPES, PHOTO_CONTAINER_MIME_TYPES } from "../../domain/services/ImageContainerDetection.js";
import {
  STAGED_DERIVATIVE_MAXIMUM_BYTES,
  STAGED_DERIVATIVE_MIME_TYPE,
  STAGED_EVIDENCE_MANIFEST_VERSION,
  STAGED_MAXIMUM_ORIGINALS,
  STAGED_ORIGINAL_MAXIMUM_BYTES,
  STAGED_RAW_ORIGINAL_MAXIMUM_BYTES,
  STAGED_SERVER_DERIVATIVE_GENERATION,
  stagedOriginalMaximumBytes,
} from "../../domain/services/StagedEvidenceArtifactManifest.js";

export const NativeProductionResource = Object.freeze({
  PROFILE: "profile",
  HOME: "home",
  GOALS: "goals",
  ACTIVE_GOAL: "active-goal",
  COMPLETED_GOAL: "completed-goal",
  OPERATING_PLAN: "operating-plan",
  PRIORITY: "priority",
  MORNING_CHECK_IN: "morning-check-in",
  WEIGHT: "weight",
  TRAINING_LOGGER: "training-logger",
  TRAINING_LANDING: "training-landing",
  TRAINING_REPORTING: "training-reporting",
  TRAINING_LIBRARY: "training-library",
  TRAINING_DAY: "training-day",
  TRAINING_SESSION: "training-session",
  TRAINING_EXERCISE: "training-exercise",
  NUTRITION: "nutrition",
  ACTIVITY: "activity",
  HEALTHKIT_ACTIVITY_CANARY: "healthkit-activity-canary",
  HEALTHKIT_SEP23_ACTIVITY_REPAIR_PREFLIGHT: "healthkit-sep23-activity-repair-preflight",
  ENERGY: "energy",
  DEXA: "dexa",
  PHOTOS: "photos",
  BRIEFING_HISTORY: "briefing-history",
  BRIEFING: "briefing",
  DEXA_EVENT: "dexa-event",
  PHOTO_EVENT: "photo-event",
  CONFIDENCE: "confidence",
  EVIDENCE_REVIEW: "evidence-review",
  EVIDENCE_REVIEW_QUEUE: "evidence-review-queue",
  TIMELINE: "timeline",
  OPERATING_PLAN_RECURRING_SUPPORT: "operating-plan-recurring-support",
  OPERATING_PLAN_NUTRITION_STRATEGY: "operating-plan-nutrition-strategy",
  OPERATING_PLAN_TRAINING_STRATEGY: "operating-plan-training-strategy",
  OPERATING_PLAN_PEPTIDE_SUPPORT: "operating-plan-peptide-support",
  OPERATING_PLAN_PROTOCOL_DOMAIN: "operating-plan-protocol-domain",
  OPERATING_PLAN_SUPPLEMENT_SUPPORT: "operating-plan-supplement-support",
  OPERATING_PLAN_SUPPLEMENT_STRATEGY_EDITOR: "operating-plan-supplement-strategy-editor",
  OPERATING_PLAN_ENERGY_STRATEGY: "operating-plan-energy-strategy",
  OPERATING_PLAN_COACHING_UPDATES: "operating-plan-coaching-updates",
});

const reads = Object.freeze([
  read("profile", "/api/v1/native/profile", "profile"),
  read("home", "/api/v1/native/read/home", "coreNavigation.getHome"),
  read("goals", "/api/v1/native/read/goals", "coreNavigation.getGoals"),
  read("active-goal", "/api/v1/native/read/active-goal", "activeGoal.getPreview"),
  read("completed-goal", "/api/v1/native/read/completed-goal", "completedGoal.getVisibleAbs"),
  read("operating-plan", "/api/v1/native/read/operating-plan", "coreNavigation.getOperatingPlan"),
  read("priority", "/api/v1/native/read/priority", "priorityNavigation.getPriorityDetail"),
  read("morning-check-in", "/api/v1/native/read/morning-check-in", "coreNavigation.getMorningCheckIn"),
  read("weight", "/api/v1/native/read/weight", "progressEvidence.getWeight", { pagination: "limit:1-365; default:90; canonical newest-first history" }),
  read("training-logger", "/api/v1/native/read/training-logger", "coreNavigation.getTrainingLogger"),
  read("training-landing", "/api/v1/native/read/training-landing", "trainingNavigation.getLanding"),
  read("training-reporting", "/api/v1/native/read/training-reporting", "trainingNavigation.getReporting.finishedPresentation"),
  read("training-library", "/api/v1/native/read/training-library", "trainingNavigation.getLibrary"),
  read("training-day", "/api/v1/native/read/training-day", "trainingNavigation.getDay"),
  read("training-session", "/api/v1/native/read/training-session", "trainingNavigation.getSession"),
  read("training-exercise", "/api/v1/native/read/training-exercise", "trainingNavigation.getExercise"),
  read("nutrition", "/api/v1/native/read/nutrition", "progressEvidence.getNutrition"),
  read("activity", "/api/v1/native/read/activity", "progressEvidence.getActivity"),
  read("healthkit-activity-canary", "/api/v1/native/read/healthkit-activity-canary", "healthKitCanary.getActivityValidation", { pagination: "required inclusive startDate/endDate; maximum 31 local dates" }),
  read("healthkit-sep23-activity-repair-preflight", "/api/v1/native/read/healthkit-sep23-activity-repair-preflight", "healthKitCanary.getSeptember23ActivityRepairPreflight"),
  read("energy", "/api/v1/native/read/energy", "progressEvidence.getEnergy"),
  read("dexa", "/api/v1/native/read/dexa", "progressEvidence.getDEXA"),
  read("photos", "/api/v1/native/read/photos", "progressPhotos.getNativePhotosTimeline", { pagination: "limit:1-50; default:12; canonical newest-first sessions" }),
  read("briefing-history", "/api/v1/native/read/briefing-history", "briefingNavigation.listNativeHistory", { pagination: "limit:1-50; default:20; cursor:opaque artifact identity" }),
  read("briefing", "/api/v1/native/read/briefing", "briefingNavigation.getNativeArtifact"),
  read("dexa-event", "/api/v1/native/read/dexa-event", "briefingNavigation.getDexaArtifact"),
  read("photo-event", "/api/v1/native/read/photo-event", "photoEventBriefing.getPhotoEvent"),
  read("confidence", "/api/v1/native/read/confidence", "activeGoal.getPreview"),
  read("evidence-review", "/api/v1/native/read/evidence-review", "evidenceReview.getReview"),
  read("evidence-review-queue", "/api/v1/native/read/evidence-review-queue", "coreNavigation.getLog"),
  read("timeline", "/api/v1/native/read/timeline", "evidenceTimeline.getPage", { pagination: "limit:1-200" }),
  read("operating-plan-recurring-support", "/api/v1/native/read/operating-plan-recurring-support", "coreNavigation.getRecurringSupport"),
  read("operating-plan-nutrition-strategy", "/api/v1/native/read/operating-plan-nutrition-strategy", "coreNavigation.getNutritionStrategyDetail"),
  read("operating-plan-training-strategy", "/api/v1/native/read/operating-plan-training-strategy", "coreNavigation.getTrainingStrategyDetail"),
  read("operating-plan-peptide-support", "/api/v1/native/read/operating-plan-peptide-support", "coreNavigation.getPeptideSupport"),
  read("operating-plan-protocol-domain", "/api/v1/native/read/operating-plan-protocol-domain", "coreNavigation.getOperatingPlanProtocolDomain"),
  read("operating-plan-supplement-support", "/api/v1/native/read/operating-plan-supplement-support", "coreNavigation.getSupplementSupport"),
  read("operating-plan-supplement-strategy-editor", "/api/v1/native/read/operating-plan-supplement-strategy-editor", "coreNavigation.getSupplementStrategyEditor"),
  read("operating-plan-energy-strategy", "/api/v1/native/read/operating-plan-energy-strategy", "coreNavigation.getEnergyStrategyDetail"),
  read("operating-plan-coaching-updates", "/api/v1/native/read/operating-plan-coaching-updates", "coreNavigation.getCoachingUpdatesDetail"),
]);

const writes = Object.freeze([
  write(Phase3Command.SUBMIT_WEIGHT, ["localDate", "value"], "If-Match required only when replacing a changed same-day Weight"),
  write(Phase3Command.SUBMIT_CHECK_IN, ["localDate", "value"], "If-Match required only when replacing a changed same-day Weight"),
  write(Phase3Command.COMPLETE_PRIORITY, ["priorityId", "occurrenceDate"], "If-Match required for the first occurrence completion; exact replay is a no-op"),
  write(Phase3Command.COMMIT_TRAINING_SESSION, ["sessionId", "localDate", "exercises"], "If-Match required when correcting an existing canonical Training session"),
  write(Phase3Command.UPSERT_NUTRITION_DAY, ["localDate", "dailyTotals"], "semantic fingerprint protects replacements; server assigns Goal and Phase"),
  write(Phase3Command.UPSERT_ACTIVITY_DAY, ["localDate", "dailyActivity", "sourceIdentity", "source"], "manual, typed, or screenshot provenance only; direct device-health sync is forbidden"),
  write(Phase3Command.INGEST_HEALTHKIT_OBSERVATIONS, ["batchId", "observations"], "source observations remain separate; Activity and Nutrition daily totals may canonicalize only inside the server-owned activation window into the quarantined HealthKit canonical day store; strategic Evidence eligibility is not decided by ingestion"),
  write(Phase3Command.EDIT_DEXA_REVIEW, ["reviewId", "evidenceObjectId", "measurements"], "If-Match required for every edit"),
  write(Phase3Command.COMMIT_EVIDENCE_REVIEW, ["reviewId"], "If-Match required to start the canonical Evidence Review lifecycle"),
  write(Phase3Command.DISPOSE_EVIDENCE_REVIEW, ["reviewId", "disposition"], "If-Match required; disposition must be discarded"),
  write(Phase3Command.RESOLVE_WORKOUT_RECONCILIATION, ["reviewId", "action"], "If-Match required; confirm requires one current Logger session identity and no_match omits it"),
  write(Phase3Command.SAVE_RECURRING_SUPPORT, ["protocolId", "protocolCategory", "executionId", "reminderId", "draft"], "If-Match required; expectedVersion compares against the execution item's own executionRevision"),
  write(Phase3Command.SAVE_NUTRITION_STRATEGY, ["protocolId", "expectedCurrentVersionId", "draft"], "If-Match not used; concurrency is enforced via expectedCurrentVersionId matching the protocol's own currentVersionId"),
  write(Phase3Command.ADD_TO_MY_LIBRARY, ["canonicalExerciseId"], "If-Match not used; idempotent add of an existing canonical exercise to My Library"),
  write(Phase3Command.CREATE_CANONICAL_EXERCISE, ["canonicalName", "primaryMuscleGroupId"], "If-Match not used; server rejects with 409 CANONICAL_EXERCISE_DUPLICATE when the full catalog already has a matching identity"),
  write(Phase3Command.SAVE_TRAINING_STRATEGY, ["protocolId", "expectedCurrentVersionId", "draft"], "If-Match not used; concurrency is enforced via expectedCurrentVersionId matching the protocol's own currentVersionId"),
  write(Phase3Command.SAVE_PEPTIDE_SUPPORT, ["protocolId", "draft"], "If-Match carries executionRevision when configured; omission is valid only while no execution exists"),
  write(Phase3Command.SAVE_SUPPLEMENT_SUPPORT, ["protocolId", "supplementVersionId", "draft"], "supplementVersionId protects the active strategy version; If-Match carries executionRevision when Support is configured"),
  write(Phase3Command.SAVE_SUPPLEMENT_STRATEGY, ["operation", "draft"], "create is idempotent by command identity; edit uses expectedCurrentVersionId inside the canonical successor transition"),
  write(Phase3Command.CHANGE_SUPPLEMENT_LIFECYCLE, ["protocolId", "operation", "expectedCurrentVersionId"], "pause/restore require the protocol's authoritative currentVersionId"),
  write(Phase3Command.SAVE_COACHING_UPDATES, ["protocolId", "expectedCurrentVersionId", "expectedSemanticDigest", "photoExpectedCurrentVersionId", "photoExpectedSemanticDigest", "dexaExpectedRevision", "draft"], "atomic composite save; If-Match carries global runtime revision alongside scoped semantic digest, both protocol versions, and DEXA executionRevision"),
]);

export const nativeProductionContractManifest = Object.freeze({
  contractVersion: "1",
  apiVersion: "v1",
  authority: "founder-production",
  authentication: "founder-device-bearer",
  bootstrap: Object.freeze({
    issuerEndpoint: "/api/v1/native/auth/pairing-credentials",
    issuerAuthentication: "founder-web-session",
    pairEndpoint: "/api/v1/native/auth/pair",
    credentialLifetimeSeconds: 600,
    credentialUse: "single-use",
    authority: "founder-production",
  }),
  sandboxAuthority: "physically-isolated-separate-contract",
  errorFormat: "application/problem+json; problemVersion=1",
  dateSemantics: "intended local dates are YYYY-MM-DD; timestamps are ISO-8601; timezone is explicit",
  media: Object.freeze({
    endpoint: "/api/v1/native/media/{mediaId}",
    identity: "opaque canonical media ID",
    authorization: "bearer, owner-scoped",
    cache: "private, no-store",
  }),
  evidenceIntake: Object.freeze({
    createEndpoint: "/api/v1/native/evidence/intakes",
    statusEndpoint: "/api/v1/native/evidence/intakes/{intakeId}",
    contentType: "multipart/form-data",
    acceptedEvidenceTypes: Object.freeze(["dexa_scan", "nutrition", "activity_day", "training", "photo_session"]),
    activitySources: Object.freeze(["screenshot", "manual-command"]),
    dexa: "one validated BodySpec PDF; asynchronous interpretation stages an Evidence Review",
    progressPhotos: "one or more validated images with Founder-confirmed pose identities and session conditions; asynchronous staging converges on the same canonical PhotoSession confirmation lifecycle as Web",
    idempotency: "Idempotency-Key equals submissionIdentity; durable receipt replay",
    authority: "founder-production",
    auth: "founder-device-bearer",
    // Staged media: one bounded JSON declaration, then one bounded request per
    // artifact. Media is complete only when every declared artifact is stored
    // and verified; interpretation waits for complete media.
    stagedMedia: Object.freeze({
      createEndpoint: "/api/v1/native/evidence/intakes/staged",
      createContentType: "application/json",
      artifactEndpoint: "/api/v1/native/evidence/intakes/{intakeId}/artifacts/{artifactId}",
      artifactMethod: "PUT",
      manifestVersion: STAGED_EVIDENCE_MANIFEST_VERSION,
      evidenceTypes: Object.freeze(["photo_session"]),
      originalTypes: Object.freeze([...PHOTO_CONTAINER_MIME_TYPES]),
      derivativeType: STAGED_DERIVATIVE_MIME_TYPE,
      originalMaximumBytes: STAGED_ORIGINAL_MAXIMUM_BYTES,
      rawOriginalMaximumBytes: STAGED_RAW_ORIGINAL_MAXIMUM_BYTES,
      originalMaximumBytesByType: Object.freeze(Object.fromEntries(PHOTO_CONTAINER_MIME_TYPES.map((type) => [type, stagedOriginalMaximumBytes(type)]))),
      derivativeMaximumBytes: STAGED_DERIVATIVE_MAXIMUM_BYTES,
      maximumOriginals: STAGED_MAXIMUM_ORIGINALS,
      heicDerivativeRequired: !STAGED_SERVER_DERIVATIVE_GENERATION,
      derivativeRequiredTypes: Object.freeze([...ANALYSIS_DERIVATIVE_REQUIRED_MIME_TYPES]),
      serverDerivativeGeneration: STAGED_SERVER_DERIVATIVE_GENERATION,
      artifactIdentity: "artifact_{submissionIdentityWithoutDashes}_{ordinal}; ordinals are contiguous across originals and derivatives",
      idempotency: "declaration replay returns the same intake; an already stored artifact is acknowledged without a second object",
      completion: "media is stored only when every declared artifact is verified against its declaration; incomplete media never interprets",
      originals: "preserved verbatim, HEIC/HEIF and Apple ProRAW DNG included; the canonical photo is always the original",
    }),
    // Orientation, contraction, and pose variant are not independent. Intake
    // accepts only these combinations (`PHOTO_IDENTITY_NON_CANONICAL`
    // otherwise), and clients derive their pose controls from this table.
    poseContract: getProgressPhotoPoseContract(),
  }),
  healthKitIngestion: Object.freeze({
    commandType: Phase3Command.INGEST_HEALTHKIT_OBSERVATIONS,
    contractVersion: "healthkit-ingestion-v1",
    maximumBatchSize: 100,
    observationTypes: Object.freeze(["activity_summary", "workout", "quantity_sample"]),
    // Accepted in addition to `observationTypes`. Kept separate so an installed
    // Native build that pins the original three-type set keeps working.
    additionalObservationTypes: Object.freeze(["nutrition_daily_total"]),
    ingestionPurposes: Object.freeze(["operational", "validation_only"]),
    defaultIngestionPurpose: "operational",
    validationOnly: "permanently raw, non-canonical, and non-strategic; purpose is immutable per V1 source identity",
    activityActivation: "server-owned, disabled until an explicit Founder-approved canonical effective date is configured; no historical backfill",
    canonicalDailyActivation: "server-owned policy scoped to explicit domains (activity, nutrition) and an exact local-date window of at most 7 days; disabled by default; no historical backfill; canonical days are stored in healthKitCanonicalDays, never in strategic Evidence",
    workoutCanonicalActivation: "dormant: a separate server-owned Workout policy (exact window of at most 3 local dates, quarantined, no backfill, no auto-confirmed links) governs canonical Apple workouts and strength link candidates; disabled by default",
    nutritionDailyTotal: "nutrition_daily_total carries HealthKit daily statistics across all sources for calories, protein_g, carbs_g, fat_g only; no meal objects; device-scoped source revision; partial_day or complete_day coverage",
    strategicEvidenceEligibility: "quarantined: HealthKit-derived canonical days are never V3, Confidence, or briefing Evidence during the proving period",
    validationDiagnostic: "/api/v1/native/read/healthkit-activity-canary requires bounded startDate and endDate",
    identity: "V1 server hash using a NUL separator across source bundle, observation type, and immutable HealthKit external ID; daily snapshots also include device and source revision",
    occurrenceTime: "stored separately from server receipt time",
    dailyActivity: "daily_total_including_workouts only; workout calories are never added to the daily total",
    workoutReconciliation: "server-owned candidate matching; strength detail remains TrainingSession-owned",
    evidenceEligibility: "not assessed by ingestion",
    queryCursor: "device-owned and never accepted or advanced by the server contract",
  }),
  reads,
  writes,
});

function read(resource, endpoint, service, extra = {}) {
  return Object.freeze({
    resource,
    endpoint,
    service,
    auth: "founder-device-bearer",
    authority: "founder-production",
    goalPhase: "server-resolved and historically frozen where applicable",
    media: "opaque references only",
    pagination: extra.pagination ?? "bounded by canonical read service",
  });
}

function write(commandType, requiredPayloadFields, revision) {
  return Object.freeze({
    commandType,
    endpoint: "/api/v1/native/commands",
    requiredPayloadFields: Object.freeze(requiredPayloadFields),
    auth: "founder-device-bearer",
    authority: "founder-production",
    idempotency: "Idempotency-Key and canonical command receipt",
    revision,
    response: "canonical identity, outcome, current revision, and continuation work identities when created",
  });
}
