import { Phase3Command } from "../commands/Phase3CommandService.js";

export const NativeProductionResource = Object.freeze({
  PROFILE: "profile",
  HOME: "home",
  GOALS: "goals",
  ACTIVE_GOAL: "active-goal",
  COMPLETED_GOAL: "completed-goal",
  OPERATING_PLAN: "operating-plan",
  PRIORITY: "priority",
  MORNING_CHECK_IN: "morning-check-in",
  WEIGHT: "weight",
  TRAINING_LOGGER: "training-logger",
  TRAINING_LANDING: "training-landing",
  TRAINING_REPORTING: "training-reporting",
  TRAINING_LIBRARY: "training-library",
  TRAINING_DAY: "training-day",
  TRAINING_SESSION: "training-session",
  TRAINING_EXERCISE: "training-exercise",
  NUTRITION: "nutrition",
  ACTIVITY: "activity",
  ENERGY: "energy",
  DEXA: "dexa",
  PHOTOS: "photos",
  BRIEFING_HISTORY: "briefing-history",
  BRIEFING: "briefing",
  DEXA_EVENT: "dexa-event",
  PHOTO_EVENT: "photo-event",
  CONFIDENCE: "confidence",
  EVIDENCE_REVIEW: "evidence-review",
  EVIDENCE_REVIEW_QUEUE: "evidence-review-queue",
  TIMELINE: "timeline",
});

const reads = Object.freeze([
  read("profile", "/api/v1/native/profile", "profile"),
  read("home", "/api/v1/native/read/home", "coreNavigation.getHome"),
  read("goals", "/api/v1/native/read/goals", "coreNavigation.getGoals"),
  read("active-goal", "/api/v1/native/read/active-goal", "activeGoal.getPreview"),
  read("completed-goal", "/api/v1/native/read/completed-goal", "completedGoal.getVisibleAbs"),
  read("operating-plan", "/api/v1/native/read/operating-plan", "coreNavigation.getOperatingPlan"),
  read("priority", "/api/v1/native/read/priority", "priorityNavigation.getPriorityDetail"),
  read("morning-check-in", "/api/v1/native/read/morning-check-in", "coreNavigation.getMorningCheckIn"),
  read("weight", "/api/v1/native/read/weight", "weightSummary.getCurrentWeight"),
  read("training-logger", "/api/v1/native/read/training-logger", "coreNavigation.getTrainingLogger"),
  read("training-landing", "/api/v1/native/read/training-landing", "trainingNavigation.getLanding"),
  read("training-reporting", "/api/v1/native/read/training-reporting", "trainingNavigation.getReporting"),
  read("training-library", "/api/v1/native/read/training-library", "trainingNavigation.getLibrary"),
  read("training-day", "/api/v1/native/read/training-day", "trainingNavigation.getDay"),
  read("training-session", "/api/v1/native/read/training-session", "trainingNavigation.getSession"),
  read("training-exercise", "/api/v1/native/read/training-exercise", "trainingNavigation.getExercise"),
  read("nutrition", "/api/v1/native/read/nutrition", "progressEvidence.getNutrition"),
  read("activity", "/api/v1/native/read/activity", "progressEvidence.getActivity"),
  read("energy", "/api/v1/native/read/energy", "progressEvidence.getEnergy"),
  read("dexa", "/api/v1/native/read/dexa", "progressEvidence.getDEXA"),
  read("photos", "/api/v1/native/read/photos", "progressPhotos.getPhotosTimeline"),
  read("briefing-history", "/api/v1/native/read/briefing-history", "briefingNavigation.listNativeHistory", { pagination: "limit:1-50; default:20; cursor:opaque artifact identity" }),
  read("briefing", "/api/v1/native/read/briefing", "briefingNavigation.getArtifact"),
  read("dexa-event", "/api/v1/native/read/dexa-event", "briefingNavigation.getDexaArtifact"),
  read("photo-event", "/api/v1/native/read/photo-event", "photoEventBriefing.getPhotoEvent"),
  read("confidence", "/api/v1/native/read/confidence", "activeGoal.getPreview"),
  read("evidence-review", "/api/v1/native/read/evidence-review", "evidenceReview.getReview"),
  read("evidence-review-queue", "/api/v1/native/read/evidence-review-queue", "coreNavigation.getLog"),
  read("timeline", "/api/v1/native/read/timeline", "evidenceTimeline.getPage", { pagination: "limit:1-200" }),
]);

const writes = Object.freeze(Object.values(Phase3Command).map((commandType) => Object.freeze({
  commandType,
  endpoint: "/api/v1/native/commands",
  auth: "founder-device-bearer",
  authority: "founder-production",
  idempotency: "Idempotency-Key and canonical command receipt",
  revision: "If-Match required for correction commands",
})));

export const nativeProductionContractManifest = Object.freeze({
  contractVersion: "1",
  apiVersion: "v1",
  authority: "founder-production",
  authentication: "founder-device-bearer",
  bootstrap: Object.freeze({
    issuerEndpoint: "/api/v1/native/auth/pairing-credentials",
    issuerAuthentication: "founder-web-session",
    pairEndpoint: "/api/v1/native/auth/pair",
    credentialLifetimeSeconds: 600,
    credentialUse: "single-use",
    authority: "founder-production",
  }),
  sandboxAuthority: "physically-isolated-separate-contract",
  errorFormat: "application/problem+json; problemVersion=1",
  dateSemantics: "intended local dates are YYYY-MM-DD; timestamps are ISO-8601; timezone is explicit",
  media: Object.freeze({
    endpoint: "/api/v1/native/media/{mediaId}",
    identity: "opaque canonical media ID",
    authorization: "bearer, owner-scoped",
    cache: "private, no-store",
  }),
  reads,
  writes,
});

function read(resource, endpoint, service, extra = {}) {
  return Object.freeze({
    resource,
    endpoint,
    service,
    auth: "founder-device-bearer",
    authority: "founder-production",
    goalPhase: "server-resolved and historically frozen where applicable",
    media: "opaque references only",
    pagination: extra.pagination ?? "bounded by canonical read service",
  });
}
