import { notFound } from "next/navigation";
import ExecutionItemBuilderScreen from "../../../../../screens/ExecutionItemBuilderScreen";
import RecurringSupportEditorScreen from "../../../../../screens/RecurringSupportEditorScreen";
import { saveExecutionItem, saveFoamRollingSupport } from "./actions";
import { loadProductionBoundedFounderReadContext } from "../../../../../application/composition/productionApplicationComposition";
import { createProgressPhotosExecutionHydrationModel } from "../../../../../domain/services/ProgressPhotosExecutionScheduleService";
import { createRecurringSupportHydrationModel } from "../../../../../domain/services/RecurringSupportManagementService";
export const dynamic="force-dynamic";
export default async function Page({params}){const {executionId}=await params;const{repositories,runtime}=await loadProductionBoundedFounderReadContext({collections:["user","executionItems","protocols","reminders"]});const item=await repositories.executionItems.getExecutionItemById(executionId);if(!item)notFound();if(executionId==="execution_foam_roll"){const user=await repositories.users.getCurrentUser();const protocol=await repositories.protocols.getProtocolById(item.linkedProtocolId);const reminders=await repositories.reminders.listReminders(user.id);const reminder=reminders.find((entry)=>entry.id==="reminder_foam_roll_daily"&&entry.linkedEntityId===protocol?.id)??null;if(!protocol||protocol.userId!==user.id||protocol.category!=="recovery"||protocol.status!=="active"||!reminder)notFound();return <RecurringSupportEditorScreen action={saveFoamRollingSupport.bind(null,{executionId:item.id,expectedRevision:item.executionRevision??1,protocolId:protocol.id,reminderId:reminder.id})} hydration={createRecurringSupportHydrationModel({executionItem:item,protocol,reminder})} protocol={protocol}/>;}const hydration=executionId==="execution_progress_photos"?createProgressPhotosExecutionHydrationModel(runtime):null;return <ExecutionItemBuilderScreen action={saveExecutionItem} context={hydration?.context} item={hydration?.item??item}/>;}
