import { notFound } from "next/navigation";
import { FounderRepositories } from "../../../../../data/repositories/founderRepositories";
import ExecutionItemBuilderScreen from "../../../../../screens/ExecutionItemBuilderScreen";
import RecurringSupportEditorScreen from "../../../../../screens/RecurringSupportEditorScreen";
import { saveExecutionItem, saveFoamRollingSupport } from "./actions";
import { loadApplicationCanonicalRuntime } from "../../../../../application/runtime/ApplicationCanonicalRuntime";
import { createProgressPhotosExecutionHydrationModel } from "../../../../../domain/services/ProgressPhotosExecutionScheduleService";
import { createRecurringSupportHydrationModel } from "../../../../../domain/services/RecurringSupportManagementService";
export const dynamic="force-dynamic";
export default async function Page({params}){const {executionId}=await params;return FounderRepositories.runInReadScope(async()=>{const item=await FounderRepositories.executionItems.getExecutionItemById(executionId);if(!item)notFound();if(executionId==="execution_foam_roll"){const user=await FounderRepositories.users.getCurrentUser();const protocol=await FounderRepositories.protocols.getProtocolById(item.linkedProtocolId);const reminders=await FounderRepositories.reminders.listReminders(user.id);const reminder=reminders.find((entry)=>entry.id==="reminder_foam_roll_daily"&&entry.linkedEntityId===protocol?.id)??null;if(!protocol||protocol.userId!==user.id||protocol.category!=="recovery"||protocol.status!=="active"||!reminder)notFound();return <RecurringSupportEditorScreen action={saveFoamRollingSupport.bind(null,{executionId:item.id,expectedRevision:item.executionRevision??1,protocolId:protocol.id,reminderId:reminder.id})} hydration={createRecurringSupportHydrationModel({executionItem:item,protocol,reminder})} protocol={protocol}/>;}const hydration=executionId==="execution_progress_photos"?createProgressPhotosExecutionHydrationModel(await loadApplicationCanonicalRuntime()):null;return <ExecutionItemBuilderScreen action={saveExecutionItem} context={hydration?.context} item={hydration?.item??item}/>;},{readModel:"route.execution-detail"});}
