import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import net from "node:net";
import { DAILY_BRIEFING_MIGRATION_VERSION, migrateDailyBriefingRuntimeStore, sha } from "../src/data/migrations/DailyBriefingMigration.js";
import { stableSerialize } from "../src/data/repositories/DailyBriefingHistory.js";

const args=parseArgs(process.argv.slice(2));
if(!args.source||!args.outputDir){console.error('Usage: node scripts/migrateDailyBriefingHistory.js --source "<runtime-store-copy.json>" --output-dir "<migration-output>"');process.exit(2);}
if(await portOpen(3000)){console.error("Preflight failed: port 3000 is active. Stop the Next.js writer manually before migration.");process.exit(3);}
const source=path.resolve(args.source),out=path.resolve(args.outputDir);
if(!fs.existsSync(source)||!fs.statSync(source).isFile())throw new Error("Source must be an existing regular file.");
fs.mkdirSync(out,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,"-");const lock=path.join(out,"daily-briefing-migration.lock");
if(fs.existsSync(lock)){console.error("Migration lock exists:",fs.readFileSync(lock,"utf8"));process.exit(4);}
const bytes=fs.readFileSync(source);const sourceHash=sha(bytes);const prefix=sourceHash.slice(0,12);const backup=path.join(out,`${path.basename(source)}.backup-${stamp}-${prefix}`);const candidatePath=path.join(out,`${path.basename(source)}.candidate-${stamp}-${prefix}`);const reportBase=path.join(out,`daily-briefing-migration-report-${stamp}`);
const lockData={migrationVersion:DAILY_BRIEFING_MIGRATION_VERSION,pid:process.pid,hostname:os.hostname(),startedAt:new Date().toISOString(),source,sourceHash,candidatePath,backup};
fs.writeFileSync(lock,JSON.stringify(lockData,null,2),{flag:"wx"});let clean=false;
try{fs.copyFileSync(source,backup,fs.constants.COPYFILE_EXCL);const backupBytes=fs.readFileSync(backup);if(backupBytes.length!==bytes.length||sha(backupBytes)!==sourceHash)throw new Error("Backup verification failed.");const parsed=JSON.parse(backupBytes.toString("utf8"));const {candidate,report}=migrateDailyBriefingRuntimeStore(parsed);const temp=`${candidatePath}.tmp-${process.pid}`;const serialized=`${stableSerialize(candidate)}\n`;fs.writeFileSync(temp,serialized,{flag:"wx"});fs.renameSync(temp,candidatePath);const candidateBytes=fs.readFileSync(candidatePath);JSON.parse(candidateBytes.toString("utf8"));const complete={...report,startedAt:lockData.startedAt,completedAt:new Date().toISOString(),environment:{hostname:os.hostname(),pid:process.pid,node:process.version},source:{path:source,bytes:bytes.length,hash:sourceHash,mtime:fs.statSync(source).mtime.toISOString()},backup:{path:backup,bytes:backupBytes.length,hash:sha(backupBytes),verified:true},candidate:{path:candidatePath,bytes:candidateBytes.length,hash:sha(candidateBytes)},lock:lockData,sizeReduction:{bytes:bytes.length-candidateBytes.length,percent:+((1-candidateBytes.length/bytes.length)*100).toFixed(2)}};fs.writeFileSync(`${reportBase}.json`,JSON.stringify(complete,null,2),{flag:"wx"});fs.writeFileSync(`${reportBase}.txt`,summary(complete),{flag:"wx"});clean=true;console.log(summary(complete));process.exitCode=complete.promotionEligible?0:5;}catch(error){fs.writeFileSync(`${reportBase}.json`,JSON.stringify({migrationVersion:DAILY_BRIEFING_MIGRATION_VERSION,status:"failed-before-or-after-candidate",promotionEligible:false,error:error.stack??String(error),source:{path:source,hash:sourceHash},backup:{path:backup,exists:fs.existsSync(backup)},candidate:{path:candidatePath,exists:fs.existsSync(candidatePath)}},null,2),{flag:"wx"});clean=true;console.error(error);process.exitCode=6;}finally{if(clean)fs.unlinkSync(lock);}
function parseArgs(xs){const o={};for(let i=0;i<xs.length;i+=2)o[xs[i].replace(/^--/,"").replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=xs[i+1];return o;}
function portOpen(port){return new Promise(resolve=>{const s=net.createConnection({host:"127.0.0.1",port});s.once("connect",()=>{s.destroy();resolve(true)});s.once("error",()=>resolve(false));s.setTimeout(500,()=>{s.destroy();resolve(false)});});}
function summary(r){return [`Daily Briefing migration: ${r.status}`,`Promotion eligible: ${r.promotionEligible}`,`Source: ${r.source.bytes} bytes ${r.source.hash}`,`Backup: ${r.backup.bytes} bytes ${r.backup.hash}`,`Candidate: ${r.candidate.bytes} bytes ${r.candidate.hash}`,`Artifacts: ${r.artifactAccounting.uniqueVariants} unique / ${r.artifactAccounting.occurrences} occurrences`,`Conflicts: ${r.conflictAccounting.length}; malformed: ${r.malformedEntries.length}`,`History depth: ${r.structuralValidation.maxSourceDepth} -> ${r.structuralValidation.maxCandidateDepth}`].join("\n");}
