// End-to-end click test of the simulator. Usage: PLAYWRIGHT_NODE_MODULES=... node test-sim.mjs
import fs from 'node:fs'; import path from 'node:path'; import { createRequire } from 'node:module'; import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url)); const root = path.join(dir, '..');
const { chromium } = createRequire(path.join(process.env.PLAYWRIGHT_NODE_MODULES, 'package.json'))('playwright');
const html = fs.readFileSync(path.join(root, 'goal-adaptation-simulator.html'), 'utf8');
const doc = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body>${html}</body></html>`;
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
const shots = path.join(dir, 'screens'); fs.mkdirSync(shots, { recursive: true });
const results = []; const ok = (name, cond, info = '') => results.push({ name, pass: !!cond, info });
const p = await b.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 1 });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.setContent(doc, { waitUntil: 'networkidle' }); await p.waitForTimeout(200);
const act = async (a, arg) => { const sel = arg !== undefined ? `#phone [data-act="${a}"][data-arg="${arg}"]` : `#phone [data-act="${a}"]`; await p.click(sel); await p.waitForTimeout(40); };
const ctl = async (c, arg) => { await p.click(arg !== undefined ? `[data-ctl="${c}"][data-arg="${arg}"]` : `[data-ctl="${c}"]`); await p.waitForTimeout(40); };
const text = () => p.evaluate(() => document.getElementById('phone').innerText);
const st = () => p.evaluate(() => ({ screen: S.screen, phase: S.phase, eat: S.plan.eat, goal: S.plan.goal, balance: S.plan.balance, v: S.versions[0].v, bf: bf(), gained: S.gained, qc: !!S.qc, stack: S.stack.length }));
const shot = async (n) => { await (await p.$('#phone')).screenshot({ path: path.join(shots, `${n}.png`) }); };

ok('starts on Home building', (await text()).includes('Lean Mass Build') && (await text()).includes('CONFIDENCE'));
await shot('01-home-start');
await act('openBriefing'); ok('DEXA briefing has decision last', /Review your goal options[\s\S]*Nothing changes until you approve\.?\s*$/.test((await text()).trim()));
await act('openOptions'); ok('Option B comparison', (await text()).includes('Lean out first') && (await text()).includes('Keep building'));
await shot('02-options');
await act('back'); ok('back returns to briefing', (await st()).screen === 'briefing');
await act('openOptions'); await act('chooseLean');
let s = await st(); ok('lean draft default −450 → eat 1,767', s.screen === 'leanSetup' && (await p.evaluate(() => S.draft.plan.eat)) === 1767);
await act('setCompletion', 'hybrid'); await act('weeks', '1'); ok('hybrid with 7 weeks', (await p.evaluate(() => S.draft.completion)).weeks === 7);
await act('openEnergy'); ok('one-time explainer first', (await st()).screen === 'explainer');
await act('explainerDone'); ok('energy screen after explainer', (await st()).screen === 'energy');
await act('split', 'blend'); let d = await p.evaluate(() => S.draft.plan); ok('blend −450 → eat 1,892 goal 1,025 (1:1)', d.eat === 1892 && d.goal === 1025, JSON.stringify(d));
await act('split', 'eat'); d = await p.evaluate(() => S.draft.plan); ok('eat less → 1,667 / 800', d.eat === 1667 && d.goal === 800);
await act('bal', '-25'); d = await p.evaluate(() => S.draft.plan); ok('step −25 → −475, eat 1,642', d.balance === -475 && d.eat === 1642);
await act('balReset'); await act('split', 'suggested'); d = await p.evaluate(() => S.draft.plan); ok('reset to suggested 1,767/900', d.eat === 1767 && d.goal === 900);
await shot('03-energy');
await act('back'); ok('energy back → setup', (await st()).screen === 'leanSetup');
await act('openEnergy'); ok('explainer not repeated', (await st()).screen === 'energy'); await act('back');
await act('openHub'); await shot('04-hub');
await act('openTraining'); await act('prog', 'Conservative'); await act('back');
await act('openRecovery'); await act('addRecovery', 'Stretching'); await act('sleep', '1'); await act('back');
await act('openSupplements'); await act('addSupp', 'Creatine'); await act('back');
await act('openTracking'); await act('toggle', 'dexa'); await act('back');
ok('hub shows changes', /changing/.test(await text()));
await act('openReview'); const rv = await text(); ok('review lists numeric changes only', rv.includes('1,767') && rv.includes('Conservative') && !/walk/i.test(rv));
await shot('05-review');
await act('approve'); s = await st(); ok('approved → Home leaning v2', s.phase === 'leaning' && s.v === 2 && (await text()).includes('Leaning'));
await shot('06-home-leaning');
ok('Home leaning keeps primary goal and paused build', /PRIMARY GOAL[\s\S]*PAUSED[\s\S]*Lean Mass Build/.test(await text()));
await act('openGoals'); ok('Goals shows temporary phase + history', (await text()).includes('Now · temporary phase'.toUpperCase()) || (await text()).includes('Leaning'));
await shot('07-goals-leaning');
await act('tab', 'home');
await ctl('response', 'slower'); await ctl('advance'); await ctl('advance'); await ctl('advance');
s = await st(); ok('Quick Calibration offered after 3 slower weeks', s.qc && (await text()).includes('Quick calibration'.toUpperCase()) || s.qc, JSON.stringify(s));
await shot('08-weekly-qc');
await act('qcOpt', 'blend'); const before = await st(); await act('qcAccept'); s = await st();
ok('QC blend: eat −100, goal +100, balance −200 deeper', s.eat === before.eat - 100 && s.goal === before.goal + 100 && s.balance === before.balance - 200, `${JSON.stringify(before)} → ${JSON.stringify(s)}`);
await ctl('jump', 'midweek'); ok('Midweek never proposes', !/Accept|Deepen/.test(await text()));
await ctl('finish'); s = await st(); ok('phase completes → DEXA decision', s.phase === 'leaningComplete' && s.screen === 'briefing', JSON.stringify(s));
await shot('09-dexa-complete');
await act('back'); ok('Home phase complete concise + priority', (await text()).includes('Leaning complete') && (await text()).includes('Choose your next phase'));
await shot('10-home-complete');
await act('openNext'); ok('next step shows honest lean change', /Lean mass \(DEXA\)/.test(await text()));
await act('pickNext', 'resume'); await act('nextReview'); await act('approve'); s = await st();
ok('resume → building again, new version', s.phase === 'resumed' && (await text()).includes('Lean Mass Build'));
await shot('11-home-resumed');
await act('openGoals'); ok('undo available', (await text()).includes('Undo last')); await act('undo'); s = await st(); ok('undo restores leaningComplete', s.phase === 'leaningComplete');
await ctl('reset'); s = await st(); ok('reset → initial', s.phase === 'building' && s.v === 1 && s.eat === 2500);
// alternative path: keep building
await act('openBriefing'); await act('openOptions'); await act('chooseKeepBuilding');
await act('gr', 'max:0.5'); await act('gr', 'max:0.5'); await act('gr', 'max:0.5'); await act('gr', 'max:0.5'); await act('gr', 'max:0.5');
await act('date', 'Feb 15'); await act('openReview'); await act('approve'); s = await st();
ok('keep-building path approves new range', s.phase === 'keepBuilding' && (await p.evaluate(() => S.guardrail.max)) === 11.5);
await ctl('reset'); await act('openBriefing'); await act('notNow'); await act('notNowPick', 'remove'); ok('not now removes Home item', !(await text()).includes('Review goal options'));
await ctl('theme', 'light'); await shot('12-home-mineral');
await ctl('jump', 'monthly'); ok('monthly briefing renders, no proposal', (await text()).includes('Month Ahead'.toUpperCase()) || (await text()).includes('Month Ahead'));
await ctl('jump', 'photo'); ok('photo event never recommends', (await text()).includes('never trigger a recommendation'));
ok('simulation label present', (await p.evaluate(() => document.body.innerText)).includes('Functional UX simulation, not the Native visual spec'));
ok('no page errors', errors.length === 0, errors.join(' | '));
await p.close();
// mobile viewport
const m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
const merr = []; m.on('pageerror', (e) => merr.push(e.message));
await m.setContent(doc, { waitUntil: 'networkidle' }); await m.waitForTimeout(200);
const ov = await m.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
ok('mobile 390 no horizontal overflow', ov <= 0, String(ov)); ok('mobile no errors', merr.length === 0, merr.join('|'));
await m.screenshot({ path: path.join(shots, '13-mobile-390.png') });
await b.close();
fs.writeFileSync(path.join(dir, 'test-results.json'), JSON.stringify(results, null, 2));
const failed = results.filter((r) => !r.pass);
console.log(`${results.length - failed.length}/${results.length} passed`); failed.forEach((f) => console.log('FAIL', f.name, f.info));
