var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/profile/protocols/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04k_lkc._.js")
R.c("server/chunks/ssr/0qpb_next_dist_006441x._.js")
R.c("server/chunks/ssr/0qpb_next_dist_esm_build_templates_app-page_1ym15_u.js")
R.c("server/chunks/ssr/0qpb_next_dist_02n_efy._.js")
R.c("server/chunks/ssr/0qpb_next_dist_0v5d0ln._.js")
R.c("server/chunks/ssr/[root-of-the-server]__130x_bb._.js")
R.c("server/chunks/ssr/0qpb_next_dist_1n01_14._.js")
R.c("server/chunks/ssr/0qpb_next_dist_compiled_0at_4t8._.js")
R.c("server/chunks/ssr/_tmp_windows-deploy-4758bd37_src_1vbuwxt._.js")
R.c("server/chunks/ssr/_tmp_windows-deploy-4758bd37_src_app_error_17r8112.js")
R.c("server/chunks/ssr/0qpb_next_dist_client_components_0ib9rvl._.js")
R.c("server/chunks/ssr/0qpb_next_dist_client_components_builtin_forbidden_0vc4cp7.js")
R.c("server/chunks/ssr/0qpb_next_dist_client_components_builtin_unauthorized_1qgof6q.js")
R.c("server/chunks/ssr/0qpb_next_dist_client_components_builtin_global-error_0zwgl9g.js")
R.c("server/chunks/ssr/1q71__next-internal_server_app_profile_protocols_page_actions_17t8n0r.js")
R.m(751383)
module.exports=R.m(751383).exports
