// GENERATED by ios/Scripts/generate_pose_contract.py from
// contracts/progress-photo-pose-contract.v1.json. Do not edit by hand:
// the Server vocabulary owns this table and a test fails if this file drifts.

/// The Server's canonical Progress Photo pose combinations, verbatim.
/// `ProgressPhotoPoseContract` derives every Native control and gate from it.
enum ProgressPhotoPoseContractData {
    static let version = "progress-photo-pose-contract-v1"

    struct Combination: Equatable, Sendable {
        let id: String
        let label: String
        let orientation: String
        let contractionState: String
        let poseVariant: String
    }

    static let combinations: [Combination] = [
        .init(id: "front-relaxed", label: "Front Relaxed", orientation: "front", contractionState: "relaxed", poseVariant: "standard"),
        .init(id: "back-relaxed", label: "Rear Relaxed", orientation: "rear", contractionState: "relaxed", poseVariant: "standard"),
        .init(id: "back-flexed", label: "Rear Flexed — Double Biceps", orientation: "rear", contractionState: "flexed", poseVariant: "double_biceps"),
        .init(id: "side-relaxed", label: "Side Relaxed", orientation: "side_unspecified", contractionState: "relaxed", poseVariant: "standard"),
        .init(id: "left-side-relaxed", label: "Left Side Relaxed", orientation: "left_side", contractionState: "relaxed", poseVariant: "standard"),
        .init(id: "right-side-relaxed", label: "Right Side Relaxed", orientation: "right_side", contractionState: "relaxed", poseVariant: "standard"),
        .init(id: "front-flexed", label: "Front Flexed", orientation: "front", contractionState: "flexed", poseVariant: "standard"),
    ]
}
