import { notFound } from "next/navigation";
import { loadProductionBoundedFounderReadContext } from "../../../../../../application/composition/productionApplicationComposition";
import { classifyPeptideExecutionState,createPeptideSupportHydrationModel,PeptideExecutionState } from "../../../../../../domain/services/PeptideExecutionManagementService";
import { PeptideExecutionDetailScreen } from "../../../../../../screens/PeptideExecutionScreen";
import PeptideSupportEditorScreen from "../../../../../../screens/PeptideSupportEditorScreen";
import { savePeptideExecution } from "./actions";
import { getLocalDateKey,resolveLocalTimeZone } from "../../../../../../domain/utils/localDate";
export const dynamic="force-dynamic";
export default async function Page({params,searchParams}){const{protocolId}=await params;const query=await searchParams;const{repositories}=await loadProductionBoundedFounderReadContext({collections:["user","protocols","executionItems","reminders"]});const user=await repositories.users.getCurrentUser();const[protocol,items,reminders]=await Promise.all([repositories.protocols.getProtocolById(protocolId),repositories.executionItems.listExecutionItems(user.id),repositories.reminders.listReminders(user.id)]);if(!protocol||protocol.userId!==user.id||protocol.category!=="peptide"||protocol.status!=="active")notFound();const classification=classifyPeptideExecutionState({protocol,executionItems:items});if(classification.state===PeptideExecutionState.INVALID)notFound();const item=classification.record;const timezone=resolveLocalTimeZone(user.timeZone??user.timezone);const localDate=getLocalDateKey(new Date(),timezone);if(query?.edit==="1"){const reminder=reminders.find((entry)=>entry.type==="protocol_reminder"&&entry.linkedEntityId===protocol.id)??null;return <PeptideSupportEditorScreen action={savePeptideExecution.bind(null,{protocolId,expectedRevision:item?.executionRevision??(item?1:null),supportEditor:"peptide_support_v1"})} hydration={createPeptideSupportHydrationModel({executionItem:item,protocol,reminder})} protocol={protocol}/>;}return <PeptideExecutionDetailScreen item={item} protocol={protocol} localDate={localDate} supportTerminology/>;}
